// @generated by packages/reducer-contract/scripts/generate-kotlin.mjs
// DO NOT EDIT BY HAND. Edit schema/reducer-runtime*.json and rerun
// `pnpm --filter=@dreamboard/reducer-contract generate`.

@file:Suppress("ktlint:standard:filename", "MaximumLineLength", "MaxLineLength")

package com.dreamboard.reducer.contract

import kotlinx.serialization.SerialName
import kotlinx.serialization.SerializationStrategy
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonElement

@Serializable
data class ContinuationToken(
    @SerialName("id")
    val id: String,
    @SerialName("data")
    val data: JsonElement,
)

@Serializable
@JsonClassDiscriminator("kind")
sealed interface GameInput {
    @Serializable
    @SerialName("interaction")
    data class Interaction(
        @SerialName("playerId")
        val playerId: String,
        @SerialName("interactionId")
        val interactionId: String,
        @SerialName("params")
        val params: JsonElement,
    ) : GameInput
}

@Serializable
@JsonClassDiscriminator("type")
sealed interface Effect {
    @Serializable
    @SerialName("transition")
    data class Transition(
        @SerialName("effectId")
        val effectId: String,
        @SerialName("to")
        val to: String,
    ) : Effect

    @Serializable
    @SerialName("rollDie")
    data class RollDie(
        @SerialName("effectId")
        val effectId: String,
        @SerialName("dieId")
        val dieId: String,
    ) : Effect

    @Serializable
    @SerialName("shuffleSharedZone")
    data class ShuffleSharedZone(
        @SerialName("effectId")
        val effectId: String,
        @SerialName("zoneId")
        val zoneId: String,
    ) : Effect
}

@Serializable
data class ReducerInputValidationResult(
    @SerialName("valid")
    val valid: Boolean,
    @SerialName("errorCode")
    val errorCode: String? = null,
    @SerialName("message")
    val message: String? = null,
)

@Serializable
data class InitializeRequest(
    @SerialName("table")
    val table: JsonElement,
    @SerialName("playerIds")
    val playerIds: List<String>,
    @SerialName("rngSeed")
    val rngSeed: JsonElement? = null,
    @SerialName("setup")
    val setup: JsonElement? = null,
)

@Serializable
data class InitializePhaseRequest(
    @SerialName("state")
    val state: JsonElement,
    @SerialName("to")
    val to: String,
)

@Serializable
data class ValidateInputRequest(
    @SerialName("state")
    val state: JsonElement,
    @SerialName("input")
    val input: GameInput,
)

@Serializable
data class ReduceRequest(
    @SerialName("state")
    val state: JsonElement,
    @SerialName("input")
    val input: GameInput,
)

@Serializable
data class DispatchRequest(
    @SerialName("state")
    val state: JsonElement,
    @SerialName("input")
    val input: GameInput,
)

@Serializable
@JsonClassDiscriminator("kind")
sealed interface ReduceResult {
    @Serializable
    @SerialName("reject")
    data class Reject(
        @SerialName("errorCode")
        val errorCode: String,
        @SerialName("message")
        val message: String? = null,
    ) : ReduceResult

    @Serializable
    @SerialName("accept")
    data class Accept(
        @SerialName("state")
        val state: JsonElement,
        @SerialName("effects")
        val effects: List<Effect>,
        @SerialName("continuations")
        val continuations: Map<String, ContinuationToken>,
    ) : ReduceResult
}

@Serializable
@JsonClassDiscriminator("kind")
sealed interface DispatchTrace {
    @Serializable
    @SerialName("acceptedClientInput")
    data class AcceptedClientInput(
        @SerialName("input")
        val input: GameInput,
    ) : DispatchTrace

    @Serializable
    @SerialName("appliedEffect")
    data class AppliedEffect(
        @SerialName("effect")
        val effect: Effect,
        @SerialName("continuation")
        val continuation: ContinuationToken? = null,
    ) : DispatchTrace

    @Serializable
    @SerialName("rngConsumption")
    data class RngConsumption(
        @SerialName("operation")
        val operation: String,
        @SerialName("traceEntry")
        val traceEntry: String,
    ) : DispatchTrace
}

@Serializable
@JsonClassDiscriminator("kind")
sealed interface DispatchResult {
    @Serializable
    @SerialName("reject")
    data class Reject(
        @SerialName("errorCode")
        val errorCode: String,
        @SerialName("message")
        val message: String? = null,
    ) : DispatchResult

    @Serializable
    @SerialName("accept")
    data class Accept(
        @SerialName("state")
        val state: JsonElement,
        @SerialName("trace")
        val trace: List<DispatchTrace>,
    ) : DispatchResult
}

@Serializable
data class SeatProjection(
    @SerialName("view")
    val view: JsonElement? = null,
    @SerialName("availableInteractions")
    val availableInteractions: JsonElement? = null,
    @SerialName("zones")
    val zones: JsonElement? = null,
)

@Serializable
data class SeatProjectionBundle(
    @SerialName("currentStage")
    val currentStage: JsonElement? = null,
    @SerialName("stageSeats")
    val stageSeats: List<String> = emptyList(),
    @SerialName("seats")
    val seats: Map<String, SeatProjection>,
)

@Serializable
data class ProjectSeatsDynamicRequest(
    @SerialName("state")
    val state: JsonElement,
    @SerialName("playerIds")
    val playerIds: List<String>,
    @SerialName("viewId")
    val viewId: String? = null,
)

@Serializable
data class BoardStaticProjection(
    @SerialName("view")
    val view: JsonElement,
    @SerialName("hash")
    val hash: String,
    @SerialName("manifestVersion")
    val manifestVersion: String,
)

/** Generated metadata for the callable reducer bundle boundary. */
enum class ReducerBundlePayloadMeasurement {
    NONE,
    JSON_BYTES,
}

data class ReducerBundleRequestOperation<I>(
    val methodName: String,
    val requestSerializer: SerializationStrategy<I>,
    val requestPayloadMeasurement: ReducerBundlePayloadMeasurement,
    val responsePayloadMeasurement: ReducerBundlePayloadMeasurement,
)

data class ReducerBundleNoInputOperation(
    val methodName: String,
    val requestPayloadMeasurement: ReducerBundlePayloadMeasurement,
    val responsePayloadMeasurement: ReducerBundlePayloadMeasurement,
)

object ReducerBundleOperations {
    const val VERSION_PROPERTY: String = "reducerContractVersion"
    const val INITIALIZE_METHOD: String = "initialize"
    const val INITIALIZE_PHASE_METHOD: String = "initializePhase"
    const val VALIDATE_INPUT_METHOD: String = "validateInput"
    const val REDUCE_METHOD: String = "reduce"
    const val DISPATCH_METHOD: String = "dispatch"
    const val PROJECT_STATIC_METHOD: String = "projectStatic"
    const val PROJECT_SEATS_DYNAMIC_METHOD: String = "projectSeatsDynamic"

    val REQUIRED_METHOD_NAMES: List<String> = listOf(
        INITIALIZE_METHOD,
        INITIALIZE_PHASE_METHOD,
        VALIDATE_INPUT_METHOD,
        REDUCE_METHOD,
        DISPATCH_METHOD,
        PROJECT_STATIC_METHOD,
        PROJECT_SEATS_DYNAMIC_METHOD,
    )

    val INITIALIZE: ReducerBundleRequestOperation<InitializeRequest> = ReducerBundleRequestOperation(
        methodName = INITIALIZE_METHOD,
        requestSerializer = InitializeRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val INITIALIZE_PHASE: ReducerBundleRequestOperation<InitializePhaseRequest> = ReducerBundleRequestOperation(
        methodName = INITIALIZE_PHASE_METHOD,
        requestSerializer = InitializePhaseRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val VALIDATE_INPUT: ReducerBundleRequestOperation<ValidateInputRequest> = ReducerBundleRequestOperation(
        methodName = VALIDATE_INPUT_METHOD,
        requestSerializer = ValidateInputRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val REDUCE: ReducerBundleRequestOperation<ReduceRequest> = ReducerBundleRequestOperation(
        methodName = REDUCE_METHOD,
        requestSerializer = ReduceRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val DISPATCH: ReducerBundleRequestOperation<DispatchRequest> = ReducerBundleRequestOperation(
        methodName = DISPATCH_METHOD,
        requestSerializer = DispatchRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val PROJECT_STATIC: ReducerBundleNoInputOperation = ReducerBundleNoInputOperation(
        methodName = PROJECT_STATIC_METHOD,
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.NONE,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val PROJECT_SEATS_DYNAMIC: ReducerBundleRequestOperation<ProjectSeatsDynamicRequest> = ReducerBundleRequestOperation(
        methodName = PROJECT_SEATS_DYNAMIC_METHOD,
        requestSerializer = ProjectSeatsDynamicRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )
}

/**
 * Wire-protocol version implemented by this generated code. Must match
 * the JS bundle's REDUCER_CONTRACT_VERSION at load time.
 */
public const val REDUCER_CONTRACT_VERSION: String = "6.0.0"
