import { existsSync, readdirSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { GameTopologyManifest } from "@dreamboard/sdk-types";

const require = createRequire(import.meta.url);
const MODULE_DIR = path.dirname(fileURLToPath(import.meta.url));
const UI_SDK_COMPONENT_SEED_PREFIX = "ui/components/dreamboard/";
const UI_SDK_COMPONENT_IMPORT_REWRITES = new Map<string, string>([
  ["../manifest-contract.js", "@dreamboard/manifest-contract"],
  ["../../manifest-contract.js", "@dreamboard/manifest-contract"],
  ["../context/PluginStateContext.js", "@dreamboard/ui-sdk"],
  ["../context/RuntimeContext.js", "@dreamboard/ui-sdk"],
  ["../hooks/useHandLayout.js", "@dreamboard/ui-sdk"],
  ["../hooks/usePluginRuntime.js", "@dreamboard/ui-sdk"],
  ["../types/player-state.js", "@dreamboard/ui-sdk"],
  ["../../hooks/usePanZoom.js", "@dreamboard/ui-sdk"],
  ["../../hooks/useIsMobile.js", "@dreamboard/ui-sdk"],
  ["../../types/player-state.js", "@dreamboard/ui-sdk"],
  ["../../types/tiled-board.js", "@dreamboard/ui-sdk"],
]);

export const SETUP_PROFILES_SEED_MARKER =
  "Generated by dreamboard setup-profiles scaffold.";

function generateUiContractContent(): string {
  return `/**
 * Generated file.
 * Do not edit directly.
 */

import type game from "../../app/game";
import type {
  ActionNamesOfDefinitionPhase,
  ActionNamesOfDefinition,
  ActionParamsOfDefinitionPhase,
  ActionParamsOfDefinition,
  PhaseNamesOfDefinition,
  PromptIdsOfDefinition,
  PromptInstanceId as PromptInstanceIdBrand,
  PromptResponseOfDefinition,
  ViewNamesOfDefinition,
  ViewOfDefinition,
} from "@dreamboard/app-sdk/reducer/model";

type GameDefinition = typeof game;

type RequiredKeys<T extends object> = {
  [Key in keyof T]-?: {} extends Pick<T, Key> ? never : Key;
}[keyof T];

type InvocationArgs<Params> = [Params] extends [undefined]
  ? []
  : Params extends object
    ? keyof Params extends never
      ? []
      : RequiredKeys<Params> extends never
        ? [] | [Params]
        : [Params]
    : [Params];

type CommandShape<Name extends string, Params> = [Params] extends [undefined]
  ? { type: Name }
  : Params extends object
    ? keyof Params extends never
      ? { type: Name }
      : RequiredKeys<Params> extends never
        ? { type: Name; params?: Params }
        : { type: Name; params: Params }
    : { type: Name; params: Params };

type CommandCreator<Name extends string, Params> = (
  ...args: InvocationArgs<Params>
) => CommandShape<Name, Params>;

function createCommand<Name extends string>(type: Name) {
  return ((...args: [] | [unknown]) => {
    const params = args[0];
    return typeof params === "undefined" ? { type } : { type, params };
  }) as CommandCreator<Name, unknown>;
}

function createCommandNamespace() {
  return new Proxy(Object.create(null), {
    get(_target, prop) {
      if (typeof prop !== "string") {
        return undefined;
      }
      return createCommand(prop);
    },
    has(_target, prop) {
      return typeof prop === "string";
    },
  });
}

export type ViewName = ViewNamesOfDefinition<GameDefinition>;
export type InferView<Name extends ViewName> = ViewOfDefinition<
  GameDefinition,
  Name
>;
export type GameView = Extract<"player", ViewName> extends never
  ? never
  : InferView<Extract<"player", ViewName>>;

export type ActionName = ActionNamesOfDefinition<GameDefinition>;
export type ActionParams<Name extends ActionName> = ActionParamsOfDefinition<
  GameDefinition,
  Name
>;
export type ActionArgs<Name extends ActionName> = InvocationArgs<
  ActionParams<Name>
>;

export type PhaseName = PhaseNamesOfDefinition<GameDefinition>;
export type ActionNameForPhase<
  Phase extends PhaseName,
> = ActionNamesOfDefinitionPhase<GameDefinition, Phase>;
export type ActionParamsForPhase<
  Phase extends PhaseName,
  Name extends ActionNameForPhase<Phase>,
> = ActionParamsOfDefinitionPhase<GameDefinition, Phase, Name>;
export type ActionArgsForPhase<
  Phase extends PhaseName,
  Name extends ActionNameForPhase<Phase>,
> = InvocationArgs<ActionParamsForPhase<Phase, Name>>;
export type ActionCommandForPhase<Phase extends PhaseName> = {
  [Name in ActionNameForPhase<Phase>]: CommandShape<
    Name,
    ActionParamsForPhase<Phase, Name>
  >;
}[ActionNameForPhase<Phase>];
export type PhaseCommands<Phase extends PhaseName> = {
  [Name in ActionNameForPhase<Phase>]: (
    ...args: ActionArgsForPhase<Phase, Name>
  ) => Extract<ActionCommandForPhase<Phase>, { type: Name }>;
};
export const phaseCommands = new Proxy(Object.create(null), {
  get(_target, prop) {
    if (typeof prop !== "string") {
      return undefined;
    }
    return createCommandNamespace();
  },
}) as {
  [Phase in PhaseName]: PhaseCommands<Phase>;
};

export type PromptId = PromptIdsOfDefinition<GameDefinition>;
export type PromptResponse<Name extends PromptId> = PromptResponseOfDefinition<
  GameDefinition,
  Name
>;
export type PromptInstanceId<Name extends PromptId> = PromptInstanceIdBrand<
  Name
>;
`;
}

function generateReducerSupportSeed(): string {
  return `import {
  createReducerOps,
  createStateQueries,
  pipe,
} from "@dreamboard/app-sdk/reducer";
import type { GameState } from "./game-contract";

/**
 * App-owned reducer helpers belong here.
 * Keep schema and contract declarations in app/game-contract.ts.
 * Keep initial state callbacks and game wiring in app/game.ts.
 * Keep memoized aggregates (winner checks, VP totals, longest-road,
 * largest-army) in app/derived.ts via \`defineDerived\`.
 *
 * Recommended authoring pattern inside a phase reducer:
 *
 *   const next = pipe(
 *     state,
 *     ops.setActivePlayers([q.players.order()[0]]),
 *   );
 *   return accept(next);
 */

export const ops = createReducerOps<GameState>();

export { pipe };

export function stateQueries(state: GameState) {
  return createStateQueries(state);
}
`;
}

function generateReducerDerivedSeed(): string {
  return `// Memoized, pure projections of reducer state. Read them from reducer
// callbacks and view projections via the injected \`derived\` helper:
//
//   reduce({ state, derived, accept }) {
//     const winner = derived(winnerOf);
//     return accept({ ...state, publicState: { ...state.publicState, winnerPlayerId: winner } });
//   }
//
// Do NOT mirror derived values back into \`publicState\`. Keep the raw
// inputs (component locations, zone contents, counters) in state and
// express aggregates here.
//
// Uncomment the example below once you have something to derive.

// import { defineDerived } from "@dreamboard/app-sdk/reducer";
// import type { GameContract } from "./game-contract";
//
// export const winnerOf = defineDerived<GameContract>()({
//   name: "winnerOf",
//   compute: ({ state }) => {
//     // Example: return the first player at or above the VP target.
//     return state.publicState.winnerPlayerId ?? null;
//   },
// });

export {};
`;
}

function generateReducerGameContractSeed(): string {
  return `import { z } from "zod";
import { ids, manifestContract } from "../shared/manifest-contract";
import { defineGameContract, type GameStateOf } from "@dreamboard/app-sdk/reducer";

const publicStateSchema = z.object({
  currentPlayerId: ids.playerId.nullable(),
  notesByPlayerId: z.partialRecord(ids.playerId, z.string()).default({}),
});
const privateStateSchema = z.object({});
const hiddenStateSchema = z.object({});

export const gameContract = defineGameContract({
  manifest: manifestContract,
  // Keep this list in sync with the keys of the \`phases\` record in ./phases.
  // Declaring phase names here narrows \`fx.transition(...)\`, \`phase.dispatch\`,
  // and the flow state's \`currentPhase\` to a literal union.
  phaseNames: ["setup"] as const,
  state: {
    public: publicStateSchema,
    private: privateStateSchema,
    hidden: hiddenStateSchema,
  },
});

export type GameContract = typeof gameContract;
export type GameState = GameStateOf<GameContract>;
`;
}

function generateReducerGameSeed(): string {
  return `import { defineGame } from "@dreamboard/app-sdk/reducer";
import { gameContract } from "./game-contract";
import { phases } from "./phases";
import setupProfiles from "./setup-profiles";

export default defineGame({
  contract: gameContract,
  initial: {
    public: ({ playerIds }) => ({
      currentPlayerId: playerIds[0] ?? null,
      notesByPlayerId: {},
    }),
    private: () => ({}),
    hidden: () => ({}),
  },
  initialPhase: "setup",
  setupProfiles,
  phases,
  views: {},
});
`;
}

function generateSetupProfilesSeed(manifest: GameTopologyManifest): string {
  const setupProfiles = manifest.setupProfiles ?? [];
  const setupProfileEntries =
    setupProfiles.length === 0
      ? ""
      : `{\n${setupProfiles
          .map((profile) => `  ${JSON.stringify(profile.id)}: {},`)
          .join("\n")}\n}`;

  return `// ${SETUP_PROFILES_SEED_MARKER}
import { setupProfiles } from "../shared/manifest-contract";

export default setupProfiles(${setupProfileEntries || "{}"});
`;
}

export function isFrameworkOwnedSetupProfilesSeed(
  content: string | null | undefined,
): boolean {
  if (content == null) {
    return false;
  }
  const trimmed = content.trim();
  if (trimmed.length === 0) {
    return true;
  }
  if (trimmed.includes(SETUP_PROFILES_SEED_MARKER)) {
    return true;
  }
  return false;
}

function generateSetupPhaseSeed(): string {
  return `import { z } from "zod";
import type { GameContract } from "../game-contract";
import { definePhase } from "@dreamboard/app-sdk/reducer";

export const setup = definePhase<GameContract>()({
  kind: "auto",
  state: z.object({}),
  initialState: () => ({}),
  enter({ state, accept }) {
    return accept(state);
  },
});
`;
}

function generatePhaseIndexSeed(): string {
  return `import { setup } from "./setup";
import type { GameContract } from "../game-contract";
import type { PhaseMapOf } from "@dreamboard/app-sdk/reducer";

export const phases = {
  setup,
} satisfies PhaseMapOf<GameContract>;
`;
}

function generateReducerAppIndex(): string {
  return `import game from "./game";
import { createReducerBundle } from "@dreamboard/app-sdk/reducer/bundle";

export default createReducerBundle(game);
`;
}

function generateAppFrameworkTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        declaration: false,
        outDir: "./dist",
        baseUrl: ".",
        paths: {
          "@dreamboard/manifest-contract": ["../shared/manifest-contract.ts"],
          "@dreamboard/ui-contract": ["../shared/generated/ui-contract.ts"],
          "@shared/*": ["../shared/*"],
        },
      },
      include: [
        "./**/*.ts",
        "./**/*.d.ts",
        "../shared/**/*.ts",
        "../shared/**/*.d.ts",
      ],
      exclude: ["node_modules", "dist"],
    },
    null,
    2,
  )}\n`;
}

function generateUiFrameworkTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "ESNext",
        moduleResolution: "bundler",
        jsx: "react-jsx",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        baseUrl: ".",
        paths: {
          "@dreamboard/manifest-contract": ["../shared/manifest-contract.ts"],
          "@dreamboard/ui-contract": ["../shared/generated/ui-contract.ts"],
          "@shared/*": ["../shared/*"],
        },
      },
      include: ["./**/*.ts", "./**/*.tsx", "../shared/**/*.ts"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2,
  )}\n`;
}

function generateReducerUiAppContent(): string {
  return `import {
  useActions,
  useGameView,
  useMe,
  usePlayerInfo,
  usePluginSession,
} from "@dreamboard/ui-sdk";
import { GameSkeleton, ToastProvider } from "./components/dreamboard";

function AppLoader() {
  const { status } = usePluginSession();

  if (status === "loading") {
    return <GameSkeleton variant="default" message="Loading game..." />;
  }

  return <AppContent />;
}

function AppContent() {
  const phase = useActions();
  const view = useGameView();
  const me = useMe();
  const players = usePlayerInfo();
  const meLabel = players.get(me.playerId)?.name ?? me.name ?? me.playerId;

  return (
    <div
      style={{
        background:
          "linear-gradient(180deg, #faf4ea 0%, #f2e5cf 48%, #ead9be 100%)",
        color: "#24180f",
        minHeight: "100vh",
        padding: "24px 16px 40px",
      }}
    >
      <section
        style={{
          background: "rgba(255, 251, 244, 0.9)",
          border: "1px solid rgba(36, 24, 15, 0.12)",
          borderRadius: 18,
          display: "grid",
          gap: 18,
          margin: "0 auto",
          maxWidth: 1080,
          padding: 24,
        }}
      >
        <header style={{ display: "grid", gap: 8 }}>
          <h1 style={{ fontSize: 32, lineHeight: 1, margin: 0 }}>Game UI</h1>
          <p style={{ margin: 0, maxWidth: 720, opacity: 0.78 }}>
            This app now owns the Dreamboard UI components under{" "}
            <code>ui/components/dreamboard</code>. Edit those files freely and
            keep reducer data flow in <code>app/</code>.
          </p>
        </header>

        <section
          style={{
            background: "rgba(36, 24, 15, 0.92)",
            borderRadius: 18,
            color: "#fff7eb",
            display: "grid",
            gap: 12,
            padding: 18,
          }}
        >
          <strong>Reducer status</strong>
          <span>Current player: {meLabel}</span>
          <span>Current phase: {phase.phase}</span>
          <span>
            Available actions:{" "}
            {[...phase.availableActions].join(", ") || "No actions available"}
          </span>
        </section>

        <section style={{ display: "grid", gap: 8 }}>
          <strong style={{ fontSize: 18 }}>Player view</strong>
          <p style={{ margin: 0, opacity: 0.78 }}>
            Replace this inspector with game-specific UI built from the reducer
            view in <code>app/game.ts</code> and phase reducers under{" "}
            <code>app/phases</code>.
          </p>
          <pre
            style={{
              background: "rgba(36, 24, 15, 0.92)",
              borderRadius: 14,
              color: "#fff7eb",
              fontSize: 12,
              lineHeight: 1.5,
              margin: 0,
              overflowX: "auto",
              padding: 16,
            }}
          >
            {JSON.stringify(view, null, 2)}
          </pre>
        </section>
      </section>
    </div>
  );
}

export default function App() {
  return (
    <ToastProvider>
      <AppLoader />
    </ToastProvider>
  );
}
`;
}

function resolveUiSdkComponentsRoot(): string {
  try {
    const uiSdkPackageJsonPath = require.resolve(
      "@dreamboard/ui-sdk/package.json",
    );
    const installedComponentsRoot = path.join(
      path.dirname(uiSdkPackageJsonPath),
      "src",
      "components",
    );
    if (existsSync(installedComponentsRoot)) {
      return installedComponentsRoot;
    }
  } catch {
    // Fall through to the repo-local source checkout lookup below.
  }

  let currentDir = MODULE_DIR;
  while (true) {
    const repoLocalComponentsRoot = path.join(
      currentDir,
      "packages",
      "ui-sdk",
      "src",
      "components",
    );
    if (
      existsSync(path.join(currentDir, "pnpm-workspace.yaml")) &&
      existsSync(repoLocalComponentsRoot)
    ) {
      return repoLocalComponentsRoot;
    }

    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      break;
    }
    currentDir = parentDir;
  }

  throw new Error(
    "Could not resolve Dreamboard UI SDK component seeds from an installed package or source checkout.",
  );
}

function walkUiSdkComponentFiles(rootDir: string): string[] {
  const componentFiles: string[] = [];
  const stack = [rootDir];

  while (stack.length > 0) {
    const currentDir = stack.pop();
    if (!currentDir) continue;

    for (const entry of readdirSync(currentDir, { withFileTypes: true })) {
      if (entry.name === "__fixtures__") {
        continue;
      }

      const entryPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        stack.push(entryPath);
        continue;
      }

      if (!entry.isFile()) {
        continue;
      }

      componentFiles.push(
        path.relative(rootDir, entryPath).replaceAll("\\", "/"),
      );
    }
  }

  componentFiles.sort((left, right) => left.localeCompare(right));
  return componentFiles;
}

function rewriteUiSdkComponentImports(content: string): string {
  let rewritten = content;

  for (const [from, to] of UI_SDK_COMPONENT_IMPORT_REWRITES) {
    rewritten = rewritten.replaceAll(`"${from}"`, `"${to}"`);
    rewritten = rewritten.replaceAll(`'${from}'`, `'${to}'`);
  }

  return rewritten;
}

function generateUiSdkComponentSeeds(): Record<string, string> {
  const sourceRoot = resolveUiSdkComponentsRoot();

  return Object.fromEntries(
    walkUiSdkComponentFiles(sourceRoot).map((relativePath) => {
      const sourcePath = path.join(sourceRoot, relativePath);
      const content = readFileSync(sourcePath, "utf8");

      return [
        `${UI_SDK_COMPONENT_SEED_PREFIX}${relativePath}`,
        rewriteUiSdkComponentImports(content),
      ];
    }),
  );
}

export function generateSeedFiles(
  manifest: GameTopologyManifest,
): Record<string, string> {
  return {
    "ui/App.tsx": generateReducerUiAppContent(),
    ...generateUiSdkComponentSeeds(),
    "app/game-contract.ts": generateReducerGameContractSeed(),
    "app/game.ts": generateReducerGameSeed(),
    "app/setup-profiles.ts": generateSetupProfilesSeed(manifest),
    "app/reducer-support.ts": generateReducerSupportSeed(),
    "app/derived.ts": generateReducerDerivedSeed(),
    "app/phases/setup.ts": generateSetupPhaseSeed(),
    "app/phases/index.ts": generatePhaseIndexSeed(),
  };
}

export function generateAuthoritativeIndexFile(
  _manifest: GameTopologyManifest,
): string {
  return generateReducerAppIndex();
}

export function generateFrameworkFiles(
  manifest: GameTopologyManifest,
): Record<string, string> {
  return {
    "app/tsconfig.framework.json": generateAppFrameworkTsConfig(),
    "ui/tsconfig.framework.json": generateUiFrameworkTsConfig(),
    "shared/generated/ui-contract.ts": generateUiContractContent(),
    "app/index.ts": generateAuthoritativeIndexFile(manifest),
  };
}
