import type { GameTopologyManifest } from "@dreamboard/sdk-types";

export const SETUP_PROFILES_SEED_MARKER =
  "Generated by dreamboard setup-profiles scaffold.";

function generateUiContractContent(): string {
  return `/**
 * Generated file.
 * Do not edit directly.
 */

import game from "../../app/game";
import {
  createClientParamSchemasByPhase,
} from "@dreamboard/app-sdk/reducer";
import type {
  ClientParamsOfInteractionOfDefinition,
  DefaultedClientParamKeysOfInteractionOfDefinition,
  InteractionIdOfDefinition,
  InteractionIdOfDefinitionPhase,
  PhaseNamesOfDefinition,
  PlayableInteractionsOfZoneOfDefinition,
  StageNamesOfDefinitionPhase,
  SurfaceOfInteractionOfDefinition,
  SurfaceTag,
  ViewNamesOfDefinition,
  ViewOfDefinition,
} from "@dreamboard/app-sdk/reducer";
import {
  GameShell as GameShellGeneric,
  useActivePlayers as useActivePlayersGeneric,
  useBoardInteractions as useBoardInteractionsGeneric,
  useInteractionByKey as useInteractionByKeyGeneric,
  usePlayerTurnOrder as usePlayerTurnOrderGeneric,
  type BoardInteractionsContext,
  type BoardInteractionsOptions,
  type ClientParamSchemaMap,
  type GameShellProps,
  type HandSurfaceConfig,
  type HandZoneRenderer,
  type InteractionDescriptor,
  type InteractionHandle,
} from "@dreamboard/ui-sdk";
import { createElement, type ReactElement } from "react";
import {
  literals,
  type PlayerId,
  type ZoneId as ManifestZoneId,
} from "../manifest-contract";

type GameDefinition = typeof game;

export type ViewName = ViewNamesOfDefinition<GameDefinition>;
export type InferView<Name extends ViewName> = ViewOfDefinition<
  GameDefinition,
  Name
>;
export type GameView = Extract<"player", ViewName> extends never
  ? never
  : InferView<Extract<"player", ViewName>>;

export type PhaseName = PhaseNamesOfDefinition<GameDefinition>;

// -------------------------------------------------------------------------
// Interaction / Stage / Zone types (authored via defineInteraction/Stage/zones)
// -------------------------------------------------------------------------

/** Union of all interaction ids across phases. */
export type InteractionId = InteractionIdOfDefinition<GameDefinition>;

/** Interactions declared in a specific phase. */
export type InteractionIdForPhase<Phase extends PhaseName> =
  InteractionIdOfDefinitionPhase<GameDefinition, Phase>;

/**
 * Client-facing params type for an interaction, inferred from its input
 * collectors. Engine-sampled collectors (e.g. \`rngInput.*\`) are omitted
 * — the trusted reducer bundle fills those fields during submit, so the
 * client never supplies them.
 */
export type InteractionParams<
  Phase extends PhaseName,
  Id extends InteractionIdForPhase<Phase>,
> = ClientParamsOfInteractionOfDefinition<GameDefinition, Phase, Id>;

/** Client-facing params with authored input defaults. */
export type InteractionDefaultedKeys<
  Phase extends PhaseName,
  Id extends InteractionIdForPhase<Phase>,
> = DefaultedClientParamKeysOfInteractionOfDefinition<GameDefinition, Phase, Id>;

/** Surface tag for an interaction. */
export type InteractionSurface<
  Phase extends PhaseName,
  Id extends InteractionIdForPhase<Phase>,
> = SurfaceOfInteractionOfDefinition<GameDefinition, Phase, Id>;

/** Phase-qualified interaction key for a specific phase. */
export type InteractionKeyForPhase<Phase extends PhaseName> =
  \`\${Phase}.\${InteractionIdForPhase<Phase>}\`;

/** Phase-qualified union of every client/UI interaction key. */
export type InteractionKey = {
  [P in PhaseName]: InteractionKeyForPhase<P>;
}[PhaseName];

type PhaseOfInteractionKey<Key extends InteractionKey> =
  Key extends \`\${infer P}.\${string}\` ? Extract<P, PhaseName> : never;

type IdOfInteractionKey<Key extends InteractionKey> =
  Key extends \`\${infer P}.\${infer I}\`
    ? P extends PhaseName
      ? Extract<I, InteractionIdForPhase<P>>
      : never
    : never;

/**
 * Union of interaction keys that target the given surface, across all phases.
 * Feed this into surface components like \`<PanelSurface<PanelInteractions> />\`
 * for exhaustive render-map typing.
 */
export type InteractionsForSurface<S extends SurfaceTag> = {
  [P in PhaseName]: {
    [I in InteractionIdForPhase<P>]: [InteractionSurface<P, I>] extends [S]
      ? \`\${P}.\${I}\`
      : never;
  }[InteractionIdForPhase<P>];
}[PhaseName];

export type PanelInteractions = InteractionsForSurface<"panel">;
export type BoardInteractions = InteractionsForSurface<
  "board-vertex" | "board-edge" | "board-tile" | "board-space"
>;
export type HandInteractions = InteractionsForSurface<"hand">;
export type InboxInteractions = InteractionsForSurface<"inbox">;
export type BlockerInteractions = InteractionsForSurface<"blocker">;
export type ChromeInteractions = InteractionsForSurface<"chrome">;

/** Stage names declared in a phase. */
export type StageName<Phase extends PhaseName> = StageNamesOfDefinitionPhase<
  GameDefinition,
  Phase
>;

/** Union of zone ids authored in the workspace manifest. */
export type ZoneId = ManifestZoneId;

type CamelCase<S extends string> = S extends \`\${infer Head}-\${infer Tail}\`
  ? \`\${Head}\${Capitalize<CamelCase<Tail>>}\`
  : S;

/** JS-friendly keys for authored zones, e.g. "dev-hand" -> "devHand". */
export type WorkspaceZoneKey = CamelCase<ZoneId>;

/** Interactions that can be played against a card in the given zone. */
export type PlayableInteractionsOfZone<
  Phase extends PhaseName,
  Z extends ZoneId & string,
> = PlayableInteractionsOfZoneOfDefinition<GameDefinition, Phase, Z>;

/** Interaction descriptor specialised to a concrete phase-qualified key. */
export type InteractionDescriptorFor<Key extends InteractionKey> =
  InteractionDescriptor<Key>;

/**
 * Params shape for a phase-qualified interaction key. Drives strong typing
 * for \`useInteractionByKey\`'s draft,
 * \`submit\`, and \`setInput\`.
 */
export type InteractionParamsOf<Key extends InteractionKey> =
  InteractionParams<PhaseOfInteractionKey<Key>, IdOfInteractionKey<Key>>;

export type InteractionDefaultedKeysOf<Key extends InteractionKey> =
  InteractionDefaultedKeys<PhaseOfInteractionKey<Key>, IdOfInteractionKey<Key>>;

type InteractionParamsShape<Key extends InteractionKey> =
  InteractionParamsOf<Key> extends Record<string, unknown>
    ? InteractionParamsOf<Key>
    : Record<string, unknown>;

type InteractionHandleDefaultedKeys<Key extends InteractionKey> = Extract<
  InteractionDefaultedKeysOf<Key>,
  keyof InteractionParamsShape<Key> & string
>;

/** Params map keyed by phase-qualified interaction key, consumed by typed surface renderers. */
export type InteractionParamsByKey = {
  [K in InteractionKey]: {
    params: InteractionParamsShape<K>;
    defaulted: InteractionHandleDefaultedKeys<K>;
  };
};

export const clientParamSchemasByPhase = createClientParamSchemasByPhase(
  game,
) as ClientParamSchemaMap;

/**
 * Workspace-typed wrapper over \`@dreamboard/ui-sdk\`'s generic
 * \`useInteractionByKey\`. The \`key\` argument is constrained to the
 * generated {@link InteractionKey} union (typos are compile errors), and
 * the returned {@link InteractionHandle} is parameterised on
 * {@link InteractionParamsOf} so \`handle.draft\`, \`handle.submit\`, and
 * \`handle.setInput\` are statically typed against the interaction's
 * declared inputs.
 *
 * \`\`\`ts
 * const handle = useInteractionByKey("play.placeThingCard");
 * if (!handle) return null;
 * handle.setInput("cardId", card.id); // inferred as ThingsDeckCardId
 * await handle.submit(); // params typed from the reducer contract
 * \`\`\`
 */
export function useInteractionByKey<Key extends InteractionKey>(
  key: Key | null | undefined,
): InteractionHandle<
  InteractionParamsShape<Key>,
  InteractionHandleDefaultedKeys<Key>
> | null {
  return useInteractionByKeyGeneric<
    Key,
    InteractionParamsShape<Key>,
    InteractionHandleDefaultedKeys<Key>
  >(key);
}

/**
 * Workspace-typed wrapper over \`@dreamboard/ui-sdk\`'s
 * \`useBoardInteractions\`. Constrains the \`priority\` list to this
 * workspace's {@link BoardInteractions} union so misspelled keys are
 * compile errors, and returns a {@link BoardInteractionsContext}
 * narrowed to the same union for exhaustive downstream logic.
 *
 * \`\`\`tsx
 * const board = useBoardInteractions({
 *   priority: ["play.placeSetupSettlement", "play.buildSettlement"],
 * });
 * board.select.vertex(vertex.id);
 * \`\`\`
 *
 * Reach for this whenever a screen keeps more than one board-surface
 * interaction live simultaneously and dispatch is target-driven
 * instead of armed-then-clicked.
 */
export function useBoardInteractions(
  options?: BoardInteractionsOptions<BoardInteractions>,
): BoardInteractionsContext<BoardInteractions> {
  return useBoardInteractionsGeneric<BoardInteractions>(options);
}

/** Workspace-typed active-player hook. */
export function useActivePlayers(): readonly PlayerId[] {
  return useActivePlayersGeneric() as readonly PlayerId[];
}

/** Workspace-typed player turn order hook. */
export function usePlayerTurnOrder(): readonly PlayerId[] {
  return usePlayerTurnOrderGeneric() as readonly PlayerId[];
}

// -------------------------------------------------------------------------
// Typed GameShell — specialised to this workspace's per-surface unions so
// authors write \`<GameShell surfaces={{ ... }} />\` with no generic args.
// -------------------------------------------------------------------------

/**
 * Full per-surface interaction map for this workspace. Authored interaction
 * keys are grouped by the surface they declared via \`defineInteraction\`.
 */
export type WorkspaceSurfaceMap = {
  panel: PanelInteractions;
  hand: HandInteractions;
  inbox: InboxInteractions;
  chrome: ChromeInteractions;
  blocker: BlockerInteractions;
  board: BoardInteractions;
};

type RawGameShellProps = GameShellProps<
  WorkspaceSurfaceMap,
  InteractionParamsByKey,
  ZoneId
>;

type WorkspaceHandSurfaceConfig = HandSurfaceConfig<
  HandInteractions,
  InteractionParamsByKey,
  WorkspaceZoneKey
>;

type WorkspaceGameShellSurfaces = Omit<
  NonNullable<RawGameShellProps["surfaces"]>,
  "hand"
> & {
  hand?: WorkspaceHandSurfaceConfig;
};

/** Props for the workspace-typed {@link GameShell}. */
export type WorkspaceGameShellProps = Omit<
  RawGameShellProps,
  "surfaces"
> & {
  surfaces?: WorkspaceGameShellSurfaces;
};

/**
 * Opinionated shell pre-specialised to this workspace's surface unions.
 * Authors import this directly and get compile-time enforcement that
 * \`surfaces.<slot>\` entries match the authored surface's interaction keys:
 *
 * \`\`\`tsx
 * import { GameShell } from "@dreamboard/ui-contract";
 *
 * <GameShell
 *   surfaces={{
 *     hand: {
 *       zones: {
 *         mainHand: (cards, contexts) => ...,
 *       },
 *       interactions: {
 *         "play.inspectCard": (descriptor, handle) => ...,
 *       },
 *     },
 *     inbox: { "judge.judgePlacement": () => null },
 *   }}
 * />
 * \`\`\`
 *
 * For a zero-default shell (custom layout, direct surface composition),
 * import \`GameShell\` from \`@dreamboard/ui-sdk\` instead.
 */
const TypedGameShell = GameShellGeneric as unknown as (
  props: RawGameShellProps,
) => ReactElement;

function zoneKeyOf(zoneId: string): WorkspaceZoneKey {
  return zoneId.replace(/-([a-z0-9])/g, (_match, char: string) =>
    char.toUpperCase(),
  ) as WorkspaceZoneKey;
}

function buildZoneIdByKey(): Record<WorkspaceZoneKey, ZoneId> {
  const entries = literals.zoneIds.map((zoneId) => [
    zoneKeyOf(zoneId),
    zoneId,
  ] as const);
  return Object.fromEntries(entries) as Record<WorkspaceZoneKey, ZoneId>;
}

const zoneIdByKey = buildZoneIdByKey();

function translateHandZones(
  zones: WorkspaceHandSurfaceConfig["zones"],
):
  | Partial<Record<ZoneId, HandZoneRenderer<HandInteractions, InteractionParamsByKey>>>
  | undefined {
  if (!zones) return undefined;

  const translated: Partial<
    Record<ZoneId, HandZoneRenderer<HandInteractions, InteractionParamsByKey>>
  > = {};
  for (const [zoneKey, renderHand] of Object.entries(zones) as Array<
    [
      WorkspaceZoneKey,
      HandZoneRenderer<HandInteractions, InteractionParamsByKey> | undefined,
    ]
  >) {
    if (!renderHand) continue;
    translated[zoneIdByKey[zoneKey]] = renderHand;
  }

  return Object.keys(translated).length > 0 ? translated : undefined;
}

function translateSurfaces(
  surfaces: WorkspaceGameShellProps["surfaces"],
): RawGameShellProps["surfaces"] {
  if (!surfaces?.hand) return surfaces as RawGameShellProps["surfaces"];

  return {
    ...surfaces,
    hand: {
      ...surfaces.hand,
      zones: translateHandZones(surfaces.hand.zones),
    },
  } as RawGameShellProps["surfaces"];
}

export function GameShell(props: WorkspaceGameShellProps): ReactElement {
  return createElement(TypedGameShell, {
    ...props,
    surfaces: translateSurfaces(props.surfaces),
    clientParamSchemas:
      props.clientParamSchemas ?? clientParamSchemasByPhase,
  });
}
`;
}

function generateReducerSupportSeed(): string {
  return `import {
  createReducerOps,
  createStateQueries,
  pipe,
} from "@dreamboard/app-sdk/reducer";
import type { GameState } from "./game-contract";

/**
 * App-owned reducer helpers belong here.
 * Keep schema and contract declarations in app/game-contract.ts.
 * Keep initial state callbacks and game wiring in app/game.ts.
 * Keep memoized aggregates (winner checks, VP totals, longest-road,
 * largest-army) in app/derived.ts via \`defineDerived\`.
 *
 * Recommended authoring pattern inside a phase reducer:
 *
 *   const next = pipe(
 *     state,
 *     ops.setActivePlayers([q.players.order()[0]]),
 *   );
 *   return accept(next);
 */

export const ops = createReducerOps<GameState>();

export { pipe };

export function stateQueries(state: GameState) {
  return createStateQueries(state);
}
`;
}

function generateReducerDerivedSeed(): string {
  return `// Memoized, pure projections of reducer state. Read them from reducer
// callbacks and view projections via the injected \`derived\` helper:
//
//   reduce({ state, derived, accept }) {
//     const winner = derived(winnerOf);
//     return accept({ ...state, publicState: { ...state.publicState, winnerPlayerId: winner } });
//   }
//
// Do NOT mirror derived values back into \`publicState\`. Keep the raw
// inputs (component locations, zone contents, counters) in state and
// express aggregates here.
//
// Uncomment the example below once you have something to derive.

// import { defineDerived } from "@dreamboard/app-sdk/reducer";
// import type { GameContract } from "./game-contract";
//
// export const winnerOf = defineDerived<GameContract>()({
//   name: "winnerOf",
//   compute: ({ state }) => {
//     // Example: return the first player at or above the VP target.
//     return state.publicState.winnerPlayerId ?? null;
//   },
// });

export {};
`;
}

function generateReducerGameContractSeed(): string {
  return `import { z } from "zod";
import { ids, manifestContract } from "../shared/manifest-contract";
import { defineGameContract, type GameStateOf } from "@dreamboard/app-sdk/reducer";

const publicStateSchema = z.object({
  currentPlayerId: ids.playerId.nullable(),
  notesByPlayerId: z.partialRecord(ids.playerId, z.string()).default({}),
});
const privateStateSchema = z.object({});
const hiddenStateSchema = z.object({});

export const gameContract = defineGameContract({
  manifest: manifestContract,
  // Keep this list in sync with the keys of the \`phases\` record in ./phases.
  // Declaring phase names here narrows \`fx.transition(...)\`, \`phase.dispatch\`,
  // and the flow state's \`currentPhase\` to a literal union.
  phaseNames: ["setup"] as const,
  state: {
    public: publicStateSchema,
    private: privateStateSchema,
    hidden: hiddenStateSchema,
  },
});

export type GameContract = typeof gameContract;
export type GameState = GameStateOf<GameContract>;
`;
}

function generateReducerGameSeed(): string {
  return `import { defineGame } from "@dreamboard/app-sdk/reducer";
import { gameContract } from "./game-contract";
import { phases } from "./phases";
import setupProfiles from "./setup-profiles";

export default defineGame({
  contract: gameContract,
  initial: {
    public: ({ playerIds }) => ({
      currentPlayerId: playerIds[0] ?? null,
      notesByPlayerId: {},
    }),
    private: () => ({}),
    hidden: () => ({}),
  },
  initialPhase: "setup",
  setupProfiles,
  phases,
  views: {},
});
`;
}

function generateSetupProfilesSeed(manifest: GameTopologyManifest): string {
  const setupProfiles = manifest.setupProfiles ?? [];
  const setupProfileEntries =
    setupProfiles.length === 0
      ? ""
      : `{\n${setupProfiles
          .map((profile) => `  ${JSON.stringify(profile.id)}: {},`)
          .join("\n")}\n}`;

  return `// ${SETUP_PROFILES_SEED_MARKER}
import { setupProfiles } from "../shared/manifest-contract";

export default setupProfiles(${setupProfileEntries || "{}"});
`;
}

export function isFrameworkOwnedSetupProfilesSeed(
  content: string | null | undefined,
): boolean {
  if (content === null || content === undefined) {
    return false;
  }
  const trimmed = content.trim();
  if (trimmed.length === 0) {
    return true;
  }
  if (trimmed.includes(SETUP_PROFILES_SEED_MARKER)) {
    return true;
  }
  return false;
}

function generateSetupPhaseSeed(): string {
  return `import { z } from "zod";
import type { GameContract } from "../game-contract";
import { definePhase } from "@dreamboard/app-sdk/reducer";

export const setup = definePhase<GameContract>()({
  kind: "auto",
  state: z.object({}),
  initialState: () => ({}),
  enter({ state, accept }) {
    return accept(state);
  },
});
`;
}

function generatePhaseIndexSeed(): string {
  return `import { setup } from "./setup";
import type { GameContract } from "../game-contract";
import type { PhaseMapOf } from "@dreamboard/app-sdk/reducer";

export const phases = {
  setup,
} satisfies PhaseMapOf<GameContract>;
`;
}

function generateReducerAppIndex(): string {
  return `import game from "./game";
import { createReducerBundle } from "@dreamboard/app-sdk/reducer";

export default createReducerBundle(game);
`;
}

function generateAppFrameworkTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        declaration: false,
        outDir: "./dist",
        baseUrl: ".",
        paths: {
          "@dreamboard/manifest-contract": ["../shared/manifest-contract.ts"],
          "@dreamboard/ui-contract": ["../shared/generated/ui-contract.ts"],
          "@shared/*": ["../shared/*"],
        },
      },
      include: [
        "./**/*.ts",
        "./**/*.d.ts",
        "../shared/**/*.ts",
        "../shared/**/*.d.ts",
      ],
      exclude: ["node_modules", "dist"],
    },
    null,
    2,
  )}\n`;
}

function generateUiFrameworkTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "ESNext",
        moduleResolution: "bundler",
        jsx: "react-jsx",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        baseUrl: ".",
        paths: {
          "@dreamboard/manifest-contract": ["../shared/manifest-contract.ts"],
          "@dreamboard/ui-contract": ["../shared/generated/ui-contract.ts"],
          "@shared/*": ["../shared/*"],
        },
      },
      include: ["./**/*.ts", "./**/*.tsx", "../shared/**/*.ts"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2,
  )}\n`;
}

function generateReducerUiAppContent(): string {
  return `import { GameShell } from "@dreamboard/ui-contract";

export default function App() {
  return <GameShell />;
}
`;
}

export function generateSeedFiles(
  manifest: GameTopologyManifest,
): Record<string, string> {
  return {
    "ui/App.tsx": generateReducerUiAppContent(),
    "app/game-contract.ts": generateReducerGameContractSeed(),
    "app/game.ts": generateReducerGameSeed(),
    "app/setup-profiles.ts": generateSetupProfilesSeed(manifest),
    "app/reducer-support.ts": generateReducerSupportSeed(),
    "app/derived.ts": generateReducerDerivedSeed(),
    "app/phases/setup.ts": generateSetupPhaseSeed(),
    "app/phases/index.ts": generatePhaseIndexSeed(),
  };
}

export function generateAuthoritativeIndexFile(
  _manifest: GameTopologyManifest,
): string {
  return generateReducerAppIndex();
}

export function generateFrameworkFiles(
  manifest: GameTopologyManifest,
): Record<string, string> {
  return {
    "app/tsconfig.framework.json": generateAppFrameworkTsConfig(),
    "ui/tsconfig.framework.json": generateUiFrameworkTsConfig(),
    "shared/generated/ui-contract.ts": generateUiContractContent(),
    "app/index.ts": generateAuthoritativeIndexFile(manifest),
  };
}
