import path from "node:path";
import { readdir, unlink } from "node:fs/promises";
import { isDeepStrictEqual } from "node:util";
import { defineCommand } from "citty";
import consola from "consola";
import { z } from "zod";
import {
  createSession,
  startGame,
  submitAction,
  subscribeToSessionEvents,
  type GameMessage,
  type YourTurnMessage,
} from "@dreamboard/api-client";
import { CONFIG_FLAG_ARGS } from "../command-args.js";
import { resolveProjectContext } from "../config/resolve.js";
import { parseConfigFlags } from "../flags.js";
import { resolveCompiledResultForRun } from "../services/workflows/resolve-run-result.js";
import { shouldUseRemoteTestRuntime } from "../services/testing/runtime-mode.js";
import {
  ensureDir,
  exists,
  readTextFileIfExists,
  writeJsonFile,
  writeTextFile,
} from "../utils/fs.js";
import { formatApiError } from "../utils/errors.js";
import { TESTING_TYPES_CONTENT } from "../templates/testing-types-content.js";
import { migrateLegacyScenarioImports } from "../services/project/static-scaffold.js";
import type { ApiScenarioStep, ProjectConfig } from "../types.js";
import { importTypeScriptModule } from "../utils/ts-module-loader.js";

function tryJsonParse(value: unknown): unknown {
  return typeof value === "string" ? JSON.parse(value) : value;
}

const DEFAULT_TIMEOUT_MS = 10_000;
const TEST_SCENARIO_SUFFIX = ".scenario.ts";
const TESTING_TYPES_STUB =
  "export function defineScenario(scenario) { return scenario; }\n";
const GENERATED_TESTING_TYPES_PREFIX = "// Generated by dreamboard";

type ScenarioDefinition = {
  meta: {
    id: string;
    description: string;
  };
  given: {
    base: string;
  };
  when: {
    steps: ApiScenarioStep[];
  };
  then: {
    assert: (ctx: {
      gameState: Record<string, unknown>;
      events: EventInspector;
      expect: ExpectApi;
    }) => void | Promise<void>;
  };
};

type LoadedScenario = {
  filePath: string;
  scenario: ScenarioDefinition;
};

type BaseScenarioDefinition = {
  seed: number;
  players: number;
  steps: ApiScenarioStep[];
};

type BaseStateArtifact = {
  key: string;
  base: string;
  setupSteps: ApiScenarioStep[];
  snapshot: Record<string, unknown>;
  fingerprint: {
    base: string;
    seed: number;
    players: number;
    baseSetupHash: string;
    compiledResultId: string;
    manifestHash?: string;
    gameId: string;
  };
};

type BaseStateFile = Record<string, BaseStateArtifact>;

type BaseScenarioDefinitions = Record<string, BaseScenarioDefinition>;

type EventRecord = {
  type: GameMessage["type"];
  message: GameMessage;
};

type TestCommandRuntime = {
  gameId: string;
  compiledResultId: string;
  manifestHash?: string;
  cleanup: () => Promise<void>;
};

type ExpectMatchers = {
  toBe: (expected: unknown) => void;
  toEqual: (expected: unknown) => void;
  toBeDefined: () => void;
  toBeUndefined: () => void;
  toContain: (expected: unknown) => void;
  toBeGreaterThanOrEqual: (expected: number) => void;
};

type ExpectApi = (actual: unknown) => ExpectMatchers;

const apiScenarioStepSchema = z
  .object({
    playerId: z.string().min(1),
    actionType: z.string().min(1),
    parameters: z.record(z.string(), z.unknown()).optional(),
    turns: z.number().int().positive().optional(),
  })
  .strict();

const scenarioSchema = z
  .object({
    meta: z
      .object({
        id: z.string().min(1),
        description: z.string().min(1),
      })
      .strict(),
    given: z
      .object({
        base: z.string().min(1),
      })
      .strict(),
    when: z
      .object({
        steps: z.array(apiScenarioStepSchema),
      })
      .strict(),
    then: z
      .object({
        assert: z.custom<(ctx: unknown) => void | Promise<void>>(
          (value) => typeof value === "function",
        ),
      })
      .strict(),
  })
  .strict();

function formatValidationIssues(error: z.ZodError): string {
  return error.issues
    .map((issue) => `${issue.path.join(".") || "scenario"}: ${issue.message}`)
    .join("; ");
}

export function parseScenarioDefinition(value: unknown): ScenarioDefinition {
  const parsed = scenarioSchema.safeParse(value);
  if (!parsed.success) {
    throw new Error(formatValidationIssues(parsed.error));
  }
  return parsed.data;
}

const generateCommand = defineCommand({
  meta: {
    name: "generate",
    description: "Generate deterministic base snapshots for TS scenarios",
  },
  args: {
    scenario: {
      type: "string",
      description: "Optional scenario file path under test/scenarios",
    },
    ...CONFIG_FLAG_ARGS,
  },
  async run({ args }) {
    const parsedFlags = parseConfigFlags(args);
    const useRemoteRuntime = shouldUseRemoteTestRuntime(parsedFlags.env);
    const { projectRoot, projectConfig } = await resolveProjectContext(
      parsedFlags,
      { requireAuth: useRemoteRuntime },
    );
    await ensureScenarioImportShim(projectRoot);

    const scenarios = await loadScenarios(projectRoot, {
      scenarioPath: args.scenario,
    });
    const baseScenarios = await loadBaseScenarioDefinitions(projectRoot);

    if (scenarios.length === 0) {
      throw new Error("No scenarios found under test/scenarios/*.scenario.ts");
    }

    validateScenarioBases(scenarios, baseScenarios);

    const runtime = await resolveTestCommandRuntime({
      projectRoot,
      projectConfig,
      useRemoteRuntime,
    });

    try {
      const uniqueBases = new Set<string>();
      for (const scenario of scenarios) {
        uniqueBases.add(scenario.scenario.given.base);
      }

      const generatedBaseStates: BaseStateFile = {};
      for (const base of uniqueBases.values()) {
        const baseScenario = baseScenarios[base];
        if (!baseScenario) continue;
        const snapshot = await captureBaseSnapshot({
          gameId: runtime.gameId,
          compiledResultId: runtime.compiledResultId,
          baseSteps: baseScenario.steps,
          seed: baseScenario.seed,
          players: baseScenario.players,
        });
        const key = baseStateKey(base);
        generatedBaseStates[key] = {
          key,
          base,
          setupSteps: baseScenario.steps,
          snapshot,
          fingerprint: {
            base,
            seed: baseScenario.seed,
            players: baseScenario.players,
            baseSetupHash: computeBaseSetupHash(baseScenario.steps),
            compiledResultId: runtime.compiledResultId,
            manifestHash: runtime.manifestHash,
            gameId: runtime.gameId,
          },
        };
      }

      const generatedDir = path.join(projectRoot, "test", "generated");
      await ensureDir(generatedDir);
      await writeGeneratedFiles({
        generatedDir,
        baseStates: generatedBaseStates,
        scenarios,
      });

      consola.success(
        `Generated ${Object.keys(generatedBaseStates).length} base state(s) for ${scenarios.length} scenario(s).`,
      );
    } finally {
      await runtime.cleanup();
    }
  },
});

const runCommand = defineCommand({
  meta: {
    name: "run",
    description:
      "Run TypeScript scenarios from test/scenarios using generated bases",
  },
  args: {
    scenario: {
      type: "string",
      description: "Optional scenario file path under test/scenarios",
    },
    ...CONFIG_FLAG_ARGS,
  },
  async run({ args }) {
    const parsedFlags = parseConfigFlags(args);
    const useRemoteRuntime = shouldUseRemoteTestRuntime(parsedFlags.env);
    const { projectRoot, projectConfig } = await resolveProjectContext(
      parsedFlags,
      { requireAuth: useRemoteRuntime },
    );
    await ensureScenarioImportShim(projectRoot);

    const scenarios = await loadScenarios(projectRoot, {
      scenarioPath: args.scenario,
    });
    const baseScenarios = await loadBaseScenarioDefinitions(projectRoot);

    if (scenarios.length === 0) {
      throw new Error("No scenarios found under test/scenarios/*.scenario.ts");
    }

    validateScenarioBases(scenarios, baseScenarios);

    const baseStates = await loadGeneratedBaseStates(projectRoot);
    const runtime = await resolveTestCommandRuntime({
      projectRoot,
      projectConfig,
      useRemoteRuntime,
    });

    try {
      let passed = 0;
      let failed = 0;
      for (const scenario of scenarios) {
        try {
          await runSingleScenario({
            scenario,
            baseScenario: baseScenarios[scenario.scenario.given.base]!,
            baseStates,
            runtimeFingerprint: {
              compiledResultId: runtime.compiledResultId,
              manifestHash: runtime.manifestHash,
              gameId: runtime.gameId,
            },
            gameId: runtime.gameId,
            compiledResultId: runtime.compiledResultId,
          });
          passed += 1;
          consola.success(`PASS ${scenario.scenario.meta.id}`);
        } catch (error) {
          failed += 1;
          consola.error(
            `FAIL ${scenario.scenario.meta.id}: ${formatScenarioError(error)}`,
          );
        }
      }
      consola.info(`Test summary: ${passed} passed, ${failed} failed.`);
      if (failed > 0) {
        process.exitCode = 1;
      }
    } finally {
      await runtime.cleanup();
    }
  },
});

async function resolveTestCommandRuntime(options: {
  projectRoot: string;
  projectConfig: ProjectConfig;
  useRemoteRuntime: boolean;
}): Promise<TestCommandRuntime> {
  if (options.useRemoteRuntime) {
    const latestCompiledResult = await resolveCompiledResultForRun(
      options.projectRoot,
      options.projectConfig,
    );
    return {
      gameId: options.projectConfig.gameId,
      compiledResultId: latestCompiledResult.id,
      manifestHash: options.projectConfig.manifestContentHash,
      cleanup: async () => undefined,
    };
  }

  const harness = await startLocalHarnessSession({
    projectRoot: options.projectRoot,
    projectConfig: options.projectConfig,
  });

  return {
    gameId: harness.gameId,
    compiledResultId: harness.compiledResultId,
    manifestHash: harness.manifestHash,
    cleanup: harness.stop,
  };
}

export default defineCommand({
  meta: {
    name: "test",
    description: "TypeScript-only test runner with deterministic base states",
  },
  subCommands: {
    generate: generateCommand,
    run: runCommand,
  },
});

async function runSingleScenario(options: {
  scenario: LoadedScenario;
  baseScenario: BaseScenarioDefinition;
  baseStates: BaseStateFile;
  runtimeFingerprint: {
    compiledResultId: string;
    manifestHash?: string;
    gameId: string;
  };
  gameId: string;
  compiledResultId: string;
}): Promise<void> {
  const {
    scenario,
    baseScenario,
    baseStates,
    runtimeFingerprint,
    gameId,
    compiledResultId,
  } = options;
  const key = baseStateKey(scenario.scenario.given.base);
  const baseState = baseStates[key];
  if (!baseState) {
    throw new Error(
      `Missing generated base state '${key}'. Run 'dreamboard test generate' first.`,
    );
  }

  validateFingerprint({
    generatedFingerprint: baseState.fingerprint,
    runtimeFingerprint: {
      ...runtimeFingerprint,
      base: scenario.scenario.given.base,
      seed: baseScenario.seed,
      players: baseScenario.players,
      baseSetupHash: computeBaseSetupHash(baseScenario.steps),
    },
  });

  const {
    data: session,
    error: sessionError,
    response: sessionResponse,
  } = await createSession({
    path: { gameId },
    body: {
      compiledResultId,
      seed: baseState.fingerprint.seed,
      playerCount: baseState.fingerprint.players,
      autoAssignSeats: true,
    },
  });
  if (!session || sessionError) {
    throw new Error(
      formatApiError(
        sessionError,
        sessionResponse,
        "Failed to create test session",
      ),
    );
  }

  const { error: startError, response: startResponse } = await startGame({
    path: { sessionId: session.sessionId },
  });
  if (startError) {
    throw new Error(
      formatApiError(startError, startResponse, "Failed to start test session"),
    );
  }

  const stream = await SessionEventStream.create(session.sessionId);
  try {
    await stream.waitForYourTurn(DEFAULT_TIMEOUT_MS);
    await executeSteps(stream, session.sessionId, baseState.setupSteps);
    stream.resetEvents();
    for (const step of scenario.scenario.when.steps) {
      await submitStep(stream, session.sessionId, step, "scenario");
    }
  } finally {
    await stream.close();
  }

  const eventInspector = new EventInspector(stream.events);
  const expectApi = createExpectApi();
  const rawState =
    stream.latestGameState ?? (baseState.snapshot as Record<string, unknown>);
  const gameState = {
    ...rawState,
    globalVariables: tryJsonParse(rawState.globalVariables),
    playerVariables: tryJsonParse(rawState.playerVariables),
  };
  await scenario.scenario.then.assert({
    gameState,
    events: eventInspector,
    expect: expectApi,
  });
}

async function loadGeneratedBaseStates(
  projectRoot: string,
): Promise<BaseStateFile> {
  const filePath = path.join(
    projectRoot,
    "test",
    "generated",
    "base-states.generated.ts",
  );
  if (!(await exists(filePath))) {
    throw new Error(
      "Missing test/generated/base-states.generated.ts. Run 'dreamboard test generate' first.",
    );
  }
  const module =
    await importTypeScriptModule<Record<string, unknown>>(filePath);
  const baseStates = module.BASE_STATES as BaseStateFile | undefined;
  if (!baseStates || typeof baseStates !== "object") {
    throw new Error("Generated base states module is invalid.");
  }
  return baseStates;
}

async function loadScenarios(
  projectRoot: string,
  options: {
    scenarioPath?: string;
  },
): Promise<LoadedScenario[]> {
  const scenarioFiles = options.scenarioPath
    ? [path.resolve(projectRoot, options.scenarioPath)]
    : await discoverScenarioFiles(path.join(projectRoot, "test", "scenarios"));

  const loaded: LoadedScenario[] = [];
  for (const scenarioFile of scenarioFiles) {
    const module =
      await importTypeScriptModule<Record<string, unknown>>(scenarioFile);
    loaded.push({
      filePath: scenarioFile,
      scenario: (() => {
        try {
          return parseScenarioDefinition(module.default);
        } catch (error) {
          if (error instanceof Error) {
            throw new Error(
              `Invalid scenario '${scenarioFile}': ${error.message}`,
            );
          }
          throw error;
        }
      })(),
    });
  }

  return loaded;
}

async function discoverScenarioFiles(root: string): Promise<string[]> {
  if (!(await exists(root))) {
    return [];
  }
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const entryPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await discoverScenarioFiles(entryPath)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(TEST_SCENARIO_SUFFIX)) {
      files.push(entryPath);
    }
  }
  files.sort();
  return files;
}

function baseStateKey(base: string): string {
  return base;
}

async function captureBaseSnapshot(options: {
  gameId: string;
  compiledResultId: string;
  baseSteps: ApiScenarioStep[];
  seed: number;
  players: number;
}): Promise<Record<string, unknown>> {
  const {
    data: session,
    error: sessionError,
    response: sessionResponse,
  } = await createSession({
    path: { gameId: options.gameId },
    body: {
      compiledResultId: options.compiledResultId,
      seed: options.seed,
      playerCount: options.players,
      autoAssignSeats: true,
    },
  });
  if (!session || sessionError) {
    throw new Error(
      formatApiError(
        sessionError,
        sessionResponse,
        "Failed to create session for test generation",
      ),
    );
  }

  const { error: startError, response: startResponse } = await startGame({
    path: { sessionId: session.sessionId },
  });
  if (startError) {
    throw new Error(
      formatApiError(
        startError,
        startResponse,
        "Failed to start session for test generation",
      ),
    );
  }

  const stream = await SessionEventStream.create(session.sessionId);
  try {
    await stream.waitForYourTurn(DEFAULT_TIMEOUT_MS);
    await executeSteps(stream, session.sessionId, options.baseSteps);
    return stream.latestGameState ?? {};
  } finally {
    await stream.close();
  }
}

async function writeGeneratedFiles(options: {
  generatedDir: string;
  baseStates: BaseStateFile;
  scenarios: LoadedScenario[];
}): Promise<void> {
  const generatedHeader =
    "// Generated by dreamboard test generate. Do not edit by hand.\n";
  const baseStatesContent = `${generatedHeader}export const BASE_STATES = ${JSON.stringify(options.baseStates, null, 2)} as const;\n`;
  const baseStatesDtsContent = `${generatedHeader}export declare const BASE_STATES: Record<string, {\n  key: string;\n  base: string;\n  setupSteps: Array<{\n    playerId: string;\n    actionType: string;\n    parameters?: Record<string, unknown>;\n    turns?: number;\n  }>;\n  snapshot: Record<string, unknown>;\n  fingerprint: {\n    base: string;\n    seed: number;\n    players: number;\n    baseSetupHash: string;\n    compiledResultId: string;\n    manifestHash?: string;\n    gameId: string;\n  };\n}>;\n`;

  const manifest = options.scenarios.map((scenario) => ({
    id: scenario.scenario.meta.id,
    filePath: path.relative(
      path.dirname(options.generatedDir),
      scenario.filePath,
    ),
    base: scenario.scenario.given.base,
  }));
  const scenarioManifestContent = `${generatedHeader}export const SCENARIO_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;\n`;

  await writeTextFile(
    path.join(options.generatedDir, "base-states.generated.ts"),
    baseStatesContent,
  );
  await writeTextFile(
    path.join(options.generatedDir, "base-states.generated.d.ts"),
    baseStatesDtsContent,
  );
  await writeTextFile(
    path.join(options.generatedDir, "scenario-manifest.generated.ts"),
    scenarioManifestContent,
  );
  await writeJsonFile(
    path.join(options.generatedDir, ".generation-meta.json"),
    {
      generatedAt: new Date().toISOString(),
      scenarioCount: options.scenarios.length,
      baseStateCount: Object.keys(options.baseStates).length,
    },
  );
}

async function ensureScenarioImportShim(projectRoot: string): Promise<void> {
  // Ensure the project-level testing-types.ts is the typed source of truth for
  // both runtime exports and type definitions. Writing the full typed content
  // here prevents testing-types.ts from shadowing testing-types.d.ts with a
  // stub that omits AssertContext and all other exported types (TypeScript
  // prefers .ts over .d.ts during module resolution, so a stub .ts makes the
  // .d.ts types unreachable — causing `dreamboard push` type errors across all
  // scenario files while `dreamboard test run` passes silently via Bun's
  // lenient type import handling).
  //
  // The file is only written when it does not exist or still contains the old
  // minimal stub, preserving any intentional user edits.
  const testingTypesRuntimePath = path.join(
    projectRoot,
    "test",
    "testing-types.ts",
  );
  const existingTestingTypes = await readTextFileIfExists(
    testingTypesRuntimePath,
  );
  if (shouldRefreshGeneratedTestingTypes(existingTestingTypes)) {
    await ensureDir(path.dirname(testingTypesRuntimePath));
    await writeTextFile(testingTypesRuntimePath, TESTING_TYPES_CONTENT);
  }

  await migrateLegacyScenarioImports(projectRoot);

  // Clean up stale .d.ts left behind by older `dreamboard new` scaffolds.
  const staleDtsPath = path.join(projectRoot, "test", "testing-types.d.ts");
  if (await exists(staleDtsPath)) {
    await unlink(staleDtsPath);
  }
}

function shouldRefreshGeneratedTestingTypes(
  existingContent: string | null,
): boolean {
  if (existingContent === null || existingContent.trim().length === 0) {
    return true;
  }
  if (existingContent === TESTING_TYPES_STUB) {
    return true;
  }
  return existingContent.startsWith(GENERATED_TESTING_TYPES_PREFIX);
}

function createExpectApi(): ExpectApi {
  return (actual: unknown) => ({
    toBe: (expected: unknown) => {
      if (actual !== expected) {
        throw new Error(
          `Expected '${String(actual)}' to be '${String(expected)}'.`,
        );
      }
    },
    toEqual: (expected: unknown) => {
      if (!isDeepStrictEqual(actual, expected)) {
        throw new Error("Expected values to be deeply equal.");
      }
    },
    toBeDefined: () => {
      if (actual === undefined) {
        throw new Error("Expected value to be defined.");
      }
    },
    toBeUndefined: () => {
      if (actual !== undefined) {
        throw new Error(
          `Expected value to be undefined, but received '${String(actual)}'.`,
        );
      }
    },
    toContain: (expected: unknown) => {
      if (Array.isArray(actual)) {
        if (!actual.some((item) => isDeepStrictEqual(item, expected))) {
          throw new Error("Expected array to contain value.");
        }
        return;
      }
      if (typeof actual === "string") {
        if (!actual.includes(String(expected))) {
          throw new Error("Expected string to contain value.");
        }
        return;
      }
      throw new Error("toContain expects an array or string actual value.");
    },
    toBeGreaterThanOrEqual: (expected: number) => {
      if (typeof actual !== "number") {
        throw new Error(
          "toBeGreaterThanOrEqual expects a number actual value.",
        );
      }
      if (actual < expected) {
        throw new Error(`Expected ${actual} to be >= ${expected}.`);
      }
    },
  });
}

class EventInspector {
  constructor(private readonly records: EventRecord[]) {}

  count(type: GameMessage["type"]): number {
    return this.records.filter((record) => record.type === type).length;
  }

  last<T extends GameMessage["type"]>(
    type: T,
  ): Extract<GameMessage, { type: T }> | undefined {
    for (let index = this.records.length - 1; index >= 0; index -= 1) {
      const record = this.records[index];
      if (record !== undefined && record.type === type) {
        return record.message as Extract<GameMessage, { type: T }>;
      }
    }
    return undefined;
  }

  all<T extends GameMessage["type"]>(
    type: T,
  ): Array<Extract<GameMessage, { type: T }>> {
    return this.records
      .filter((record) => record.type === type)
      .map((record) => record.message as Extract<GameMessage, { type: T }>);
  }
}

class SessionEventStream {
  readonly events: EventRecord[] = [];
  latestGameState: Record<string, unknown> | undefined;

  private readonly abortController = new AbortController();
  private readonly queue: GameMessage[] = [];
  private readonly waiting: Array<(event: GameMessage) => void> = [];
  private pumpPromise: Promise<void> = Promise.resolve();

  static async create(sessionId: string): Promise<SessionEventStream> {
    const stream = new SessionEventStream();
    const { stream: eventStream } = await subscribeToSessionEvents({
      path: { sessionId },
      signal: stream.abortController.signal,
    });

    stream.pumpPromise = (async () => {
      for await (const event of eventStream as AsyncGenerator<GameMessage>) {
        if (!event) {
          continue;
        }
        stream.onEvent(event);
      }
    })();

    return stream;
  }

  async waitForYourTurn(timeoutMs: number): Promise<YourTurnMessage> {
    while (true) {
      const event = await this.nextEvent(timeoutMs);
      if (event.type === "YOUR_TURN") {
        return event;
      }
    }
  }

  async waitForActionOutcome(
    step: ApiScenarioStep,
    timeoutMs: number,
  ): Promise<"executed" | "rejected"> {
    while (true) {
      const event = await this.nextEvent(timeoutMs);
      if (
        event.type === "ACTION_EXECUTED" &&
        event.playerId === step.playerId &&
        event.action.actionType === step.actionType
      ) {
        return "executed";
      }
      if (event.type === "ACTION_REJECTED") {
        if (!event.targetPlayer || event.targetPlayer === step.playerId) {
          return "rejected";
        }
      }
    }
  }

  async close(): Promise<void> {
    this.abortController.abort();
    try {
      await this.pumpPromise;
    } catch {
      // Ignore cancellation errors from stream shutdown.
    }
  }

  resetEvents(): void {
    this.events.length = 0;
  }

  private onEvent(event: GameMessage): void {
    this.events.push({ type: event.type, message: event });
    const state = extractGameState(event);
    if (state) {
      this.latestGameState = state;
    }

    const waiter = this.waiting.shift();
    if (waiter) {
      waiter(event);
      return;
    }
    this.queue.push(event);
  }

  private async nextEvent(timeoutMs: number): Promise<GameMessage> {
    if (this.queue.length > 0) {
      return this.queue.shift() as GameMessage;
    }

    return new Promise<GameMessage>((resolve, reject) => {
      const timeoutHandle = setTimeout(() => {
        const waiterIndex = this.waiting.indexOf(waiter);
        if (waiterIndex >= 0) {
          this.waiting.splice(waiterIndex, 1);
        }
        reject(
          new Error(
            `Timed out waiting for session events after ${timeoutMs}ms.`,
          ),
        );
      }, timeoutMs);

      const waiter = (event: GameMessage) => {
        clearTimeout(timeoutHandle);
        resolve(event);
      };

      this.waiting.push(waiter);
    });
  }
}

function extractGameState(
  event: GameMessage,
): Record<string, unknown> | undefined {
  if (event.type === "YOUR_TURN") {
    return event.gameState as Record<string, unknown>;
  }
  if (event.type === "ACTION_EXECUTED") {
    return event.newState as Record<string, unknown>;
  }
  if (event.type === "STATE_UPDATE") {
    return event.gameState as Record<string, unknown>;
  }
  if (event.type === "GAME_STARTED") {
    return event.gameState as Record<string, unknown>;
  }
  if (event.type === "HISTORY_RESTORED") {
    return event.gameState as Record<string, unknown>;
  }
  return undefined;
}

export function describeFingerprintMismatch(options: {
  generatedFingerprint: BaseStateArtifact["fingerprint"];
  runtimeFingerprint: {
    base: string;
    seed: number;
    players: number;
    baseSetupHash: string;
    compiledResultId: string;
    manifestHash?: string;
    gameId: string;
  };
}): string | null {
  const baseSetupChanges: string[] = [];
  const compiledResultChanges: string[] = [];
  const projectChanges: string[] = [];

  if (options.generatedFingerprint.base !== options.runtimeFingerprint.base) {
    baseSetupChanges.push("base");
  }
  if (options.generatedFingerprint.seed !== options.runtimeFingerprint.seed) {
    baseSetupChanges.push("seed");
  }
  if (
    options.generatedFingerprint.players !== options.runtimeFingerprint.players
  ) {
    baseSetupChanges.push("players");
  }
  if (
    options.generatedFingerprint.baseSetupHash !==
    options.runtimeFingerprint.baseSetupHash
  ) {
    baseSetupChanges.push("baseSetupHash");
  }
  if (
    options.generatedFingerprint.compiledResultId !==
    options.runtimeFingerprint.compiledResultId
  ) {
    compiledResultChanges.push("compiledResultId");
  }
  if (
    options.generatedFingerprint.manifestHash !==
    options.runtimeFingerprint.manifestHash
  ) {
    compiledResultChanges.push("manifestHash");
  }
  if (
    options.generatedFingerprint.gameId !== options.runtimeFingerprint.gameId
  ) {
    projectChanges.push("gameId");
  }

  const sections: string[] = [];
  if (baseSetupChanges.length > 0) {
    sections.push(`base setup changed (${baseSetupChanges.join(", ")})`);
  }
  if (compiledResultChanges.length > 0) {
    sections.push(
      `compiled result changed (${compiledResultChanges.join(", ")})`,
    );
  }
  if (projectChanges.length > 0) {
    sections.push(`project identity changed (${projectChanges.join(", ")})`);
  }

  if (sections.length === 0) {
    return null;
  }

  return `Fingerprint mismatch: ${sections.join("; ")}. Run 'dreamboard test generate' to refresh deterministic bases.`;
}

function validateFingerprint(options: {
  generatedFingerprint: BaseStateArtifact["fingerprint"];
  runtimeFingerprint: {
    base: string;
    seed: number;
    players: number;
    baseSetupHash: string;
    compiledResultId: string;
    manifestHash?: string;
    gameId: string;
  };
}): void {
  const message = describeFingerprintMismatch(options);
  if (message) {
    throw new Error(message);
  }
}

async function loadBaseScenarioDefinitions(
  projectRoot: string,
): Promise<BaseScenarioDefinitions> {
  const filePath = path.join(projectRoot, "test", "base-scenarios.json");
  if (!(await exists(filePath))) {
    throw new Error(
      "Missing test/base-scenarios.json. Define base checkpoints there, including 'initial-turn'.",
    );
  }

  const parsed = JSON.parse(
    (await readTextFileIfExists(filePath)) ?? "",
  ) as unknown;
  const baseSchema = z.record(
    z.string().min(1),
    z
      .object({
        seed: z.number().int(),
        players: z.number().int().positive(),
        steps: z.array(apiScenarioStepSchema).default([]),
      })
      .strict(),
  );
  const validated = baseSchema.safeParse(parsed);
  if (!validated.success) {
    const message = validated.error.issues
      .map(
        (issue) =>
          `${issue.path.join(".") || "base scenarios"}: ${issue.message}`,
      )
      .join("; ");
    throw new Error(`Invalid test/base-scenarios.json: ${message}`);
  }

  if (!("initial-turn" in validated.data)) {
    throw new Error(
      "Invalid test/base-scenarios.json: 'initial-turn' must be explicitly defined with seed and players.",
    );
  }

  return validated.data;
}

function validateScenarioBases(
  scenarios: LoadedScenario[],
  baseScenarios: BaseScenarioDefinitions,
): void {
  const available = new Set(Object.keys(baseScenarios));
  const invalid = scenarios
    .filter((scenario) => !available.has(scenario.scenario.given.base))
    .map(
      (scenario) =>
        path.relative(process.cwd(), scenario.filePath) +
        ` -> '${scenario.scenario.given.base}'`,
    );

  if (invalid.length === 0) {
    return;
  }

  throw new Error(
    `Unknown given.base value(s): ${invalid.join(", ")}. Available bases: ${Array.from(available).sort().join(", ")}`,
  );
}

async function executeSteps(
  stream: SessionEventStream,
  sessionId: string,
  steps: ApiScenarioStep[],
): Promise<void> {
  for (let i = 0; i < steps.length; i++) {
    const step = steps[i]!;
    const outcome = await submitStep(stream, sessionId, step, "base");
    if (outcome === "rejected") {
      throw new Error(
        `Base setup step ${i + 1}/${steps.length} was rejected: ` +
          `${step.playerId} ${step.actionType} ${JSON.stringify(step.parameters ?? {})}. ` +
          `Ensure all base setup steps use valid actions for the given seed and player count, ` +
          `then re-run 'dreamboard test generate'.`,
      );
    }
  }
}

async function submitStep(
  stream: SessionEventStream,
  sessionId: string,
  step: ApiScenarioStep,
  stage: "base" | "scenario",
): Promise<"executed" | "rejected"> {
  const { error: submitError, response: submitResponse } = await submitAction({
    path: { sessionId },
    body: {
      playerId: step.playerId,
      actionType: step.actionType,
      parameters: JSON.stringify(step.parameters ?? {}),
    },
  });
  // HTTP 400 means the action was rejected by game logic — the server still emits
  // an ACTION_REJECTED event on the stream, so we fall through to waitForActionOutcome.
  if (submitError && submitResponse?.status !== 400) {
    throw new Error(
      formatApiError(
        submitError,
        submitResponse,
        `Failed to submit ${stage} step`,
      ),
    );
  }
  return stream.waitForActionOutcome(step, DEFAULT_TIMEOUT_MS);
}

function computeBaseSetupHash(steps: ApiScenarioStep[]): string {
  return JSON.stringify(steps);
}

function formatScenarioError(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  return String(error);
}

async function startLocalHarnessSession(options: {
  projectRoot: string;
  projectConfig: ProjectConfig;
}): Promise<{
  gameId: string;
  compiledResultId: string;
  manifestHash: string;
  stop: () => Promise<void>;
}> {
  if (typeof Bun === "undefined") {
    throw new Error(
      "Local embedded harness requires Bun from a source checkout. Run `bun run dist/index.js test ... --env local`, or use `--env dev`/`--env prod` from a published install.",
    );
  }

  const module = await import("../services/testing/embedded-harness.js");
  return module.startEmbeddedHarnessSession(options);
}
