import path from "node:path";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { readdir } from "node:fs/promises";
import { isDeepStrictEqual } from "node:util";
import type { Browser, Page } from "playwright";
import type { GameTopologyManifest } from "@dreamboard/sdk-types";
import {
  createSession,
  listPlayerActions,
  startGame,
  submitPlayerAction,
  type GameMessage,
} from "@dreamboard/api-client";
import * as ReducerContractZod from "@dreamboard/reducer-contract/zod";
import type * as Wire from "@dreamboard/reducer-contract/wire";
import { createReducerBundle } from "@dreamboard/app-sdk/reducer";
import { materializeManifestTable } from "@dreamboard/workspace-codegen";
import type { ProjectConfig, ResolvedConfig } from "../../types.js";
import {
  ensureDir,
  exists,
  readTextFileIfExists,
  writeJsonFile,
  writeTextFile,
} from "../../utils/fs.js";
import {
  importTypeScriptModule,
  bundleTypeScriptModuleText,
} from "../../utils/ts-module-loader.js";
import { hashContent } from "../../utils/crypto.js";
import { loadManifest } from "../project/local-files.js";
import {
  REDUCER_TESTING_TYPES_WRAPPER_CONTENT,
  buildReducerTestingContractContent,
} from "../../templates/testing-types-content.js";
import {
  startEmbeddedHarnessSession,
  type EmbeddedHarnessSession,
} from "./embedded-harness.js";
import { subscribeToCliSessionEvents } from "../../utils/session-event-stream.js";
import {
  buildBrowserAuthInitScript,
  configurePlaywrightBrowsersPath,
  waitForGameReady,
} from "../../ui/playwright-runner.js";
import { resolveSetupProfileSelection } from "../workflows/resolve-setup-profile.js";

const GENERATED_TESTING_TYPES_PREFIX = "// Generated by dreamboard";
const TESTING_TYPES_STUB =
  "export function defineScenario(scenario) { return scenario; }\n";
const DEFAULT_TIMEOUT_MS = 10_000;
const BASE_SUFFIX = ".base.ts";
const SCENARIO_SUFFIX = ".scenario.ts";

type TestRunnerName = "reducer" | "embedded" | "browser";

type TypedBaseDefinition = {
  id: string;
  seed?: number;
  players?: number;
  setupProfileId?: string;
  extends?: string;
  setup: (ctx: BaseContext) => void | Promise<void>;
};

type ResolvedBaseDefinition = TypedBaseDefinition & {
  seed: number;
  players: number;
};

type TypedScenarioDefinition = {
  id: string;
  description?: string;
  from: string;
  runners?: readonly TestRunnerName[];
  phase?: string;
  stage?: string;
  when: (ctx: SharedScenarioContext) => void | Promise<void>;
  then: (ctx: SharedScenarioContext) => void | Promise<void>;
};

type LoadedBase = {
  filePath: string;
  definition: TypedBaseDefinition;
  bundleHash: string;
};

type LoadedScenario = {
  filePath: string;
  definition: TypedScenarioDefinition;
  bundleHash: string;
};

type ExpectMatchers = {
  toBe: (expected: unknown) => void;
  toEqual: (expected: unknown) => void;
  toBeDefined: () => void;
  toBeUndefined: () => void;
  toBeNull: () => void;
  toContain: (expected: unknown) => void;
  toBeGreaterThanOrEqual: (expected: number) => void;
};

type ExpectApi = (actual: unknown) => ExpectMatchers;

type HistoryInput = {
  kind: "interaction";
  playerId: string;
  interactionId: string;
  params: Record<string, unknown>;
};

type HistoryRecord = {
  input: HistoryInput;
  accepted: boolean;
  errorCode?: string;
  message?: string;
};

type BaseStateArtifact = {
  key: string;
  base: string;
  snapshot: Record<string, unknown>;
  fingerprint: {
    base: string;
    seed: number;
    players: number;
    baseBundleHash: string;
    manifestHash: string;
    appBundleHash: string;
    uiContractHash: string;
    setupProfileId?: string | null;
    compiledResultId?: string;
    gameId?: string;
    parentBaseId?: string | null;
    parentFingerprintHash?: string | null;
  };
};

type BaseStateFile = Record<string, BaseStateArtifact>;

type BaseContext = {
  game: ScenarioGameApi;
  players: () => readonly string[];
  seat: (index: number) => string;
};

type SharedScenarioContext = BaseContext & {
  state: () => string;
  view: (playerId: string) => unknown;
  interactions: (playerId: string) => readonly Record<string, unknown>[];
  expect: ExpectApi;
};

type ScenarioGameApi = {
  start: () => Promise<void>;
  submit: (
    playerId: string,
    interactionId: string,
    params?: Record<string, unknown>,
  ) => Promise<void>;
};

type SubmissionError = Error & { errorCode?: string };

type BrowserDriverModule = {
  default?: BrowserRunnerDriver;
} & Partial<BrowserRunnerDriver>;

type BrowserRunnerDriver = {
  onReady?: (bridge: BrowserBridgeClient) => Promise<void> | void;
  interaction?: (
    bridge: BrowserBridgeClient,
    input: {
      playerId: string;
      interactionId: string;
      params: unknown;
    },
  ) => Promise<boolean | void> | boolean | void;
};

type BrowserSnapshot = {
  sessionId: string | null;
  shortCode: string | null;
  version: number;
  currentPhase: string | null;
  controllingPlayerId: string;
  controllablePlayerIds: string[];
  view: unknown;
  availableInteractions?: string[];
};

export type ReducerNativeScenarioResult = {
  id: string;
  success: boolean;
  error?: string;
};

export type ReducerNativeScenarioSummary = {
  passed: number;
  failed: number;
  results: ReducerNativeScenarioResult[];
};

export type SeededScenarioSession = {
  sessionId: string;
  shortCode: string;
  gameId: string;
  seed: number;
  playerCount: number;
  setupProfileId: string | null;
  scenarioId: string;
  phase: string | null;
  stage: string | null;
};

type BrowserBridgeClient = {
  snapshot: () => Promise<BrowserSnapshot>;
  submitInteraction: (
    playerId: string,
    interactionId: string,
    params: unknown,
  ) => Promise<void>;
  waitForVersionChange: (
    previousVersion: number,
    timeoutMs?: number,
  ) => Promise<BrowserSnapshot>;
};

type GameplaySnapshot = {
  version: number;
  actionSetVersion: string;
  currentPhase: string | null;
  playerId: string;
  view: unknown;
  availableInteractions: string[];
};

let testingExpectApiFactoryPromise:
  | Promise<
      (options?: {
        matchSnapshot?: (name: string | undefined, actual: unknown) => void;
      }) => ExpectApi
    >
  | undefined;

async function loadTestingExpectApiFactory(): Promise<
  (options?: {
    matchSnapshot?: (name: string | undefined, actual: unknown) => void;
  }) => ExpectApi
> {
  testingExpectApiFactoryPromise ??= import("@dreamboard/testing").then(
    (module) =>
      module.createExpectApi as (options?: {
        matchSnapshot?: (name: string | undefined, actual: unknown) => void;
      }) => ExpectApi,
  );
  return testingExpectApiFactoryPromise;
}

function createSubmissionError(
  errorCode: string | undefined,
  message: string | undefined,
  fallbackMessage: string,
): SubmissionError {
  const error = new Error(message ?? fallbackMessage) as SubmissionError;
  error.name = "SubmissionError";
  error.errorCode = errorCode;
  return error;
}

function parseJsonValue(value: unknown): unknown {
  if (typeof value !== "string") {
    return value;
  }
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}

function deepEqual(left: unknown, right: unknown): boolean {
  return isDeepStrictEqual(left, right);
}

function normalizeScenarioRunners(
  runners: readonly TestRunnerName[] | undefined,
): readonly TestRunnerName[] {
  return runners && runners.length > 0 ? runners : ["reducer"];
}

function shouldRefreshReducerTestingTypes(
  existingContent: string | null,
): boolean {
  if (
    existingContent === null ||
    existingContent.trim().length === 0 ||
    existingContent === TESTING_TYPES_STUB ||
    existingContent.startsWith(GENERATED_TESTING_TYPES_PREFIX)
  ) {
    return true;
  }
  return false;
}

async function discoverFiles(root: string, suffix: string): Promise<string[]> {
  if (!(await exists(root))) {
    return [];
  }
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const entryPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await discoverFiles(entryPath, suffix)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(suffix)) {
      files.push(entryPath);
    }
  }
  files.sort();
  return files;
}

function isFunction(value: unknown): value is (...args: never[]) => unknown {
  return typeof value === "function";
}

function parseTypedBaseDefinition(value: unknown): TypedBaseDefinition {
  if (
    typeof value !== "object" ||
    value === null ||
    !("id" in value) ||
    typeof value.id !== "string" ||
    !("setup" in value) ||
    !isFunction(value.setup)
  ) {
    throw new Error("Invalid reducer-native base definition.");
  }
  const parentBaseId =
    "extends" in value && typeof value.extends === "string"
      ? value.extends
      : undefined;
  const seed =
    "seed" in value && typeof value.seed === "number" ? value.seed : undefined;
  const players =
    "players" in value && typeof value.players === "number"
      ? value.players
      : undefined;
  if ((seed === undefined || players === undefined) && !parentBaseId) {
    throw new Error(
      "Invalid reducer-native base definition. Base definitions without --extends must declare numeric seed and players.",
    );
  }
  const setupProfileId =
    "setupProfileId" in value && typeof value.setupProfileId === "string"
      ? value.setupProfileId
      : undefined;
  return {
    ...(value as TypedBaseDefinition),
    seed,
    players,
    setupProfileId,
    extends: parentBaseId,
  };
}

function parseTypedScenarioDefinition(value: unknown): TypedScenarioDefinition {
  if (
    typeof value !== "object" ||
    value === null ||
    !("id" in value) ||
    typeof value.id !== "string" ||
    !("from" in value) ||
    typeof value.from !== "string" ||
    !("when" in value) ||
    !isFunction(value.when) ||
    !("then" in value) ||
    !isFunction(value.then)
  ) {
    throw new Error("Invalid reducer-native scenario definition.");
  }
  const phase =
    "phase" in value && typeof value.phase === "string"
      ? value.phase
      : undefined;
  const stage =
    "stage" in value && typeof value.stage === "string"
      ? value.stage
      : undefined;
  return {
    ...(value as TypedScenarioDefinition),
    phase,
    stage,
  };
}

export async function isReducerNativeTestingWorkspace(
  projectRoot: string,
): Promise<boolean> {
  return (
    (await exists(path.join(projectRoot, "app", "game.ts"))) &&
    (await exists(
      path.join(projectRoot, "shared", "generated", "ui-contract.ts"),
    ))
  );
}

export async function ensureReducerNativeTestingFiles(
  projectRoot: string,
): Promise<void> {
  const testingTypesPath = path.join(projectRoot, "test", "testing-types.ts");
  const testingContractPath = path.join(
    projectRoot,
    "test",
    "generated",
    "testing-contract.ts",
  );
  const baseStatesPath = path.join(
    projectRoot,
    "test",
    "generated",
    "base-states.generated.ts",
  );
  const baseStatesDtsPath = path.join(
    projectRoot,
    "test",
    "generated",
    "base-states.generated.d.ts",
  );
  const scenarioManifestPath = path.join(
    projectRoot,
    "test",
    "generated",
    "scenario-manifest.generated.ts",
  );

  await ensureDir(path.dirname(testingTypesPath));
  await ensureDir(path.dirname(testingContractPath));

  const existingTestingTypes = await readTextFileIfExists(testingTypesPath);
  if (shouldRefreshReducerTestingTypes(existingTestingTypes)) {
    await writeTextFile(
      testingTypesPath,
      REDUCER_TESTING_TYPES_WRAPPER_CONTENT,
    );
  }

  const rejectionCodes = await collectKnownRejectionCodes(projectRoot);
  await writeTextFile(
    testingContractPath,
    buildReducerTestingContractContent({ rejectionCodes }),
  );

  const header =
    "// Generated by dreamboard test generate. Do not edit by hand.\n";
  if (!(await exists(baseStatesPath))) {
    await writeTextFile(
      baseStatesPath,
      `${header}export const BASE_STATES = {} as const;\n`,
    );
  }
  if (!(await exists(baseStatesDtsPath))) {
    await writeTextFile(
      baseStatesDtsPath,
      `${header}export declare const BASE_STATES: Record<string, unknown>;\n`,
    );
  }
  if (!(await exists(scenarioManifestPath))) {
    await writeTextFile(
      scenarioManifestPath,
      `${header}export const SCENARIO_MANIFEST = [] as const;\n`,
    );
  }
}

const DEFAULT_REJECTION_CODES = [
  "NOT_YOUR_TURN",
  "action-unavailable",
  "invalid-action-params",
  "prompt-not-owned",
] as const;

async function collectKnownRejectionCodes(
  projectRoot: string,
): Promise<string[]> {
  const knownCodes = new Set<string>(DEFAULT_REJECTION_CODES);
  const gamePath = path.join(projectRoot, "app", "game.ts");
  if (!(await exists(gamePath))) {
    return Array.from(knownCodes).sort((left, right) =>
      left.localeCompare(right),
    );
  }

  try {
    const module =
      await importTypeScriptModule<Record<string, unknown>>(gamePath);
    const phases =
      (
        module.default as {
          phases?: Record<
            string,
            {
              interactions?: Record<string, { errorCodes?: readonly string[] }>;
            }
          >;
        }
      )?.phases ?? {};
    for (const phase of Object.values(phases)) {
      const interactions = phase.interactions ?? {};
      for (const interaction of Object.values(interactions)) {
        for (const errorCode of interaction.errorCodes ?? []) {
          if (typeof errorCode === "string" && errorCode.length > 0) {
            knownCodes.add(errorCode);
          }
        }
      }
    }
  } catch {
    // Keep the generated contract usable even if the game module fails to load.
  }

  return Array.from(knownCodes).sort((left, right) =>
    left.localeCompare(right),
  );
}

export async function loadTypedBases(
  projectRoot: string,
): Promise<LoadedBase[]> {
  const baseFiles = await discoverFiles(
    path.join(projectRoot, "test", "bases"),
    BASE_SUFFIX,
  );
  const loaded: LoadedBase[] = [];
  for (const filePath of baseFiles) {
    const [module, bundledText] = await Promise.all([
      importTypeScriptModule<Record<string, unknown>>(filePath),
      bundleTypeScriptModuleText(filePath),
    ]);
    loaded.push({
      filePath,
      definition: parseTypedBaseDefinition(module.default),
      bundleHash: hashContent(bundledText),
    });
  }
  return loaded;
}

export async function loadTypedScenarios(
  projectRoot: string,
  options: { scenarioPath?: string },
): Promise<LoadedScenario[]> {
  const scenarioFiles = options.scenarioPath
    ? [path.resolve(projectRoot, options.scenarioPath)]
    : await discoverFiles(
        path.join(projectRoot, "test", "scenarios"),
        SCENARIO_SUFFIX,
      );
  const loaded: LoadedScenario[] = [];
  for (const filePath of scenarioFiles) {
    const [module, bundledText] = await Promise.all([
      importTypeScriptModule<Record<string, unknown>>(filePath),
      bundleTypeScriptModuleText(filePath),
    ]);
    loaded.push({
      filePath,
      definition: parseTypedScenarioDefinition(module.default),
      bundleHash: hashContent(bundledText),
    });
  }
  return loaded;
}

class KotlinSeededRandom {
  private x: number;
  private y: number;
  private z: number;
  private w: number;
  private v: number;
  private addend: number;

  constructor(seed: number) {
    const seedBig = BigInt.asIntN(64, BigInt(Math.trunc(seed)));
    const seed1 = Number(BigInt.asIntN(32, seedBig));
    const seed2 = Number(BigInt.asIntN(32, seedBig >> 32n));

    this.x = seed1 | 0;
    this.y = seed2 | 0;
    this.z = 0;
    this.w = 0;
    this.v = ~seed1;
    this.addend = ((seed1 << 10) ^ (seed2 >>> 4)) | 0;

    if ((this.x | this.y | this.z | this.w | this.v) === 0) {
      throw new Error(
        "Kotlin random seed must initialize at least one state word.",
      );
    }

    for (let index = 0; index < 64; index += 1) {
      this.nextInt();
    }
  }

  nextInt(): number {
    let next = this.x | 0;
    next ^= next >>> 2;
    this.x = this.y;
    this.y = this.z;
    this.z = this.w;
    const currentV = this.v | 0;
    this.w = currentV;
    next = (next ^ (next << 1) ^ currentV ^ (currentV << 4)) | 0;
    this.v = next;
    this.addend = (this.addend + 362437) | 0;
    return (next + this.addend) | 0;
  }

  private nextBits(bitCount: number): number {
    if (bitCount <= 0) {
      return 0;
    }
    return this.nextInt() >>> (32 - bitCount);
  }

  nextIntBound(bound: number): number {
    if (bound <= 0) {
      throw new Error("bound must be positive");
    }

    if ((bound & -bound) === bound) {
      const bitCount = 31 - Math.clz32(bound);
      return this.nextBits(bitCount);
    }

    let value: number;
    while (true) {
      const bits = this.nextInt() >>> 1;
      value = bits % bound;
      if (bits - value + (bound - 1) >= 0) {
        return value;
      }
    }
  }

  nextLong(): number {
    const high = BigInt(this.nextInt());
    const low = BigInt(this.nextInt());
    return Number(BigInt.asIntN(64, (high << 32n) + low));
  }
}

function shuffleWithKotlinRandom<T>(
  values: readonly T[],
  random: KotlinSeededRandom,
): T[] {
  const next = [...values];
  for (let index = next.length - 1; index > 0; index -= 1) {
    const swapIndex = random.nextIntBound(index + 1);
    const current = next[index];
    next[index] = next[swapIndex] as T;
    next[swapIndex] = current as T;
  }
  return next;
}

type EffectiveBaseSetup = {
  setupProfileId: string | null;
};

type GeneratedInitialTableFactory = (options?: {
  playerIds?: readonly string[];
  shuffleItems?: <Value>(values: readonly Value[]) => Value[];
}) => Record<string, unknown>;

function resolveEffectiveBaseSetup(options: {
  manifest: GameTopologyManifest;
  base: TypedBaseDefinition;
  basesById?: Map<string, LoadedBase>;
}): EffectiveBaseSetup {
  const inheritedSetupProfileId =
    options.base.setupProfileId ??
    (options.base.extends && options.basesById
      ? resolveEffectiveBaseSetup({
          manifest: options.manifest,
          base:
            options.basesById.get(options.base.extends)?.definition ??
            (() => {
              throw new Error(
                `Base '${options.base.id}' extends unknown parent '${options.base.extends}'.`,
              );
            })(),
          basesById: options.basesById,
        }).setupProfileId
      : undefined);
  const selection = resolveSetupProfileSelection({
    manifest: options.manifest,
    requestedSetupProfileId: inheritedSetupProfileId ?? undefined,
  });
  return {
    setupProfileId: selection.id,
  };
}

function resolveBaseDefinition(
  base: LoadedBase,
  basesById: Map<string, LoadedBase>,
): ResolvedBaseDefinition {
  const inherited =
    base.definition.extends !== undefined
      ? resolveBaseDefinition(
          basesById.get(base.definition.extends) ??
            (() => {
              throw new Error(
                `Base '${base.definition.id}' extends unknown parent '${base.definition.extends}'.`,
              );
            })(),
          basesById,
        )
      : null;

  const seed = base.definition.seed ?? inherited?.seed;
  const players = base.definition.players ?? inherited?.players;
  if (seed === undefined || players === undefined) {
    throw new Error(
      `Base '${base.definition.id}' must resolve numeric seed and players.`,
    );
  }

  return {
    ...base.definition,
    seed,
    players,
    setupProfileId:
      base.definition.setupProfileId ?? inherited?.setupProfileId ?? undefined,
  };
}

function summarizeTableValidationError(
  manifest: GameTopologyManifest,
  error: Error,
): string {
  const issues = error.message
    .split("; ")
    .map((issue) => issue.trim())
    .filter((issue) => issue.length > 0);

  if (
    issues.length === 0 ||
    !issues.every((issue) => issue.startsWith("table"))
  ) {
    return error.message;
  }

  const boardBaseIdByRuntimeId = new Map<string, string>(
    (manifest.boards ?? []).flatMap((board) =>
      board.scope === "perPlayer"
        ? Array.from(
            { length: manifest.players.maxPlayers },
            (_, index) =>
              [`${board.id}:player-${index + 1}`, board.id] as const,
          )
        : ([[board.id, board.id]] as const),
    ),
  );

  const representativeIssues = issues.slice(0, 3).map((issue) => {
    const [, runtimeBoardId = ""] =
      issue.match(/^table\.boards\.byId\.([^.]+)\./) ?? [];
    const boardBaseId = boardBaseIdByRuntimeId.get(runtimeBoardId);
    if (!boardBaseId) {
      return `- ${issue.replace(/^table\./, "")}`;
    }
    const boardSpecificPath = issue
      .replace(/^table\.boards\.byId\.[^.]+\./, "")
      .replace(/^table\./, "");
    return `- board '${boardBaseId}' (${runtimeBoardId}): ${boardSpecificPath}`;
  });

  return [
    `Reducer-native table validation failed with ${issues.length} issue${issues.length === 1 ? "" : "s"}.`,
    "Likely root cause: the generated test table shape does not match the authored manifest topology.",
    ...representativeIssues,
    "Pass --debug for the full validation dump.",
  ].join("\n");
}

class ShadowReducerRuntime {
  private readonly bundle: ReturnType<typeof createReducerBundle>;
  private readonly playerIds: string[];
  private readonly historyRecords: HistoryRecord[] = [];
  private state: Record<string, unknown> | null = null;
  private started = false;

  constructor(
    private readonly manifest: GameTopologyManifest,
    private readonly gameModuleDefault: unknown,
    private readonly createInitialTable: GeneratedInitialTableFactory | null,
    private readonly seed: number,
    private readonly players: number,
    private readonly setupProfileId: string | null,
    private readonly debug = false,
  ) {
    if (
      typeof gameModuleDefault !== "object" ||
      gameModuleDefault === null ||
      !("contract" in gameModuleDefault)
    ) {
      throw new Error(
        "app/game.ts must export a reducer-native game definition.",
      );
    }
    this.bundle = createReducerBundle(gameModuleDefault as never);
    this.playerIds = Array.from(
      { length: players },
      (_, index) => `player-${index + 1}`,
    );
  }

  async start(): Promise<void> {
    if (this.started) {
      return;
    }
    const random = new KotlinSeededRandom(this.seed);
    const shuffleItems = <Value>(values: readonly Value[]) =>
      shuffleWithKotlinRandom(values, random);
    const table =
      this.createInitialTable?.({
        playerIds: this.playerIds,
        shuffleItems,
      }) ??
      materializeManifestTable({
        manifest: this.manifest,
        playerIds: this.playerIds,
        shuffleItems,
      });
    const rngSeed = random.nextLong();
    try {
      this.state = (await this.bundle.initialize({
        table: table as never,
        playerIds: this.playerIds,
        rngSeed,
        setup: this.setupProfileId
          ? {
              profileId: this.setupProfileId,
            }
          : null,
      })) as Record<string, unknown>;
    } catch (error) {
      if (!this.debug && error instanceof Error) {
        throw new Error(summarizeTableValidationError(this.manifest, error));
      }
      throw error;
    }
    this.started = true;
  }

  phase(): string {
    return (
      ((
        (this.state?.domain as { flow?: { currentPhase?: string } } | undefined)
          ?.flow as { currentPhase?: string } | undefined
      )?.currentPhase ??
        null) ||
      ""
    );
  }

  playerOrder(): string[] {
    return this.playerIds;
  }

  rawState(): Record<string, unknown> {
    if (!this.state) {
      throw new Error("Reducer runtime has not been started.");
    }
    return this.state;
  }

  hydrate(snapshot: Record<string, unknown>): void {
    this.state = structuredClone(snapshot);
    this.started = true;
  }

  projectAllSeats(): {
    currentStage: string | null;
    stageSeats: string[];
    seats: Record<
      string,
      {
        view?: unknown;
        availableInteractions?: Array<Record<string, unknown>>;
        zones?: Record<string, unknown>;
      }
    >;
  } {
    const projection = this.bundle.projectSeatsDynamic({
      state: this.rawState() as never,
      playerIds: this.playerIds as never,
    }) as {
      currentStage?: string | null;
      stageSeats?: string[];
      seats?: Record<
        string,
        {
          view?: unknown;
          availableInteractions?: Array<Record<string, unknown>>;
          zones?: Record<string, unknown>;
        }
      >;
    };
    return {
      currentStage: projection.currentStage ?? null,
      stageSeats: projection.stageSeats ?? [],
      seats: projection.seats ?? {},
    };
  }

  currentStage(): string | null {
    return this.projectAllSeats().currentStage;
  }

  view(playerId: string): unknown {
    return this.projectAllSeats().seats[playerId]?.view ?? null;
  }

  availableInteractionsForPlayer(playerId: string): string[] {
    const projection = this.projectAllSeats();
    const seat = projection.seats[playerId];
    const descriptors = seat?.availableInteractions ?? [];
    return descriptors
      .filter(
        (descriptor) =>
          !!descriptor && typeof descriptor.interactionId === "string",
      )
      .map((descriptor) => descriptor.interactionId as string);
  }

  /**
   * Phase-kind interaction descriptors (action + prompt) available to
   * `playerId` in the current phase. Surfaces the same projection the UI
   * SDK consumes, so scenarios can assert addressee authorization and
   * availability without reaching into game-specific state. Returned as
   * loose records — the typed `InteractionDescriptor` shape is narrowed
   * downstream in the workspace-generated `testing-contract.ts`.
   */
  interactionsForPlayer(playerId: string): Array<Record<string, unknown>> {
    return this.projectAllSeats().seats[playerId]?.availableInteractions ?? [];
  }

  clearHistory(): void {
    this.historyRecords.length = 0;
  }

  private async applyInput(input: HistoryInput): Promise<void> {
    const parsedInput = toReducerInput(input);
    const validation = parseWirePayload(
      "validateInput",
      await this.bundle.validateInput({
        state: this.rawState() as never,
        input: parsedInput as never,
      }),
      "ReducerInputValidationResult",
      ReducerContractZod.ReducerInputValidationResultSchema,
    );
    if (!validation.valid) {
      const record = {
        input,
        accepted: false,
        errorCode: validation.errorCode,
        message: validation.message,
      };
      this.historyRecords.push(record);
      throw createSubmissionError(
        validation.errorCode,
        validation.message,
        "Reducer input rejected.",
      );
    }

    const result = assertDispatchResultWireContract(
      await this.bundle.dispatch({
        state: this.rawState() as never,
        input: parsedInput as never,
      }),
    );

    if (result.kind === "reject") {
      const record = {
        input,
        accepted: false,
        errorCode: result.errorCode,
        message: result.message,
      };
      this.historyRecords.push(record);
      throw createSubmissionError(
        result.errorCode,
        result.message,
        "Reducer input rejected.",
      );
    }

    this.state = result.state as Record<string, unknown>;
    this.historyRecords.push({ input, accepted: true });
  }

  async submitInteraction(
    playerId: string,
    interactionId: string,
    params: Record<string, unknown>,
  ): Promise<void> {
    await this.applyInput({
      kind: "interaction",
      playerId,
      interactionId,
      params,
    });
  }
}

/**
 * Translate the harness's history record into the unified `interaction`
 * wire shape the ingress bundle accepts.
 */
function toReducerInput(input: HistoryInput): Record<string, unknown> {
  return {
    kind: "interaction",
    playerId: input.playerId,
    interactionId: input.interactionId,
    params: input.params,
  };
}

class EmbeddedGameplayTracker {
  private readonly abortController = new AbortController();
  private readonly state: GameplaySnapshot = {
    version: -1,
    actionSetVersion: "",
    currentPhase: null,
    playerId: "player-1",
    view: null,
    availableInteractions: [],
  };
  private readonly events: GameMessage[] = [];
  private connected = false;

  constructor(
    private readonly sessionId: string,
    private readonly playerId: string,
  ) {
    this.state.playerId = playerId;
  }

  async connect(): Promise<void> {
    if (this.connected) {
      return;
    }
    this.connected = true;
    const { stream } = await subscribeToCliSessionEvents({
      sessionId: this.sessionId,
      playerId: this.playerId,
      signal: this.abortController.signal,
      clientSource: "dreamboard-cli-test",
    });

    void (async () => {
      for await (const message of stream) {
        if (!message) {
          continue;
        }
        this.events.push(message);
        this.onMessage(message);
      }
    })();
  }

  close(): void {
    this.abortController.abort();
  }

  snapshot(): GameplaySnapshot {
    return {
      ...this.state,
      availableInteractions: [...this.state.availableInteractions],
    };
  }

  private onMessage(message: GameMessage): void {
    if (message.type === "gameplay.bootstrap") {
      this.state.version = message.gameplay.version;
      this.state.actionSetVersion = message.gameplay.actionSetVersion;
      this.state.playerId = message.gameplay.playerId;
      this.state.currentPhase = message.gameplay.currentPhase;
      this.state.view = parseSeatView(message.gameplay.view);
      this.state.availableInteractions = (
        message.gameplay.availableInteractions ?? []
      ).map((interaction) => interaction.interactionId);
      return;
    }

    if (
      message.type === "gameplay.updated" ||
      message.type === "gameplay.resynced"
    ) {
      this.state.version = message.gameplay.version;
      this.state.actionSetVersion = message.gameplay.actionSetVersion;
      this.state.playerId = message.gameplay.playerId;
      this.state.currentPhase = message.gameplay.currentPhase;
      this.state.view = parseSeatView(message.gameplay.view);
      this.state.availableInteractions = (
        message.gameplay.availableInteractions ?? []
      ).map((interaction) => interaction.interactionId);
    }
  }

  async waitForVersionChange(
    previousVersion: number,
    timeoutMs = DEFAULT_TIMEOUT_MS,
  ): Promise<void> {
    const startedAt = Date.now();
    while (Date.now() - startedAt < timeoutMs) {
      if (this.state.version > previousVersion) {
        return;
      }
      await sleep(20);
    }
    throw new Error("Timed out waiting for gameplay version change.");
  }

  async waitForBootstrap(timeoutMs = DEFAULT_TIMEOUT_MS): Promise<void> {
    await this.waitForVersionChange(-1, timeoutMs);
  }
}

function parseSeatView(raw: string | null | undefined): unknown {
  return raw ? parseJsonValue(raw) : null;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function formatIssuePath(
  label: string,
  path: ReadonlyArray<PropertyKey>,
): string {
  let formatted = label;
  for (const segment of path) {
    formatted +=
      typeof segment === "number" ? `[${segment}]` : `.${String(segment)}`;
  }
  return formatted;
}

function parseWirePayload<T>(
  methodName: string,
  value: unknown,
  label: string,
  schema: {
    safeParse: (input: unknown) =>
      | { success: true; data: T }
      | {
          success: false;
          error: {
            issues: Array<{
              path: Array<PropertyKey>;
              message: string;
            }>;
          };
        };
  },
): T {
  const parsed = schema.safeParse(value);
  if (parsed.success) {
    return parsed.data;
  }
  const firstIssue = parsed.error.issues[0];
  const formattedPath = formatIssuePath(label, firstIssue?.path ?? []);
  throw new Error(
    `Reducer bundle returned invalid payload for '${methodName}': ${formattedPath} ${firstIssue?.message ?? "failed schema validation"}.`,
  );
}

export function assertDispatchResultWireContract(
  result: unknown,
): Wire.DispatchResult {
  return parseWirePayload(
    "dispatch",
    result,
    "DispatchResult",
    ReducerContractZod.DispatchResultSchema,
  );
}

async function createBrowserBridgeClient(
  page: Page,
): Promise<BrowserBridgeClient> {
  const bridgeExists = async (): Promise<boolean> =>
    page.evaluate(() =>
      Boolean(
        (
          window as typeof window & {
            __dreamboardTestBridge__?: unknown;
          }
        ).__dreamboardTestBridge__,
      ),
    );

  const startedAt = Date.now();
  while (!(await bridgeExists())) {
    if (Date.now() - startedAt > DEFAULT_TIMEOUT_MS) {
      const bodyText = await page
        .locator("body")
        .innerText()
        .catch(() => "");
      const diagnostic = bodyText.trim().replace(/\s+/g, " ").slice(0, 400);
      throw new Error(
        diagnostic.length > 0
          ? `Timed out waiting for browser test bridge. Page text: ${diagnostic}`
          : "Timed out waiting for browser test bridge.",
      );
    }
    await sleep(50);
  }

  return {
    snapshot: () =>
      page.evaluate(() =>
        (
          window as typeof window & {
            __dreamboardTestBridge__: {
              snapshot: () => Promise<BrowserSnapshot>;
            };
          }
        ).__dreamboardTestBridge__.snapshot(),
      ),
    submitInteraction: (playerId, interactionId, params) =>
      page.evaluate(
        ([nextPlayerId, nextInteractionId, nextParams]) =>
          (
            window as typeof window & {
              __dreamboardTestBridge__: {
                submitInteraction: (
                  playerId: string,
                  interactionId: string,
                  params: unknown,
                ) => Promise<void>;
              };
            }
          ).__dreamboardTestBridge__.submitInteraction(
            nextPlayerId,
            nextInteractionId,
            nextParams,
          ),
        [playerId, interactionId, params] as const,
      ),
    waitForVersionChange: async (
      previousVersion,
      timeoutMs = DEFAULT_TIMEOUT_MS,
    ) => {
      const started = Date.now();
      while (Date.now() - started < timeoutMs) {
        const snapshot = await page.evaluate(() =>
          (
            window as typeof window & {
              __dreamboardTestBridge__: {
                snapshot: () => Promise<BrowserSnapshot>;
              };
            }
          ).__dreamboardTestBridge__.snapshot(),
        );
        if (snapshot.version > previousVersion) {
          return snapshot;
        }
        await sleep(50);
      }
      throw new Error("Timed out waiting for browser gameplay version change.");
    },
  };
}

async function assertLiveMatchesShadow(
  runner: TestRunnerName,
  shadow: ShadowReducerRuntime,
  live: GameplaySnapshot | BrowserSnapshot,
): Promise<void> {
  if (runner === "reducer") {
    return;
  }

  const currentPhase =
    "currentPhase" in live ? live.currentPhase : shadow.phase();
  if (currentPhase !== shadow.phase()) {
    throw new Error(
      `Live phase '${String(currentPhase)}' diverged from reducer phase '${shadow.phase()}'.`,
    );
  }

  const livePlayerId =
    "playerId" in live ? live.playerId : live.controllingPlayerId;
  const liveView = "view" in live ? live.view : null;
  if (livePlayerId && !deepEqual(liveView, await shadow.view(livePlayerId))) {
    throw new Error("Live projected views diverged from reducer shadow views.");
  }

  const liveInteractions =
    "availableInteractions" in live ? live.availableInteractions : null;
  if (
    livePlayerId &&
    liveInteractions &&
    !deepEqual(
      liveInteractions,
      shadow.availableInteractionsForPlayer(livePlayerId),
    )
  ) {
    throw new Error(
      "Live available-interactions metadata diverged from reducer shadow state.",
    );
  }
}

async function loadBrowserDriver(
  projectRoot: string,
): Promise<BrowserRunnerDriver | null> {
  const filePath = path.join(projectRoot, "test", "browser-driver.ts");
  if (!(await exists(filePath))) {
    return null;
  }
  const module = await importTypeScriptModule<BrowserDriverModule>(filePath);
  return module.default ?? module;
}

async function openBrowserPage(
  playUrl: string,
  config: ResolvedConfig,
): Promise<{
  browser: Browser;
  page: Page;
}> {
  configurePlaywrightBrowsersPath();
  const { chromium } = await import("playwright");
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
  });
  const initScript = await buildBrowserAuthInitScript(config);
  if (initScript) {
    await context.addInitScript({ content: initScript });
  }
  const page = await context.newPage();
  await page.goto(playUrl, { waitUntil: "domcontentloaded" });
  return { browser, page };
}

function sanitizeSnapshotSegment(value: string): string {
  return value.replace(/[^a-zA-Z0-9._-]+/g, "-");
}

function createScenarioSnapshotMatcher(options: {
  projectRoot: string;
  scenarioId: string;
  updateSnapshots: boolean;
}): (filename: string | undefined, actual: unknown) => void {
  return (filename, actual) => {
    const suffix = filename ? `.${sanitizeSnapshotSegment(filename)}` : "";
    const snapshotPath = path.join(
      options.projectRoot,
      "test",
      "generated",
      "snapshots",
      `${sanitizeSnapshotSegment(options.scenarioId)}${suffix}.snapshot.json`,
    );
    const wrappedValue = {
      value: actual,
    };
    const serialized = `${JSON.stringify(wrappedValue, null, 2)}\n`;

    mkdirSync(path.dirname(snapshotPath), { recursive: true });
    if (!existsSync(snapshotPath) || options.updateSnapshots) {
      writeFileSync(snapshotPath, serialized, "utf8");
      return;
    }

    const previous = JSON.parse(readFileSync(snapshotPath, "utf8")) as {
      value: unknown;
    };
    if (!deepEqual(previous.value, actual)) {
      throw new Error(
        `Snapshot mismatch for scenario '${options.scenarioId}'. Re-run with --update-snapshots to refresh ${path.relative(options.projectRoot, snapshotPath)}.`,
      );
    }
  };
}

async function createScenarioContext(options: {
  runner: TestRunnerName;
  shadow: ShadowReducerRuntime;
  expect: ExpectApi;
  live?:
    | {
        sessionId: string;
        version: number;
        actionSetVersion: string;
      }
    | undefined;
  embedded?:
    | {
        sessionId: string;
        tracker: EmbeddedGameplayTracker;
      }
    | undefined;
  browser?:
    | {
        bridge: BrowserBridgeClient;
        driver: BrowserRunnerDriver | null;
      }
    | undefined;
}): Promise<SharedScenarioContext> {
  const api: ScenarioGameApi = {
    start: async () => {
      await options.shadow.start();
      if (options.runner === "embedded" && options.embedded) {
        const live = options.embedded.tracker.snapshot();
        await assertLiveMatchesShadow("embedded", options.shadow, live);
      }
      if (options.runner === "browser" && options.browser) {
        const live = await options.browser.bridge.snapshot();
        await assertLiveMatchesShadow("browser", options.shadow, live);
      }
    },
    submit: async (playerId, interactionId, params) => {
      await api.start();
      const interactionParams = params ?? {};

      const previousVersion = options.live
        ? options.live.version
        : options.runner === "embedded"
          ? (options.embedded?.tracker.snapshot().version ?? 0)
          : options.runner === "browser"
            ? ((await options.browser?.bridge.snapshot())?.version ?? 0)
            : 0;

      if (options.live) {
        if (!options.live.actionSetVersion) {
          const { data } = await listPlayerActions({
            path: { sessionId: options.live.sessionId, playerId },
          });
          options.live.actionSetVersion = data?.actionSetVersion ?? "";
        }
        const { data, error } = await submitPlayerAction({
          path: {
            sessionId: options.live.sessionId,
            playerId,
            interactionId,
          },
          body: {
            expectedVersion: previousVersion,
            actionSetVersion: options.live.actionSetVersion,
            inputs:
              interactionParams &&
              typeof interactionParams === "object" &&
              !Array.isArray(interactionParams)
                ? (interactionParams as never)
                : {},
          },
        });
        if (error) {
          throw createSubmissionError(
            "api-error",
            undefined,
            "Failed to submit interaction",
          );
        }
        if (data?.accepted === false) {
          const shadowError = await tryShadowSubmit(
            options.shadow,
            playerId,
            interactionId,
            interactionParams,
          );
          if (!shadowError || shadowError.errorCode !== data.errorCode) {
            throw new Error(
              "Live session rejection diverged from reducer shadow state.",
            );
          }
          throw createSubmissionError(
            data.errorCode ?? undefined,
            data.message ?? undefined,
            "Interaction rejected",
          );
        }
        options.live.version =
          typeof data?.version === "number"
            ? data.version
            : previousVersion + 1;
        options.live.actionSetVersion =
          data?.actionSetVersion ?? options.live.actionSetVersion;
      } else if (options.runner === "embedded" && options.embedded) {
        const embeddedSnapshot = options.embedded.tracker.snapshot();
        const { data, error } = await submitPlayerAction({
          path: {
            sessionId: options.embedded.sessionId,
            playerId,
            interactionId,
          },
          body: {
            expectedVersion: previousVersion,
            actionSetVersion: embeddedSnapshot.actionSetVersion,
            inputs:
              interactionParams &&
              typeof interactionParams === "object" &&
              !Array.isArray(interactionParams)
                ? (interactionParams as never)
                : {},
          },
        });
        if (error) {
          throw createSubmissionError(
            "api-error",
            undefined,
            "Failed to submit interaction",
          );
        }
        if (data?.accepted === false) {
          const shadowError = await tryShadowSubmit(
            options.shadow,
            playerId,
            interactionId,
            interactionParams,
          );
          if (!shadowError || shadowError.errorCode !== data.errorCode) {
            throw new Error(
              "Embedded harness rejection diverged from reducer shadow state.",
            );
          }
          throw createSubmissionError(
            data.errorCode ?? undefined,
            data.message ?? undefined,
            "Interaction rejected",
          );
        }
      } else if (options.runner === "browser" && options.browser) {
        const handled =
          (await options.browser.driver?.interaction?.(options.browser.bridge, {
            playerId,
            interactionId,
            params: interactionParams,
          })) === true;
        if (!handled) {
          await options.browser.bridge.submitInteraction(
            playerId,
            interactionId,
            interactionParams,
          );
        }
      }

      await options.shadow.submitInteraction(
        playerId,
        interactionId,
        interactionParams,
      );

      if (options.runner === "embedded" && options.embedded) {
        await options.embedded.tracker.waitForVersionChange(previousVersion);
        await assertLiveMatchesShadow(
          "embedded",
          options.shadow,
          options.embedded.tracker.snapshot(),
        );
      }
      if (options.runner === "browser" && options.browser) {
        const live =
          await options.browser.bridge.waitForVersionChange(previousVersion);
        await assertLiveMatchesShadow("browser", options.shadow, live);
      }
    },
  };

  return {
    game: api,
    players: () => options.shadow.playerOrder(),
    seat: (index: number) => {
      const order = options.shadow.playerOrder();
      if (!Number.isInteger(index) || index < 0 || index >= order.length) {
        throw new Error(
          `seat(${index}) is out of range; scenario has ${order.length} player(s).`,
        );
      }
      return order[index]!;
    },
    state: () => options.shadow.phase(),
    view: (playerId) => options.shadow.view(playerId),
    interactions: (playerId) => options.shadow.interactionsForPlayer(playerId),
    expect: options.expect,
  };
}

async function tryShadowSubmit(
  shadow: ShadowReducerRuntime,
  playerId: string,
  interactionId: string,
  params: Record<string, unknown>,
): Promise<SubmissionError | null> {
  try {
    await shadow.submitInteraction(playerId, interactionId, params);
    throw new Error("Expected shadow interaction to reject.");
  } catch (error) {
    if (
      error instanceof Error &&
      (error as SubmissionError).name === "SubmissionError"
    ) {
      return error as SubmissionError;
    }
    throw error;
  }
}

export async function createSessionFromScenario(options: {
  projectRoot: string;
  scenarioId: string;
  compiledResultId: string;
  gameId: string;
  debug?: boolean;
}): Promise<SeededScenarioSession> {
  await ensureReducerNativeTestingFiles(options.projectRoot);

  const [
    bases,
    scenarios,
    generatedBaseStates,
    manifest,
    gameModule,
    manifestContractModule,
  ] = await Promise.all([
    loadTypedBases(options.projectRoot),
    loadTypedScenarios(options.projectRoot, {}),
    loadGeneratedBaseStates(options.projectRoot),
    loadManifest(options.projectRoot),
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "app", "game.ts"),
    ),
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "shared", "manifest-contract.ts"),
    ),
  ]);

  const matchingScenarios = scenarios.filter(
    (scenario) => scenario.definition.id === options.scenarioId,
  );
  if (matchingScenarios.length === 0) {
    throw new Error(
      `Unknown scenario '${options.scenarioId}'. Available scenarios: ${scenarios
        .map((scenario) => scenario.definition.id)
        .sort()
        .join(", ")}`,
    );
  }
  if (matchingScenarios.length > 1) {
    throw new Error(
      `Scenario id '${options.scenarioId}' is defined more than once. Keep one scenario per file and one unique id per workspace.`,
    );
  }

  const scenario = matchingScenarios[0]!;
  const basesById = new Map(bases.map((base) => [base.definition.id, base]));
  validateTypedScenarioBases([scenario], basesById);
  const base = basesById.get(scenario.definition.from);
  if (!base) {
    throw new Error(
      `Missing typed base '${scenario.definition.from}' for scenario '${scenario.definition.id}'.`,
    );
  }

  const generatedBase = generatedBaseStates?.[baseStateKey(base.definition.id)];
  if (!generatedBase) {
    throw new Error(
      `Missing generated base artifact for '${base.definition.id}'. Run 'dreamboard test generate' before using --from-scenario.`,
    );
  }

  validateGeneratedFingerprint({
    generated: generatedBase.fingerprint,
    current: await currentFingerprint({
      projectRoot: options.projectRoot,
      base,
      basesById,
      compiledResultId: options.compiledResultId,
      gameId: options.gameId,
    }),
  });

  const createInitialTable =
    typeof manifestContractModule.createInitialTable === "function"
      ? (manifestContractModule.createInitialTable as GeneratedInitialTableFactory)
      : null;
  const resolvedBase = resolveBaseDefinition(base, basesById);
  const effectiveSetup = resolveEffectiveBaseSetup({
    manifest,
    base: base.definition,
    basesById,
  });
  const shadow = new ShadowReducerRuntime(
    manifest,
    gameModule.default,
    createInitialTable,
    resolvedBase.seed,
    resolvedBase.players,
    effectiveSetup.setupProfileId,
    options.debug ?? false,
  );
  if (base.definition.extends) {
    const parentArtifact =
      generatedBaseStates?.[baseStateKey(base.definition.extends)];
    if (!parentArtifact) {
      throw new Error(
        `Base '${base.definition.id}' extends '${base.definition.extends}', but the parent artifact is missing. Run 'dreamboard test generate' first.`,
      );
    }
    shadow.hydrate(parentArtifact.snapshot);
  }

  const { data: session, error: sessionError } = await createSession({
    path: { gameId: options.gameId },
    body: {
      compiledResultId: options.compiledResultId,
      seed: resolvedBase.seed,
      playerCount: resolvedBase.players,
      autoAssignSeats: true,
      setupProfileId: effectiveSetup.setupProfileId ?? undefined,
    },
  });
  if (!session || sessionError) {
    throw new Error(
      `Failed to create seeded scenario session for '${scenario.definition.id}'.`,
    );
  }

  const { error: startError } = await startGame({
    path: { sessionId: session.sessionId },
  });
  if (startError) {
    throw new Error(
      `Failed to start seeded scenario session for '${scenario.definition.id}'.`,
    );
  }

  const context = await createScenarioContext({
    runner: "reducer",
    shadow,
    expect: (await loadTestingExpectApiFactory())(),
    live: {
      sessionId: session.sessionId,
      version: 0,
      actionSetVersion: "",
    },
  });

  await context.game.start();
  await base.definition.setup({
    game: context.game,
    players: context.players,
    seat: context.seat,
  });
  shadow.clearHistory();
  await scenario.definition.when(context);
  if (
    scenario.definition.phase &&
    shadow.phase() !== scenario.definition.phase
  ) {
    throw new Error(
      `Scenario '${scenario.definition.id}' expected phase '${scenario.definition.phase}' but reached '${shadow.phase()}'.`,
    );
  }
  if (
    scenario.definition.stage &&
    shadow.currentStage() !== scenario.definition.stage
  ) {
    throw new Error(
      `Scenario '${scenario.definition.id}' expected stage '${scenario.definition.stage}' but reached '${
        shadow.currentStage() ?? "null"
      }'.`,
    );
  }

  return {
    sessionId: session.sessionId,
    shortCode: session.shortCode,
    gameId: session.gameId,
    seed: resolvedBase.seed,
    playerCount: resolvedBase.players,
    setupProfileId: effectiveSetup.setupProfileId,
    scenarioId: scenario.definition.id,
    phase: shadow.phase(),
    stage: shadow.currentStage(),
  };
}

function baseStateKey(baseId: string): string {
  return baseId;
}

function fingerprintHash(
  fingerprint: BaseStateArtifact["fingerprint"],
): string {
  return hashContent(JSON.stringify(fingerprint));
}

function sortBasesForArtifacts(
  bases: LoadedBase[],
  basesById: Map<string, LoadedBase>,
): LoadedBase[] {
  const ordered: LoadedBase[] = [];
  const visiting = new Set<string>();
  const visited = new Set<string>();

  const visit = (base: LoadedBase) => {
    if (visited.has(base.definition.id)) {
      return;
    }
    if (visiting.has(base.definition.id)) {
      throw new Error(
        `Cyclic reducer-native base inheritance detected at '${base.definition.id}'.`,
      );
    }
    visiting.add(base.definition.id);
    if (base.definition.extends) {
      const parent = basesById.get(base.definition.extends);
      if (!parent) {
        throw new Error(
          `Base '${base.definition.id}' extends unknown parent '${base.definition.extends}'.`,
        );
      }
      visit(parent);
    }
    visiting.delete(base.definition.id);
    visited.add(base.definition.id);
    ordered.push(base);
  };

  for (const base of bases) {
    visit(base);
  }

  return ordered;
}

function writeProjectionSnapshots(options: {
  projectRoot: string;
  baseId: string;
  shadow: ShadowReducerRuntime;
}): void {
  const projectionDir = path.join(
    options.projectRoot,
    "test",
    "generated",
    "bases",
    options.baseId,
  );
  rmSync(projectionDir, { recursive: true, force: true });
  mkdirSync(projectionDir, { recursive: true });
  const projection = options.shadow.projectAllSeats();
  for (const [playerId, seatProjection] of Object.entries(projection.seats)) {
    const outputPath = path.join(projectionDir, `${playerId}.projection.json`);
    writeFileSync(
      outputPath,
      `${JSON.stringify(
        {
          currentStage: projection.currentStage,
          stageSeats: projection.stageSeats,
          ...seatProjection,
        },
        null,
        2,
      )}\n`,
      "utf8",
    );
  }
}

function validateTypedScenarioBases(
  scenarios: LoadedScenario[],
  basesById: Map<string, LoadedBase>,
): void {
  const available = new Set(basesById.keys());
  const invalid = scenarios
    .filter((scenario) => !available.has(scenario.definition.from))
    .map(
      (scenario) =>
        path.relative(process.cwd(), scenario.filePath) +
        ` -> '${scenario.definition.from}'`,
    );

  if (invalid.length > 0) {
    throw new Error(
      `Unknown scenario base(s): ${invalid.join(", ")}. Available bases: ${Array.from(available).sort().join(", ")}`,
    );
  }
}

export async function writeReducerNativeGeneratedFiles(options: {
  projectRoot: string;
  bases: LoadedBase[];
  scenarios: LoadedScenario[];
  compiledResultId?: string;
  gameId?: string;
  debug?: boolean;
}): Promise<void> {
  await ensureReducerNativeTestingFiles(options.projectRoot);

  const manifest = await loadManifest(options.projectRoot);
  const manifestHash = hashContent(JSON.stringify(manifest));
  const appBundleHash = hashContent(
    await bundleTypeScriptModuleText(
      path.join(options.projectRoot, "app", "game.ts"),
    ),
  );
  const uiContractHash = hashContent(
    await bundleTypeScriptModuleText(
      path.join(options.projectRoot, "shared", "generated", "ui-contract.ts"),
    ),
  );

  const generatedDir = path.join(options.projectRoot, "test", "generated");
  await ensureDir(generatedDir);
  const baseStates: BaseStateFile = {};
  const [gameModule, manifestContractModule] = await Promise.all([
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "app", "game.ts"),
    ),
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "shared", "manifest-contract.ts"),
    ),
  ]);
  const createInitialTable =
    typeof manifestContractModule.createInitialTable === "function"
      ? (manifestContractModule.createInitialTable as GeneratedInitialTableFactory)
      : null;
  const basesById = new Map(
    options.bases.map((base) => [base.definition.id, base]),
  );
  for (const base of sortBasesForArtifacts(options.bases, basesById)) {
    const resolvedBase = resolveBaseDefinition(base, basesById);
    const effectiveSetup = resolveEffectiveBaseSetup({
      manifest,
      base: base.definition,
      basesById,
    });
    const shadow = new ShadowReducerRuntime(
      manifest,
      gameModule.default,
      createInitialTable,
      resolvedBase.seed,
      resolvedBase.players,
      effectiveSetup.setupProfileId,
      options.debug ?? false,
    );
    let parentFingerprintHash: string | null = null;
    if (base.definition.extends) {
      const parentArtifact = baseStates[baseStateKey(base.definition.extends)];
      if (!parentArtifact) {
        throw new Error(
          `Base '${base.definition.id}' extends '${base.definition.extends}', but the parent artifact does not exist yet.`,
        );
      }
      if (parentArtifact.fingerprint.seed !== resolvedBase.seed) {
        throw new Error(
          `Base '${base.definition.id}' extends '${base.definition.extends}' but changes seed from ${parentArtifact.fingerprint.seed} to ${resolvedBase.seed}.`,
        );
      }
      if (parentArtifact.fingerprint.players !== resolvedBase.players) {
        throw new Error(
          `Base '${base.definition.id}' extends '${base.definition.extends}' but changes players from ${parentArtifact.fingerprint.players} to ${resolvedBase.players}.`,
        );
      }
      if (
        (parentArtifact.fingerprint.setupProfileId ?? null) !==
        (effectiveSetup.setupProfileId ?? null)
      ) {
        throw new Error(
          `Base '${base.definition.id}' extends '${base.definition.extends}' but changes setup profile from ${
            parentArtifact.fingerprint.setupProfileId ?? "none"
          } to ${effectiveSetup.setupProfileId ?? "none"}.`,
        );
      }
      parentFingerprintHash = fingerprintHash(parentArtifact.fingerprint);
      shadow.hydrate(parentArtifact.snapshot);
    }
    const context = await createScenarioContext({
      runner: "reducer",
      shadow,
      expect: (await loadTestingExpectApiFactory())(),
    });
    await context.game.start();
    await base.definition.setup({
      game: context.game,
      players: context.players,
      seat: context.seat,
    });
    baseStates[baseStateKey(base.definition.id)] = {
      key: baseStateKey(base.definition.id),
      base: base.definition.id,
      snapshot: shadow.rawState(),
      fingerprint: {
        base: base.definition.id,
        seed: resolvedBase.seed,
        players: resolvedBase.players,
        baseBundleHash: base.bundleHash,
        manifestHash,
        appBundleHash,
        uiContractHash,
        setupProfileId: effectiveSetup.setupProfileId,
        compiledResultId: options.compiledResultId,
        gameId: options.gameId,
        parentBaseId: base.definition.extends ?? null,
        parentFingerprintHash,
      },
    };
    writeProjectionSnapshots({
      projectRoot: options.projectRoot,
      baseId: base.definition.id,
      shadow,
    });
  }

  const header =
    "// Generated by dreamboard test generate. Do not edit by hand.\n";
  await writeTextFile(
    path.join(generatedDir, "base-states.generated.ts"),
    `${header}export const BASE_STATES = ${JSON.stringify(baseStates, null, 2)} as const;\n`,
  );
  await writeTextFile(
    path.join(generatedDir, "base-states.generated.d.ts"),
    `${header}export declare const BASE_STATES: Record<string, unknown>;\n`,
  );
  await writeTextFile(
    path.join(generatedDir, "scenario-manifest.generated.ts"),
    `${header}export const SCENARIO_MANIFEST = ${JSON.stringify(
      options.scenarios.map((scenario) => ({
        id: scenario.definition.id,
        filePath: path.relative(generatedDir, scenario.filePath),
        base: scenario.definition.from,
        runners: normalizeScenarioRunners(scenario.definition.runners),
      })),
      null,
      2,
    )} as const;\n`,
  );
  await writeJsonFile(path.join(generatedDir, ".generation-meta.json"), {
    generatedAt: new Date().toISOString(),
    scenarioCount: options.scenarios.length,
    baseStateCount: options.bases.length,
  });
}

async function loadGeneratedBaseStates(
  projectRoot: string,
): Promise<BaseStateFile | null> {
  const filePath = path.join(
    projectRoot,
    "test",
    "generated",
    "base-states.generated.ts",
  );
  if (!(await exists(filePath))) {
    return null;
  }
  const module =
    await importTypeScriptModule<Record<string, unknown>>(filePath);
  return (module.BASE_STATES as BaseStateFile | undefined) ?? null;
}

function validateGeneratedFingerprint(options: {
  generated: BaseStateArtifact["fingerprint"];
  current: BaseStateArtifact["fingerprint"];
}): void {
  const mismatches: string[] = [];
  if (options.generated.baseBundleHash !== options.current.baseBundleHash) {
    mismatches.push("base module changed");
  }
  if (options.generated.manifestHash !== options.current.manifestHash) {
    mismatches.push("manifest changed");
  }
  if (options.generated.appBundleHash !== options.current.appBundleHash) {
    mismatches.push("game reducer bundle changed");
  }
  if (options.generated.uiContractHash !== options.current.uiContractHash) {
    mismatches.push("ui contract changed");
  }
  if (
    options.generated.compiledResultId &&
    options.current.compiledResultId &&
    options.generated.compiledResultId !== options.current.compiledResultId
  ) {
    mismatches.push("compiled result changed");
  }
  if (
    options.generated.gameId &&
    options.current.gameId &&
    options.generated.gameId !== options.current.gameId
  ) {
    mismatches.push("game id changed");
  }
  if (
    options.generated.seed !== options.current.seed ||
    options.generated.players !== options.current.players
  ) {
    mismatches.push("base seed/player count changed");
  }
  if (
    (options.generated.setupProfileId ?? null) !==
    (options.current.setupProfileId ?? null)
  ) {
    mismatches.push("base setup profile changed");
  }
  if (
    (options.generated.parentBaseId ?? null) !==
    (options.current.parentBaseId ?? null)
  ) {
    mismatches.push("base parent changed");
  }
  if (
    (options.generated.parentFingerprintHash ?? null) !==
    (options.current.parentFingerprintHash ?? null)
  ) {
    mismatches.push("parent base artifact changed");
  }
  if (mismatches.length > 0) {
    throw new Error(
      `${mismatches.join("; ")}. Run 'dreamboard test generate' to refresh reducer-native base artifacts.`,
    );
  }
}

async function currentFingerprint(options: {
  projectRoot: string;
  base: LoadedBase;
  basesById?: Map<string, LoadedBase>;
  compiledResultId?: string;
  gameId?: string;
}): Promise<BaseStateArtifact["fingerprint"]> {
  const manifest = await loadManifest(options.projectRoot);
  const resolvedBase = resolveBaseDefinition(
    options.base,
    options.basesById ?? new Map([[options.base.definition.id, options.base]]),
  );
  const effectiveSetup = resolveEffectiveBaseSetup({
    manifest,
    base: options.base.definition,
    basesById: options.basesById,
  });
  let parentFingerprintHash: string | null = null;
  if (options.base.definition.extends) {
    const parentBase = options.basesById?.get(options.base.definition.extends);
    if (!parentBase) {
      throw new Error(
        `Base '${options.base.definition.id}' extends unknown parent '${options.base.definition.extends}'.`,
      );
    }
    parentFingerprintHash = fingerprintHash(
      await currentFingerprint({
        projectRoot: options.projectRoot,
        base: parentBase,
        basesById: options.basesById,
        compiledResultId: options.compiledResultId,
        gameId: options.gameId,
      }),
    );
  }
  return {
    base: options.base.definition.id,
    seed: resolvedBase.seed,
    players: resolvedBase.players,
    baseBundleHash: options.base.bundleHash,
    manifestHash: hashContent(JSON.stringify(manifest)),
    appBundleHash: hashContent(
      await bundleTypeScriptModuleText(
        path.join(options.projectRoot, "app", "game.ts"),
      ),
    ),
    uiContractHash: hashContent(
      await bundleTypeScriptModuleText(
        path.join(options.projectRoot, "shared", "generated", "ui-contract.ts"),
      ),
    ),
    setupProfileId: effectiveSetup.setupProfileId,
    compiledResultId: options.compiledResultId,
    gameId: options.gameId,
    parentBaseId: options.base.definition.extends ?? null,
    parentFingerprintHash,
  };
}

export async function generateReducerNativeArtifacts(options: {
  projectRoot: string;
  compiledResultId?: string;
  gameId?: string;
  scenarioPath?: string;
  debug?: boolean;
}): Promise<{
  bases: LoadedBase[];
  scenarios: LoadedScenario[];
}> {
  await ensureReducerNativeTestingFiles(options.projectRoot);
  const [bases, scenarios] = await Promise.all([
    loadTypedBases(options.projectRoot),
    loadTypedScenarios(options.projectRoot, {
      scenarioPath: options.scenarioPath,
    }),
  ]);
  const basesById = new Map(bases.map((base) => [base.definition.id, base]));
  validateTypedScenarioBases(scenarios, basesById);
  await writeReducerNativeGeneratedFiles({
    projectRoot: options.projectRoot,
    bases,
    scenarios,
    compiledResultId: options.compiledResultId,
    gameId: options.gameId,
    debug: options.debug,
  });
  return { bases, scenarios };
}

export async function runReducerNativeScenarios(options: {
  projectRoot: string;
  projectConfig: ProjectConfig;
  resolvedConfig: ResolvedConfig;
  runner: TestRunnerName;
  scenarioPath?: string;
  compiledResultId?: string;
  gameId?: string;
  webBaseUrl?: string;
  debug?: boolean;
  updateSnapshots?: boolean;
}): Promise<ReducerNativeScenarioSummary> {
  await ensureReducerNativeTestingFiles(options.projectRoot);

  const [
    bases,
    scenarios,
    initialGeneratedBaseStates,
    manifest,
    gameModule,
    manifestContractModule,
  ] = await Promise.all([
    loadTypedBases(options.projectRoot),
    loadTypedScenarios(options.projectRoot, {
      scenarioPath: options.scenarioPath,
    }),
    loadGeneratedBaseStates(options.projectRoot),
    loadManifest(options.projectRoot),
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "app", "game.ts"),
    ),
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "shared", "manifest-contract.ts"),
    ),
  ]);
  let generatedBaseStates = initialGeneratedBaseStates;
  const createInitialTable =
    typeof manifestContractModule.createInitialTable === "function"
      ? (manifestContractModule.createInitialTable as GeneratedInitialTableFactory)
      : null;

  const basesById = new Map(bases.map((base) => [base.definition.id, base]));
  validateTypedScenarioBases(scenarios, basesById);

  if (options.updateSnapshots) {
    await writeReducerNativeGeneratedFiles({
      projectRoot: options.projectRoot,
      bases,
      scenarios,
      compiledResultId: options.compiledResultId,
      gameId: options.gameId,
      debug: options.debug,
    });
    generatedBaseStates = await loadGeneratedBaseStates(options.projectRoot);
  }

  const runnerScenarios = scenarios.filter((scenario) =>
    normalizeScenarioRunners(scenario.definition.runners).includes(
      options.runner,
    ),
  );

  let embeddedHarness: EmbeddedHarnessSession | null = null;
  let browser: Browser | null = null;
  let page: Page | null = null;
  let browserBridge: BrowserBridgeClient | null = null;
  let browserDriver: BrowserRunnerDriver | null = null;

  if (options.runner === "embedded") {
    embeddedHarness = await startEmbeddedHarnessSession({
      projectRoot: options.projectRoot,
      projectConfig: options.projectConfig,
      configureClient: true,
    });
  }

  if (options.runner === "browser") {
    const webBaseUrl = options.webBaseUrl ?? options.projectConfig.webBaseUrl;
    if (!webBaseUrl) {
      throw new Error(
        "Browser runner requires a local webBaseUrl. Start the local web stack and configure the project for env local.",
      );
    }
    browserDriver = await loadBrowserDriver(options.projectRoot);
    const opened = await openBrowserPage(
      `${webBaseUrl}/_dev`,
      options.resolvedConfig,
    );
    browser = opened.browser;
    page = opened.page;
  }

  try {
    let passed = 0;
    let failed = 0;
    const results: ReducerNativeScenarioResult[] = [];

    for (const scenario of runnerScenarios) {
      const base = basesById.get(scenario.definition.from);
      if (!base) {
        throw new Error(
          `Missing typed base '${scenario.definition.from}' for scenario '${scenario.definition.id}'.`,
        );
      }

      if (generatedBaseStates?.[baseStateKey(base.definition.id)]) {
        validateGeneratedFingerprint({
          generated:
            generatedBaseStates[baseStateKey(base.definition.id)]!.fingerprint,
          current: await currentFingerprint({
            projectRoot: options.projectRoot,
            base,
            basesById,
            compiledResultId: options.compiledResultId,
            gameId: options.gameId,
          }),
        });
      } else if (options.runner !== "reducer") {
        throw new Error(
          "Missing reducer-native generated base artifacts. Run 'dreamboard test generate' first.",
        );
      }

      try {
        const resolvedBase = resolveBaseDefinition(base, basesById);
        const effectiveSetup = resolveEffectiveBaseSetup({
          manifest,
          base: base.definition,
          basesById,
        });
        const shadow = new ShadowReducerRuntime(
          manifest,
          gameModule.default,
          createInitialTable,
          resolvedBase.seed,
          resolvedBase.players,
          effectiveSetup.setupProfileId,
          options.debug ?? false,
        );
        if (base.definition.extends) {
          const parentArtifact =
            generatedBaseStates?.[baseStateKey(base.definition.extends)];
          if (!parentArtifact) {
            throw new Error(
              `Base '${base.definition.id}' extends '${base.definition.extends}', but the parent artifact is missing. Run 'dreamboard test generate' first.`,
            );
          }
          shadow.hydrate(parentArtifact.snapshot);
        }

        let embedded:
          | {
              sessionId: string;
              tracker: EmbeddedGameplayTracker;
            }
          | undefined;
        try {
          if (options.runner === "embedded" && embeddedHarness) {
            const { data: session, error: sessionError } = await createSession({
              path: { gameId: embeddedHarness.gameId },
              body: {
                compiledResultId: embeddedHarness.compiledResultId,
                seed: resolvedBase.seed,
                playerCount: resolvedBase.players,
                autoAssignSeats: true,
                setupProfileId: effectiveSetup.setupProfileId ?? undefined,
              },
            });
            if (!session || sessionError) {
              throw new Error("Failed to create embedded harness session.");
            }
            const tracker = new EmbeddedGameplayTracker(
              session.sessionId,
              "player-1",
            );
            const { error: startError } = await startGame({
              path: { sessionId: session.sessionId },
            });
            if (startError) {
              throw new Error("Failed to start embedded harness session.");
            }
            await tracker.connect();
            await tracker.waitForBootstrap();
            embedded = {
              sessionId: session.sessionId,
              tracker,
            };
          }

          if (options.runner === "browser" && page) {
            const gameId = options.gameId ?? options.projectConfig.gameId;
            const compiledResultId =
              options.compiledResultId ??
              options.projectConfig.compile?.latestSuccessful?.resultId;
            if (!compiledResultId) {
              throw new Error(
                "Browser runner requires a compiled result. Compile the workspace first.",
              );
            }
            const { data: session, error: sessionError } = await createSession({
              path: { gameId },
              body: {
                compiledResultId,
                seed: resolvedBase.seed,
                playerCount: resolvedBase.players,
                autoAssignSeats: true,
                setupProfileId: effectiveSetup.setupProfileId ?? undefined,
              },
            });
            if (!session || sessionError) {
              throw new Error("Failed to create browser-runner session.");
            }
            const { error: startError, data: started } = await startGame({
              path: { sessionId: session.sessionId },
            });
            if (startError || !started) {
              throw new Error("Failed to start browser-runner session.");
            }
            await page.goto(
              `${options.webBaseUrl ?? options.projectConfig.webBaseUrl}/_dev/play/${started.session.shortCode}`,
              { waitUntil: "domcontentloaded" },
            );
            await waitForGameReady(page);
            browserBridge = await createBrowserBridgeClient(page);
            await browserDriver?.onReady?.(browserBridge);
          }

          const context = await createScenarioContext({
            runner: options.runner,
            shadow,
            expect: (await loadTestingExpectApiFactory())({
              matchSnapshot: createScenarioSnapshotMatcher({
                projectRoot: options.projectRoot,
                scenarioId: scenario.definition.id,
                updateSnapshots: options.updateSnapshots ?? false,
              }),
            }),
            embedded,
            browser:
              options.runner === "browser" && browserBridge
                ? {
                    bridge: browserBridge,
                    driver: browserDriver,
                  }
                : undefined,
          });

          await context.game.start();
          await base.definition.setup({
            game: context.game,
            players: context.players,
            seat: context.seat,
          });
          shadow.clearHistory();
          await scenario.definition.when(context);
          if (
            scenario.definition.phase &&
            shadow.phase() !== scenario.definition.phase
          ) {
            throw new Error(
              `Scenario '${scenario.definition.id}' expected phase '${scenario.definition.phase}' but reached '${shadow.phase()}'.`,
            );
          }
          if (
            scenario.definition.stage &&
            shadow.currentStage() !== scenario.definition.stage
          ) {
            throw new Error(
              `Scenario '${scenario.definition.id}' expected stage '${scenario.definition.stage}' but reached '${
                shadow.currentStage() ?? "null"
              }'.`,
            );
          }
          await scenario.definition.then(context);
          passed += 1;
          results.push({
            id: scenario.definition.id,
            success: true,
          });
        } finally {
          embedded?.tracker.close();
        }
      } catch (error) {
        failed += 1;
        results.push({
          id: scenario.definition.id,
          success: false,
          error:
            error instanceof Error
              ? error.message
              : `Scenario '${scenario.definition.id}' failed.`,
        });
      }
    }

    return { passed, failed, results };
  } finally {
    if (embeddedHarness) {
      await embeddedHarness.stop();
    }
    if (browser) {
      await browser.close();
    }
  }
}
