import path from "node:path";
import { readdir } from "node:fs/promises";
import type { Browser, Page } from "playwright";
import type { GameTopologyManifest } from "@dreamboard/sdk-types";
import {
  createSession,
  startGame,
  submitInput,
  type GameMessage,
} from "@dreamboard/api-client";
import { createReducerBundle } from "@dreamboard/app-sdk";
import { materializeManifestTable } from "@dreamboard/workspace-codegen";
import type { ProjectConfig, ResolvedConfig } from "../../types.js";
import {
  ensureDir,
  exists,
  readTextFileIfExists,
  writeJsonFile,
  writeTextFile,
} from "../../utils/fs.js";
import {
  importTypeScriptModule,
  bundleTypeScriptModuleText,
} from "../../utils/ts-module-loader.js";
import { hashContent } from "../../utils/crypto.js";
import { loadManifest } from "../project/local-files.js";
import {
  REDUCER_TESTING_CONTRACT_CONTENT,
  REDUCER_TESTING_TYPES_WRAPPER_CONTENT,
} from "../../templates/testing-types-content.js";
import {
  startEmbeddedHarnessSession,
  type EmbeddedHarnessSession,
} from "./embedded-harness.js";
import { subscribeToCliSessionEvents } from "../../utils/session-event-stream.js";
import {
  buildBrowserAuthInitScript,
  configurePlaywrightBrowsersPath,
  waitForGameReady,
} from "../../ui/playwright-runner.js";
import { resolveSetupProfileSelection } from "../workflows/resolve-setup-profile.js";

const GENERATED_TESTING_TYPES_PREFIX = "// Generated by dreamboard";
const TESTING_TYPES_STUB =
  "export function defineScenario(scenario) { return scenario; }\n";
const DEFAULT_TIMEOUT_MS = 10_000;
const BASE_SUFFIX = ".base.ts";
const SCENARIO_SUFFIX = ".scenario.ts";

type TestRunnerName = "reducer" | "embedded" | "browser";

type TypedBaseDefinition = {
  id: string;
  seed: number;
  players: number;
  setupProfileId?: string;
  setup: (ctx: { game: ScenarioGameApi }) => void | Promise<void>;
};

type TypedScenarioDefinition = {
  id: string;
  description?: string;
  from: string;
  runners?: readonly TestRunnerName[];
  when: (ctx: SharedScenarioContext) => void | Promise<void>;
  then: (ctx: SharedScenarioContext) => void | Promise<void>;
};

type LoadedBase = {
  filePath: string;
  definition: TypedBaseDefinition;
  bundleHash: string;
};

type LoadedScenario = {
  filePath: string;
  definition: TypedScenarioDefinition;
  bundleHash: string;
};

type ExpectMatchers = {
  toBe: (expected: unknown) => void;
  toEqual: (expected: unknown) => void;
  toBeDefined: () => void;
  toBeUndefined: () => void;
  toBeNull: () => void;
  toContain: (expected: unknown) => void;
  toBeGreaterThanOrEqual: (expected: number) => void;
};

type ExpectApi = (actual: unknown) => ExpectMatchers;

type HistoryInput =
  | {
      kind: "action";
      playerId: string;
      actionType: string;
      params: Record<string, unknown>;
    }
  | {
      kind: "promptResponse";
      playerId: string;
      promptId: string;
      response: unknown;
    }
  | {
      kind: "windowAction";
      playerId: string;
      windowId: string;
      actionType: string;
      params: Record<string, unknown>;
    };

type HistoryRecord = {
  input: HistoryInput;
  accepted: boolean;
  errorCode?: string;
  message?: string;
};

type BaseStateArtifact = {
  key: string;
  base: string;
  snapshot: Record<string, unknown>;
  fingerprint: {
    base: string;
    seed: number;
    players: number;
    baseBundleHash: string;
    manifestHash: string;
    appBundleHash: string;
    uiContractHash: string;
    setupProfileId?: string | null;
    compiledResultId?: string;
    gameId?: string;
  };
};

type BaseStateFile = Record<string, BaseStateArtifact>;

type SharedScenarioContext = {
  game: ScenarioGameApi;
  players: () => readonly string[];
  state: () => string;
  view: (playerId: string) => unknown;
  prompts: (playerId: string) => readonly Record<string, unknown>[];
  windows: (playerId: string) => readonly Record<string, unknown>[];
  expect: ExpectApi;
};

type ScenarioGameApi = {
  start: () => Promise<void>;
  action: (
    playerId: string,
    actionOrCommand:
      | string
      | { type: string; params?: Record<string, unknown> },
    params?: Record<string, unknown>,
  ) => Promise<void>;
  respond: (
    playerId: string,
    promptOrId: string | { id: string; promptId?: string },
    response: unknown,
  ) => Promise<void>;
  windowAction: (
    playerId: string,
    windowOrId: string | { id: string; windowId?: string },
    actionOrCommand:
      | string
      | {
          type: string;
          params?: Record<string, unknown>;
        },
    params?: Record<string, unknown>,
  ) => Promise<void>;
  expectPrompt: (
    playerId: string,
    promptId: string,
  ) => Promise<Record<string, unknown>>;
  expectWindow: (windowId: string) => Promise<Record<string, unknown>>;
};

type SubmissionError = Error & { errorCode?: string };

type BrowserDriverModule = {
  default?: BrowserRunnerDriver;
} & Partial<BrowserRunnerDriver>;

type BrowserRunnerDriver = {
  onReady?: (bridge: BrowserBridgeClient) => Promise<void> | void;
  action?: (
    bridge: BrowserBridgeClient,
    input: {
      playerId: string;
      actionType: string;
      params: Record<string, unknown>;
    },
  ) => Promise<boolean | void> | boolean | void;
  promptResponse?: (
    bridge: BrowserBridgeClient,
    input: { playerId: string; promptId: string; response: unknown },
  ) => Promise<boolean | void> | boolean | void;
  windowAction?: (
    bridge: BrowserBridgeClient,
    input: {
      playerId: string;
      windowId: string;
      actionType: string;
      params: Record<string, unknown>;
    },
  ) => Promise<boolean | void> | boolean | void;
};

type BrowserSnapshot = {
  sessionId: string | null;
  shortCode: string | null;
  version: number;
  currentPhase: string | null;
  controllingPlayerId: string;
  controllablePlayerIds: string[];
  seatViewsByPlayerId: Record<string, unknown>;
  availableActionsByPlayerId?: Record<string, string[]>;
  prompts: Array<Record<string, unknown>>;
  windows: Array<Record<string, unknown>>;
};

export type ReducerNativeScenarioResult = {
  id: string;
  success: boolean;
  error?: string;
};

export type ReducerNativeScenarioSummary = {
  passed: number;
  failed: number;
  results: ReducerNativeScenarioResult[];
};

type BrowserBridgeClient = {
  snapshot: () => Promise<BrowserSnapshot>;
  submitAction: (
    playerId: string,
    actionType: string,
    params: Record<string, unknown>,
  ) => Promise<void>;
  submitPromptResponse: (
    playerId: string,
    promptId: string,
    response: unknown,
  ) => Promise<void>;
  submitWindowAction: (
    playerId: string,
    windowId: string,
    actionType: string,
    params: Record<string, unknown>,
  ) => Promise<void>;
  waitForVersionChange: (
    previousVersion: number,
    timeoutMs?: number,
  ) => Promise<BrowserSnapshot>;
};

type GameplaySnapshot = {
  version: number;
  currentPhase: string | null;
  seatViewsByPlayerId: Record<string, unknown>;
  availableActionsByPlayerId: Record<string, string[]>;
  prompts: Array<Record<string, unknown>>;
  windows: Array<Record<string, unknown>>;
};

function createSubmissionError(
  errorCode: string | undefined,
  message: string | undefined,
  fallbackMessage: string,
): SubmissionError {
  const error = new Error(message ?? fallbackMessage) as SubmissionError;
  error.name = "SubmissionError";
  error.errorCode = errorCode;
  return error;
}

function parseJsonValue(value: unknown): unknown {
  if (typeof value !== "string") {
    return value;
  }
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}

function createExpectApi(): ExpectApi {
  return (actual: unknown) => ({
    toBe: (expected: unknown) => {
      if (actual !== expected) {
        throw new Error(
          `Expected '${String(actual)}' to be '${String(expected)}'.`,
        );
      }
    },
    toEqual: (expected: unknown) => {
      if (!deepEqual(actual, expected)) {
        throw new Error("Expected values to be deeply equal.");
      }
    },
    toBeDefined: () => {
      if (actual === undefined) {
        throw new Error("Expected value to be defined.");
      }
    },
    toBeUndefined: () => {
      if (actual !== undefined) {
        throw new Error(
          `Expected value to be undefined, but received '${String(actual)}'.`,
        );
      }
    },
    toBeNull: () => {
      if (actual !== null) {
        throw new Error(
          `Expected value to be null, but received '${String(actual)}'.`,
        );
      }
    },
    toContain: (expected: unknown) => {
      if (Array.isArray(actual)) {
        if (!actual.some((item) => deepEqual(item, expected))) {
          throw new Error("Expected array to contain value.");
        }
        return;
      }
      if (typeof actual === "string") {
        if (!actual.includes(String(expected))) {
          throw new Error("Expected string to contain value.");
        }
        return;
      }
      throw new Error("toContain expects an array or string actual value.");
    },
    toBeGreaterThanOrEqual: (expected: number) => {
      if (typeof actual !== "number") {
        throw new Error(
          "toBeGreaterThanOrEqual expects a number actual value.",
        );
      }
      if (actual < expected) {
        throw new Error(`Expected ${actual} to be >= ${expected}.`);
      }
    },
  });
}

function deepEqual(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function normalizeScenarioRunners(
  runners: readonly TestRunnerName[] | undefined,
): readonly TestRunnerName[] {
  return runners && runners.length > 0 ? runners : ["reducer"];
}

function shouldRefreshReducerTestingTypes(
  existingContent: string | null,
): boolean {
  if (
    existingContent === null ||
    existingContent.trim().length === 0 ||
    existingContent === TESTING_TYPES_STUB ||
    existingContent.startsWith(GENERATED_TESTING_TYPES_PREFIX)
  ) {
    return true;
  }
  return false;
}

async function discoverFiles(root: string, suffix: string): Promise<string[]> {
  if (!(await exists(root))) {
    return [];
  }
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const entryPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await discoverFiles(entryPath, suffix)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(suffix)) {
      files.push(entryPath);
    }
  }
  files.sort();
  return files;
}

function isFunction(value: unknown): value is (...args: never[]) => unknown {
  return typeof value === "function";
}

function parseTypedBaseDefinition(value: unknown): TypedBaseDefinition {
  if (
    typeof value !== "object" ||
    value === null ||
    !("id" in value) ||
    typeof value.id !== "string" ||
    !("seed" in value) ||
    typeof value.seed !== "number" ||
    !("players" in value) ||
    typeof value.players !== "number" ||
    !("setup" in value) ||
    !isFunction(value.setup)
  ) {
    throw new Error("Invalid reducer-native base definition.");
  }
  const setupProfileId =
    "setupProfileId" in value && typeof value.setupProfileId === "string"
      ? value.setupProfileId
      : undefined;
  return {
    ...(value as TypedBaseDefinition),
    setupProfileId,
  };
}

function parseTypedScenarioDefinition(value: unknown): TypedScenarioDefinition {
  if (
    typeof value !== "object" ||
    value === null ||
    !("id" in value) ||
    typeof value.id !== "string" ||
    !("from" in value) ||
    typeof value.from !== "string" ||
    !("when" in value) ||
    !isFunction(value.when) ||
    !("then" in value) ||
    !isFunction(value.then)
  ) {
    throw new Error("Invalid reducer-native scenario definition.");
  }
  return value as TypedScenarioDefinition;
}

export async function isReducerNativeTestingWorkspace(
  projectRoot: string,
): Promise<boolean> {
  return (
    (await exists(path.join(projectRoot, "app", "game.ts"))) &&
    (await exists(
      path.join(projectRoot, "shared", "generated", "ui-contract.ts"),
    ))
  );
}

export async function ensureReducerNativeTestingFiles(
  projectRoot: string,
): Promise<void> {
  const testingTypesPath = path.join(projectRoot, "test", "testing-types.ts");
  const testingContractPath = path.join(
    projectRoot,
    "test",
    "generated",
    "testing-contract.ts",
  );

  await ensureDir(path.dirname(testingTypesPath));
  await ensureDir(path.dirname(testingContractPath));

  const existingTestingTypes = await readTextFileIfExists(testingTypesPath);
  if (shouldRefreshReducerTestingTypes(existingTestingTypes)) {
    await writeTextFile(
      testingTypesPath,
      REDUCER_TESTING_TYPES_WRAPPER_CONTENT,
    );
  }

  const existingTestingContract =
    await readTextFileIfExists(testingContractPath);
  if (
    existingTestingContract === null ||
    existingTestingContract.trim().length === 0 ||
    existingTestingContract.startsWith(GENERATED_TESTING_TYPES_PREFIX)
  ) {
    await writeTextFile(testingContractPath, REDUCER_TESTING_CONTRACT_CONTENT);
  }
}

export async function loadTypedBases(
  projectRoot: string,
): Promise<LoadedBase[]> {
  const baseFiles = await discoverFiles(
    path.join(projectRoot, "test", "bases"),
    BASE_SUFFIX,
  );
  const loaded: LoadedBase[] = [];
  for (const filePath of baseFiles) {
    const [module, bundledText] = await Promise.all([
      importTypeScriptModule<Record<string, unknown>>(filePath),
      bundleTypeScriptModuleText(filePath),
    ]);
    loaded.push({
      filePath,
      definition: parseTypedBaseDefinition(module.default),
      bundleHash: hashContent(bundledText),
    });
  }
  return loaded;
}

export async function loadTypedScenarios(
  projectRoot: string,
  options: { scenarioPath?: string },
): Promise<LoadedScenario[]> {
  const scenarioFiles = options.scenarioPath
    ? [path.resolve(projectRoot, options.scenarioPath)]
    : await discoverFiles(
        path.join(projectRoot, "test", "scenarios"),
        SCENARIO_SUFFIX,
      );
  const loaded: LoadedScenario[] = [];
  for (const filePath of scenarioFiles) {
    const [module, bundledText] = await Promise.all([
      importTypeScriptModule<Record<string, unknown>>(filePath),
      bundleTypeScriptModuleText(filePath),
    ]);
    loaded.push({
      filePath,
      definition: parseTypedScenarioDefinition(module.default),
      bundleHash: hashContent(bundledText),
    });
  }
  return loaded;
}

class KotlinSeededRandom {
  private x: number;
  private y: number;
  private z: number;
  private w: number;
  private v: number;
  private addend: number;

  constructor(seed: number) {
    const seedBig = BigInt.asIntN(64, BigInt(Math.trunc(seed)));
    const seed1 = Number(BigInt.asIntN(32, seedBig));
    const seed2 = Number(BigInt.asIntN(32, seedBig >> 32n));

    this.x = seed1 | 0;
    this.y = seed2 | 0;
    this.z = 0;
    this.w = 0;
    this.v = ~seed1;
    this.addend = ((seed1 << 10) ^ (seed2 >>> 4)) | 0;

    if ((this.x | this.y | this.z | this.w | this.v) === 0) {
      throw new Error(
        "Kotlin random seed must initialize at least one state word.",
      );
    }

    for (let index = 0; index < 64; index += 1) {
      this.nextInt();
    }
  }

  nextInt(): number {
    let next = this.x | 0;
    next ^= next >>> 2;
    this.x = this.y;
    this.y = this.z;
    this.z = this.w;
    const currentV = this.v | 0;
    this.w = currentV;
    next = (next ^ (next << 1) ^ currentV ^ (currentV << 4)) | 0;
    this.v = next;
    this.addend = (this.addend + 362437) | 0;
    return (next + this.addend) | 0;
  }

  private nextBits(bitCount: number): number {
    if (bitCount <= 0) {
      return 0;
    }
    return this.nextInt() >>> (32 - bitCount);
  }

  nextIntBound(bound: number): number {
    if (bound <= 0) {
      throw new Error("bound must be positive");
    }

    if ((bound & -bound) === bound) {
      const bitCount = 31 - Math.clz32(bound);
      return this.nextBits(bitCount);
    }

    let value: number;
    while (true) {
      const bits = this.nextInt() >>> 1;
      value = bits % bound;
      if (bits - value + (bound - 1) >= 0) {
        return value;
      }
    }
  }

  nextLong(): number {
    const high = BigInt(this.nextInt());
    const low = BigInt(this.nextInt());
    return Number(BigInt.asIntN(64, (high << 32n) + low));
  }
}

function shuffleWithKotlinRandom<T>(
  values: readonly T[],
  random: KotlinSeededRandom,
): T[] {
  const next = [...values];
  for (let index = next.length - 1; index > 0; index -= 1) {
    const swapIndex = random.nextIntBound(index + 1);
    const current = next[index];
    next[index] = next[swapIndex] as T;
    next[swapIndex] = current as T;
  }
  return next;
}

type EffectiveBaseSetup = {
  setupProfileId: string | null;
};

type GeneratedInitialTableFactory = (options?: {
  playerIds?: readonly string[];
  shuffleItems?: <Value>(values: readonly Value[]) => Value[];
}) => Record<string, unknown>;

function resolveEffectiveBaseSetup(options: {
  manifest: GameTopologyManifest;
  base: TypedBaseDefinition;
}): EffectiveBaseSetup {
  const selection = resolveSetupProfileSelection({
    manifest: options.manifest,
    requestedSetupProfileId: options.base.setupProfileId,
  });
  return {
    setupProfileId: selection.id,
  };
}

function summarizeTableValidationError(
  manifest: GameTopologyManifest,
  error: Error,
): string {
  const issues = error.message
    .split("; ")
    .map((issue) => issue.trim())
    .filter((issue) => issue.length > 0);

  if (
    issues.length === 0 ||
    !issues.every((issue) => issue.startsWith("table"))
  ) {
    return error.message;
  }

  const boardBaseIdByRuntimeId = new Map<string, string>(
    (manifest.boards ?? []).flatMap((board) =>
      board.scope === "perPlayer"
        ? Array.from(
            { length: manifest.players.maxPlayers },
            (_, index) =>
              [`${board.id}:player-${index + 1}`, board.id] as const,
          )
        : ([[board.id, board.id]] as const),
    ),
  );

  const representativeIssues = issues.slice(0, 3).map((issue) => {
    const [, runtimeBoardId = ""] =
      issue.match(/^table\.boards\.byId\.([^.]+)\./) ?? [];
    const boardBaseId = boardBaseIdByRuntimeId.get(runtimeBoardId);
    if (!boardBaseId) {
      return `- ${issue.replace(/^table\./, "")}`;
    }
    const boardSpecificPath = issue
      .replace(/^table\.boards\.byId\.[^.]+\./, "")
      .replace(/^table\./, "");
    return `- board '${boardBaseId}' (${runtimeBoardId}): ${boardSpecificPath}`;
  });

  return [
    `Reducer-native table validation failed with ${issues.length} issue${issues.length === 1 ? "" : "s"}.`,
    "Likely root cause: the generated test table shape does not match the authored manifest topology.",
    ...representativeIssues,
    "Pass --debug for the full validation dump.",
  ].join("\n");
}

class ShadowReducerRuntime {
  private readonly bundle: ReturnType<typeof createReducerBundle>;
  private readonly playerIds: string[];
  private readonly historyRecords: HistoryRecord[] = [];
  private state: Record<string, unknown> | null = null;
  private started = false;

  constructor(
    private readonly manifest: GameTopologyManifest,
    private readonly gameModuleDefault: unknown,
    private readonly createInitialTable: GeneratedInitialTableFactory | null,
    private readonly seed: number,
    private readonly players: number,
    private readonly setupProfileId: string | null,
    private readonly debug = false,
  ) {
    if (
      typeof gameModuleDefault !== "object" ||
      gameModuleDefault === null ||
      !("contract" in gameModuleDefault)
    ) {
      throw new Error(
        "app/game.ts must export a reducer-native game definition.",
      );
    }
    this.bundle = createReducerBundle(gameModuleDefault as never);
    this.playerIds = Array.from(
      { length: players },
      (_, index) => `player-${index + 1}`,
    );
  }

  async start(): Promise<void> {
    if (this.started) {
      return;
    }
    const random = new KotlinSeededRandom(this.seed);
    const shuffleItems = <Value>(values: readonly Value[]) =>
      shuffleWithKotlinRandom(values, random);
    const table =
      this.createInitialTable?.({
        playerIds: this.playerIds,
        shuffleItems,
      }) ??
      materializeManifestTable({
        manifest: this.manifest,
        playerIds: this.playerIds,
        shuffleItems,
      });
    const rngSeed = random.nextLong();
    try {
      this.state = (await this.bundle.initialize({
        table: table as never,
        playerIds: this.playerIds,
        rngSeed,
        setup: this.setupProfileId
          ? {
              profileId: this.setupProfileId,
            }
          : null,
      })) as Record<string, unknown>;
    } catch (error) {
      if (!this.debug && error instanceof Error) {
        throw new Error(summarizeTableValidationError(this.manifest, error));
      }
      throw error;
    }
    this.started = true;
  }

  phase(): string {
    return (
      ((
        (this.state?.domain as { flow?: { currentPhase?: string } } | undefined)
          ?.flow as { currentPhase?: string } | undefined
      )?.currentPhase ??
        null) ||
      ""
    );
  }

  playerOrder(): string[] {
    return this.playerIds;
  }

  rawState(): Record<string, unknown> {
    if (!this.state) {
      throw new Error("Reducer runtime has not been started.");
    }
    return this.state;
  }

  view(playerId: string): unknown {
    return this.bundle.getView({
      state: this.rawState() as never,
      playerId,
    });
  }

  async availableActionsByPlayerId(): Promise<Record<string, string[]>> {
    return Object.fromEntries(
      await Promise.all(
        this.playerIds.map(async (playerId) => [
          playerId,
          (
            await this.bundle.getAvailableActions({
              state: this.rawState() as never,
              playerId,
            })
          )
            .map((action) => action?.actionType)
            .filter((actionType): actionType is string => !!actionType),
        ]),
      ),
    );
  }

  promptInstances(): Array<Record<string, unknown>> {
    return ((this.rawState().runtime as { prompts?: unknown[] } | undefined)
      ?.prompts ?? []) as Array<Record<string, unknown>>;
  }

  promptsForPlayer(playerId: string): Array<Record<string, unknown>> {
    return this.promptInstances().filter((prompt) =>
      promptTargetsPlayer(prompt, playerId),
    );
  }

  windowInstances(): Array<Record<string, unknown>> {
    return ((this.rawState().runtime as { windows?: unknown[] } | undefined)
      ?.windows ?? []) as Array<Record<string, unknown>>;
  }

  windowsForPlayer(playerId: string): Array<Record<string, unknown>> {
    return this.windowInstances().filter((window) =>
      windowTargetsPlayer(window, playerId),
    );
  }

  clearHistory(): void {
    this.historyRecords.length = 0;
  }

  private async applyInput(input: HistoryInput): Promise<void> {
    const parsedInput = toReducerInput(input);
    const validation = (await this.bundle.validateInput({
      state: this.rawState() as never,
      input: parsedInput as never,
    })) as { valid: boolean; errorCode?: string; message?: string };
    if (!validation.valid) {
      const record = {
        input,
        accepted: false,
        errorCode: validation.errorCode,
        message: validation.message,
      };
      this.historyRecords.push(record);
      throw createSubmissionError(
        validation.errorCode,
        validation.message,
        "Reducer input rejected.",
      );
    }

    const result = (await this.bundle.dispatch({
      state: this.rawState() as never,
      input: parsedInput as never,
    })) as
      | {
          type: "accept";
          state: Record<string, unknown>;
        }
      | {
          type: "reject";
          errorCode: string;
          message?: string;
        };

    assertDispatchResultWireContract(result);

    if (result.type === "reject") {
      const record = {
        input,
        accepted: false,
        errorCode: result.errorCode,
        message: result.message,
      };
      this.historyRecords.push(record);
      throw createSubmissionError(
        result.errorCode,
        result.message,
        "Reducer input rejected.",
      );
    }

    this.state = result.state;
    this.historyRecords.push({ input, accepted: true });
  }

  async submitAction(
    playerId: string,
    actionType: string,
    params: Record<string, unknown>,
  ): Promise<void> {
    await this.applyInput({
      kind: "action",
      playerId,
      actionType,
      params,
    });
  }

  async submitPromptResponse(
    playerId: string,
    promptId: string,
    response: unknown,
  ): Promise<void> {
    await this.applyInput({
      kind: "promptResponse",
      playerId,
      promptId,
      response,
    });
  }

  async submitWindowAction(
    playerId: string,
    windowId: string,
    actionType: string,
    params: Record<string, unknown>,
  ): Promise<void> {
    await this.applyInput({
      kind: "windowAction",
      playerId,
      windowId,
      actionType,
      params,
    });
  }
}

function toReducerInput(input: HistoryInput): Record<string, unknown> {
  switch (input.kind) {
    case "action":
      return {
        kind: "action",
        playerId: input.playerId,
        actionType: input.actionType,
        params: input.params,
      };
    case "promptResponse":
      return {
        kind: "promptResponse",
        playerId: input.playerId,
        promptId: input.promptId,
        response: input.response,
      };
    case "windowAction":
      return {
        kind: "windowAction",
        playerId: input.playerId,
        windowId: input.windowId,
        actionType: input.actionType,
        params: input.params,
      };
  }
}

function promptTargetsPlayer(
  prompt: Record<string, unknown>,
  playerId: string,
): boolean {
  return prompt.to === playerId;
}

function windowTargetsPlayer(
  window: Record<string, unknown>,
  playerId: string,
): boolean {
  const addressedTo = Array.isArray(window.addressedTo)
    ? window.addressedTo
    : [];
  return addressedTo.length === 0 || addressedTo.includes(playerId);
}

class EmbeddedGameplayTracker {
  private readonly abortController = new AbortController();
  private readonly state: GameplaySnapshot = {
    version: -1,
    currentPhase: null,
    seatViewsByPlayerId: {},
    availableActionsByPlayerId: {},
    prompts: [],
    windows: [],
  };
  private readonly events: GameMessage[] = [];
  private connected = false;

  constructor(private readonly sessionId: string) {}

  async connect(): Promise<void> {
    if (this.connected) {
      return;
    }
    this.connected = true;
    const { stream } = await subscribeToCliSessionEvents({
      sessionId: this.sessionId,
      signal: this.abortController.signal,
      clientSource: "dreamboard-cli-test",
    });

    void (async () => {
      for await (const message of stream) {
        if (!message) {
          continue;
        }
        this.events.push(message);
        this.onMessage(message);
      }
    })();
  }

  close(): void {
    this.abortController.abort();
  }

  snapshot(): GameplaySnapshot {
    return {
      ...this.state,
      seatViewsByPlayerId: { ...this.state.seatViewsByPlayerId },
      availableActionsByPlayerId: { ...this.state.availableActionsByPlayerId },
      prompts: [...this.state.prompts],
      windows: [...this.state.windows],
    };
  }

  private onMessage(message: GameMessage): void {
    if (message.type === "SESSION_BOOTSTRAP" && message.gameplay) {
      this.state.version = message.gameplay.version;
      this.state.currentPhase = message.gameplay.currentPhase;
      this.state.seatViewsByPlayerId = parseSeatViews(
        message.gameplay.seatViewsByPlayerId,
      );
      this.state.availableActionsByPlayerId = Object.fromEntries(
        message.gameplay.availableActions.map((entry) => [
          entry.playerId,
          entry.actions.map((action) => action.actionType),
        ]),
      );
      this.state.prompts = message.gameplay.prompts as Array<
        Record<string, unknown>
      >;
      this.state.windows = message.gameplay.windows as Array<
        Record<string, unknown>
      >;
      return;
    }

    if (message.type === "GAMEPLAY_UPDATE") {
      this.state.version = message.gameplay.version;
      this.state.currentPhase = message.gameplay.currentPhase;
      this.state.seatViewsByPlayerId = parseSeatViews(
        message.gameplay.seatViewsByPlayerId,
      );
      this.state.availableActionsByPlayerId = Object.fromEntries(
        message.gameplay.availableActions.map((entry) => [
          entry.playerId,
          entry.actions.map((action) => action.actionType),
        ]),
      );
      this.state.prompts = message.gameplay.prompts as Array<
        Record<string, unknown>
      >;
      this.state.windows = message.gameplay.windows as Array<
        Record<string, unknown>
      >;
    }
  }

  async waitForVersionChange(
    previousVersion: number,
    timeoutMs = DEFAULT_TIMEOUT_MS,
  ): Promise<void> {
    const startedAt = Date.now();
    while (Date.now() - startedAt < timeoutMs) {
      if (this.state.version > previousVersion) {
        return;
      }
      await sleep(20);
    }
    throw new Error("Timed out waiting for gameplay version change.");
  }

  async waitForBootstrap(timeoutMs = DEFAULT_TIMEOUT_MS): Promise<void> {
    await this.waitForVersionChange(-1, timeoutMs);
  }
}

function parseSeatViews(raw: Record<string, string>): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(raw ?? {}).map(([playerId, value]) => [
      playerId,
      parseJsonValue(value),
    ]),
  );
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function assertTaggedByKind(
  value: unknown,
  label: string,
): asserts value is Record<string, unknown> & { type: string; kind: string } {
  if (!value || typeof value !== "object") {
    throw new Error(
      `Reducer bundle returned invalid payload for 'dispatch': ${label} must be an object.`,
    );
  }
  const tagged = value as { type?: unknown; kind?: unknown };
  if (typeof tagged.type !== "string") {
    throw new Error(
      `Reducer bundle returned invalid payload for 'dispatch': ${label} is missing string property 'type'.`,
    );
  }
  if (tagged.kind !== tagged.type) {
    throw new Error(
      `Reducer bundle returned invalid payload for 'dispatch': ${label} must include kind='${tagged.type}'.`,
    );
  }
}

export function assertDispatchResultWireContract(result: unknown): void {
  assertTaggedByKind(result, "DispatchResult");
  if (result.type !== "accept") {
    return;
  }

  const trace = (result as { trace?: unknown }).trace;
  if (!Array.isArray(trace)) {
    throw new Error(
      "Reducer bundle returned invalid payload for 'dispatch': DispatchResult.accept.trace must be an array.",
    );
  }

  for (const [index, entry] of trace.entries()) {
    assertTaggedByKind(entry, `DispatchResult.accept.trace[${index}]`);
    if (entry.type !== "appliedEffect") {
      continue;
    }

    const effect = (entry as { effect?: unknown }).effect;
    assertTaggedByKind(effect, `DispatchResult.accept.trace[${index}].effect`);
    if (effect.type !== "openWindow") {
      continue;
    }

    const closePolicy = (effect as { closePolicy?: unknown }).closePolicy;
    assertTaggedByKind(
      closePolicy,
      `DispatchResult.accept.trace[${index}].effect.closePolicy`,
    );
  }
}

async function createBrowserBridgeClient(
  page: Page,
): Promise<BrowserBridgeClient> {
  const bridgeExists = async (): Promise<boolean> =>
    page.evaluate(() =>
      Boolean(
        (
          window as typeof window & {
            __dreamboardTestBridge__?: unknown;
          }
        ).__dreamboardTestBridge__,
      ),
    );

  const startedAt = Date.now();
  while (!(await bridgeExists())) {
    if (Date.now() - startedAt > DEFAULT_TIMEOUT_MS) {
      const bodyText = await page
        .locator("body")
        .innerText()
        .catch(() => "");
      const diagnostic = bodyText.trim().replace(/\s+/g, " ").slice(0, 400);
      throw new Error(
        diagnostic.length > 0
          ? `Timed out waiting for browser test bridge. Page text: ${diagnostic}`
          : "Timed out waiting for browser test bridge.",
      );
    }
    await sleep(50);
  }

  return {
    snapshot: () =>
      page.evaluate(() =>
        (
          window as typeof window & {
            __dreamboardTestBridge__: {
              snapshot: () => Promise<BrowserSnapshot>;
            };
          }
        ).__dreamboardTestBridge__.snapshot(),
      ),
    submitAction: (playerId, actionType, params) =>
      page.evaluate(
        ([nextPlayerId, nextActionType, nextParams]) =>
          (
            window as typeof window & {
              __dreamboardTestBridge__: {
                submitAction: (
                  playerId: string,
                  actionType: string,
                  params: Record<string, unknown>,
                ) => Promise<void>;
              };
            }
          ).__dreamboardTestBridge__.submitAction(
            nextPlayerId,
            nextActionType,
            nextParams,
          ),
        [playerId, actionType, params] as const,
      ),
    submitPromptResponse: (playerId, promptId, response) =>
      page.evaluate(
        ([nextPlayerId, nextPromptId, nextResponse]) =>
          (
            window as typeof window & {
              __dreamboardTestBridge__: {
                submitPromptResponse: (
                  playerId: string,
                  promptId: string,
                  response: unknown,
                ) => Promise<void>;
              };
            }
          ).__dreamboardTestBridge__.submitPromptResponse(
            nextPlayerId,
            nextPromptId,
            nextResponse,
          ),
        [playerId, promptId, response] as const,
      ),
    submitWindowAction: (playerId, windowId, actionType, params) =>
      page.evaluate(
        ([nextPlayerId, nextWindowId, nextActionType, nextParams]) =>
          (
            window as typeof window & {
              __dreamboardTestBridge__: {
                submitWindowAction: (
                  playerId: string,
                  windowId: string,
                  actionType: string,
                  params: Record<string, unknown>,
                ) => Promise<void>;
              };
            }
          ).__dreamboardTestBridge__.submitWindowAction(
            nextPlayerId,
            nextWindowId,
            nextActionType,
            nextParams,
          ),
        [playerId, windowId, actionType, params] as const,
      ),
    waitForVersionChange: async (
      previousVersion,
      timeoutMs = DEFAULT_TIMEOUT_MS,
    ) => {
      const started = Date.now();
      while (Date.now() - started < timeoutMs) {
        const snapshot = await page.evaluate(() =>
          (
            window as typeof window & {
              __dreamboardTestBridge__: {
                snapshot: () => Promise<BrowserSnapshot>;
              };
            }
          ).__dreamboardTestBridge__.snapshot(),
        );
        if (snapshot.version > previousVersion) {
          return snapshot;
        }
        await sleep(50);
      }
      throw new Error("Timed out waiting for browser gameplay version change.");
    },
  };
}

function normalizePromptForComparison(
  prompt: Record<string, unknown>,
): Record<string, unknown> {
  return {
    id: prompt.id,
    promptId: prompt.promptId,
    to: prompt.to,
    title: prompt.title ?? null,
    payload: prompt.payload ?? null,
    options: Array.isArray(prompt.options)
      ? prompt.options.map((option) => ({
          id: (option as { id?: unknown }).id ?? null,
          label: (option as { label?: unknown }).label ?? null,
        }))
      : [],
  };
}

function normalizeWindowForComparison(
  window: Record<string, unknown>,
): Record<string, unknown> {
  return {
    id: window.id,
    windowId: window.windowId,
    closePolicy: window.closePolicy ?? null,
    addressedTo: Array.isArray(window.addressedTo) ? window.addressedTo : [],
    payload: window.payload ?? null,
  };
}

async function assertLiveMatchesShadow(
  runner: TestRunnerName,
  shadow: ShadowReducerRuntime,
  live: GameplaySnapshot | BrowserSnapshot,
): Promise<void> {
  if (runner === "reducer") {
    return;
  }

  const livePrompts = ("prompts" in live ? live.prompts : []).map(
    normalizePromptForComparison,
  );
  const shadowPrompts = shadow
    .promptInstances()
    .map(normalizePromptForComparison);
  if (!deepEqual(livePrompts, shadowPrompts)) {
    throw new Error("Live prompt state diverged from reducer shadow state.");
  }

  const liveWindows = ("windows" in live ? live.windows : []).map(
    normalizeWindowForComparison,
  );
  const shadowWindows = shadow
    .windowInstances()
    .map(normalizeWindowForComparison);
  if (!deepEqual(liveWindows, shadowWindows)) {
    throw new Error("Live window state diverged from reducer shadow state.");
  }

  const currentPhase =
    "currentPhase" in live ? live.currentPhase : shadow.phase();
  if (currentPhase !== shadow.phase()) {
    throw new Error(
      `Live phase '${String(currentPhase)}' diverged from reducer phase '${shadow.phase()}'.`,
    );
  }

  const liveViews =
    "seatViewsByPlayerId" in live ? live.seatViewsByPlayerId : {};
  const shadowViews = Object.fromEntries(
    await Promise.all(
      shadow
        .playerOrder()
        .map(async (playerId) => [playerId, await shadow.view(playerId)]),
    ),
  );
  if (!deepEqual(liveViews, shadowViews)) {
    throw new Error("Live projected views diverged from reducer shadow views.");
  }

  const liveActions =
    "availableActionsByPlayerId" in live
      ? live.availableActionsByPlayerId
      : null;
  if (
    liveActions &&
    !deepEqual(liveActions, await shadow.availableActionsByPlayerId())
  ) {
    throw new Error(
      "Live available-actions metadata diverged from reducer shadow state.",
    );
  }
}

async function loadBrowserDriver(
  projectRoot: string,
): Promise<BrowserRunnerDriver | null> {
  const filePath = path.join(projectRoot, "test", "browser-driver.ts");
  if (!(await exists(filePath))) {
    return null;
  }
  const module = await importTypeScriptModule<BrowserDriverModule>(filePath);
  return module.default ?? module;
}

async function openBrowserPage(
  playUrl: string,
  config: ResolvedConfig,
): Promise<{
  browser: Browser;
  page: Page;
}> {
  configurePlaywrightBrowsersPath();
  const { chromium } = await import("playwright");
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
  });
  const initScript = await buildBrowserAuthInitScript(config);
  if (initScript) {
    await context.addInitScript({ content: initScript });
  }
  const page = await context.newPage();
  await page.goto(playUrl, { waitUntil: "domcontentloaded" });
  return { browser, page };
}

async function createScenarioContext(options: {
  runner: TestRunnerName;
  shadow: ShadowReducerRuntime;
  embedded?:
    | {
        sessionId: string;
        tracker: EmbeddedGameplayTracker;
      }
    | undefined;
  browser?:
    | {
        bridge: BrowserBridgeClient;
        driver: BrowserRunnerDriver | null;
      }
    | undefined;
}): Promise<SharedScenarioContext> {
  const expect = createExpectApi();

  const resolvePromptInstanceId = (
    playerId: string,
    promptOrId: string | { id: string; promptId?: string },
  ): string => {
    if (typeof promptOrId !== "string") {
      return (
        (promptOrId.id as string | undefined) ??
        (promptOrId.promptId as string | undefined) ??
        ""
      );
    }

    const directMatch = options.shadow
      .promptInstances()
      .find((candidate) => candidate.id === promptOrId);
    if (directMatch) {
      return promptOrId;
    }

    const activePrompt = options.shadow
      .promptsForPlayer(playerId)
      .find((candidate) => candidate.promptId === promptOrId);
    return (activePrompt?.id as string | undefined) ?? promptOrId;
  };

  const resolveWindowInstanceId = (
    playerId: string,
    windowOrId: string | { id: string; windowId?: string },
  ): string => {
    if (typeof windowOrId !== "string") {
      return (
        (windowOrId.id as string | undefined) ??
        (windowOrId.windowId as string | undefined) ??
        ""
      );
    }

    const directMatch = options.shadow
      .windowInstances()
      .find((candidate) => candidate.id === windowOrId);
    if (directMatch) {
      return windowOrId;
    }

    const activeWindow = options.shadow
      .windowsForPlayer(playerId)
      .find((candidate) => candidate.windowId === windowOrId);
    return (activeWindow?.id as string | undefined) ?? windowOrId;
  };

  const api: ScenarioGameApi = {
    start: async () => {
      await options.shadow.start();
      if (options.runner === "embedded" && options.embedded) {
        const live = options.embedded.tracker.snapshot();
        await assertLiveMatchesShadow("embedded", options.shadow, live);
      }
      if (options.runner === "browser" && options.browser) {
        const live = await options.browser.bridge.snapshot();
        await assertLiveMatchesShadow("browser", options.shadow, live);
      }
    },
    action: async (playerId, actionOrCommand, params) => {
      await api.start();
      const actionType =
        typeof actionOrCommand === "string"
          ? actionOrCommand
          : actionOrCommand.type;
      const actionParams =
        typeof actionOrCommand === "string"
          ? (params ?? {})
          : (actionOrCommand.params ?? {});

      const previousVersion =
        options.runner === "embedded"
          ? (options.embedded?.tracker.snapshot().version ?? 0)
          : options.runner === "browser"
            ? ((await options.browser?.bridge.snapshot())?.version ?? 0)
            : 0;

      if (options.runner === "embedded" && options.embedded) {
        const { data, error } = await submitInput({
          path: { sessionId: options.embedded.sessionId },
          body: {
            input: {
              kind: "action",
              playerId,
              actionType,
              params: JSON.stringify(actionParams),
            },
            expectedVersion: previousVersion,
          },
        });
        if (error) {
          throw createSubmissionError(
            "api-error",
            undefined,
            "Failed to submit action",
          );
        }
        if (data?.accepted === false) {
          const shadowError = await tryShadowAction(
            options.shadow,
            playerId,
            actionType,
            actionParams,
          );
          if (!shadowError || shadowError.errorCode !== data.errorCode) {
            throw new Error(
              "Embedded harness rejection diverged from reducer shadow state.",
            );
          }
          throw createSubmissionError(
            data.errorCode ?? undefined,
            data.message ?? undefined,
            "Action rejected",
          );
        }
      } else if (options.runner === "browser" && options.browser) {
        const handled =
          (await options.browser.driver?.action?.(options.browser.bridge, {
            playerId,
            actionType,
            params: actionParams,
          })) === true;
        if (!handled) {
          await options.browser.bridge.submitAction(
            playerId,
            actionType,
            actionParams,
          );
        }
      }

      await options.shadow.submitAction(playerId, actionType, actionParams);

      if (options.runner === "embedded" && options.embedded) {
        await options.embedded.tracker.waitForVersionChange(previousVersion);
        await assertLiveMatchesShadow(
          "embedded",
          options.shadow,
          options.embedded.tracker.snapshot(),
        );
      }
      if (options.runner === "browser" && options.browser) {
        const live =
          await options.browser.bridge.waitForVersionChange(previousVersion);
        await assertLiveMatchesShadow("browser", options.shadow, live);
      }
    },
    respond: async (playerId, promptOrId, response) => {
      await api.start();
      const promptId = resolvePromptInstanceId(playerId, promptOrId);

      const previousVersion =
        options.runner === "embedded"
          ? (options.embedded?.tracker.snapshot().version ?? 0)
          : options.runner === "browser"
            ? ((await options.browser?.bridge.snapshot())?.version ?? 0)
            : 0;

      if (options.runner === "embedded" && options.embedded) {
        const { data, error } = await submitInput({
          path: { sessionId: options.embedded.sessionId },
          body: {
            input: {
              kind: "promptResponse",
              playerId,
              promptId,
              response: JSON.stringify(response),
            },
            expectedVersion: previousVersion,
          },
        });
        if (error) {
          throw createSubmissionError(
            "api-error",
            undefined,
            "Failed to submit prompt response",
          );
        }
        if (data?.accepted === false) {
          const shadowError = await tryShadowPrompt(
            options.shadow,
            playerId,
            promptId,
            response,
          );
          if (!shadowError || shadowError.errorCode !== data.errorCode) {
            throw new Error(
              "Embedded prompt rejection diverged from reducer shadow state.",
            );
          }
          throw createSubmissionError(
            data.errorCode ?? undefined,
            data.message ?? undefined,
            "Prompt response rejected",
          );
        }
      } else if (options.runner === "browser" && options.browser) {
        const handled =
          (await options.browser.driver?.promptResponse?.(
            options.browser.bridge,
            {
              playerId,
              promptId,
              response,
            },
          )) === true;
        if (!handled) {
          await options.browser.bridge.submitPromptResponse(
            playerId,
            promptId,
            response,
          );
        }
      }

      await options.shadow.submitPromptResponse(playerId, promptId, response);

      if (options.runner === "embedded" && options.embedded) {
        await options.embedded.tracker.waitForVersionChange(previousVersion);
        await assertLiveMatchesShadow(
          "embedded",
          options.shadow,
          options.embedded.tracker.snapshot(),
        );
      }
      if (options.runner === "browser" && options.browser) {
        const live =
          await options.browser.bridge.waitForVersionChange(previousVersion);
        await assertLiveMatchesShadow("browser", options.shadow, live);
      }
    },
    windowAction: async (playerId, windowOrId, actionOrCommand, params) => {
      await api.start();
      const windowId = resolveWindowInstanceId(playerId, windowOrId);
      const actionType =
        typeof actionOrCommand === "string"
          ? actionOrCommand
          : actionOrCommand.type;
      const actionParams =
        typeof actionOrCommand === "string"
          ? (params ?? {})
          : (actionOrCommand.params ?? {});

      const previousVersion =
        options.runner === "embedded"
          ? (options.embedded?.tracker.snapshot().version ?? 0)
          : options.runner === "browser"
            ? ((await options.browser?.bridge.snapshot())?.version ?? 0)
            : 0;

      if (options.runner === "embedded" && options.embedded) {
        const { data, error } = await submitInput({
          path: { sessionId: options.embedded.sessionId },
          body: {
            input: {
              kind: "windowAction",
              playerId,
              windowId,
              actionType,
              params: JSON.stringify(actionParams),
            },
            expectedVersion: previousVersion,
          },
        });
        if (error) {
          throw createSubmissionError(
            "api-error",
            undefined,
            "Failed to submit window action",
          );
        }
        if (data?.accepted === false) {
          const shadowError = await tryShadowWindow(
            options.shadow,
            playerId,
            windowId,
            actionType,
            actionParams,
          );
          if (!shadowError || shadowError.errorCode !== data.errorCode) {
            throw new Error(
              "Embedded window rejection diverged from reducer shadow state.",
            );
          }
          throw createSubmissionError(
            data.errorCode ?? undefined,
            data.message ?? undefined,
            "Window action rejected",
          );
        }
      } else if (options.runner === "browser" && options.browser) {
        const handled =
          (await options.browser.driver?.windowAction?.(
            options.browser.bridge,
            {
              playerId,
              windowId,
              actionType,
              params: actionParams,
            },
          )) === true;
        if (!handled) {
          await options.browser.bridge.submitWindowAction(
            playerId,
            windowId,
            actionType,
            actionParams,
          );
        }
      }

      await options.shadow.submitWindowAction(
        playerId,
        windowId,
        actionType,
        actionParams,
      );

      if (options.runner === "embedded" && options.embedded) {
        await options.embedded.tracker.waitForVersionChange(previousVersion);
        await assertLiveMatchesShadow(
          "embedded",
          options.shadow,
          options.embedded.tracker.snapshot(),
        );
      }
      if (options.runner === "browser" && options.browser) {
        const live =
          await options.browser.bridge.waitForVersionChange(previousVersion);
        await assertLiveMatchesShadow("browser", options.shadow, live);
      }
    },
    expectPrompt: async (playerId, promptId) => {
      await api.start();
      const started = Date.now();
      while (Date.now() - started < DEFAULT_TIMEOUT_MS) {
        const prompt =
          options.shadow
            .promptsForPlayer(playerId)
            .find((candidate) => candidate.promptId === promptId) ?? null;
        if (prompt) {
          if (options.runner === "embedded" && options.embedded) {
            await assertLiveMatchesShadow(
              "embedded",
              options.shadow,
              options.embedded.tracker.snapshot(),
            );
          }
          if (options.runner === "browser" && options.browser) {
            await assertLiveMatchesShadow(
              "browser",
              options.shadow,
              await options.browser.bridge.snapshot(),
            );
          }
          return prompt;
        }
        await sleep(20);
      }
      throw new Error(`Timed out waiting for prompt '${promptId}'.`);
    },
    expectWindow: async (windowId) => {
      await api.start();
      const started = Date.now();
      while (Date.now() - started < DEFAULT_TIMEOUT_MS) {
        const window =
          options.shadow
            .windowInstances()
            .find((candidate) => candidate.windowId === windowId) ?? null;
        if (window) {
          if (options.runner === "embedded" && options.embedded) {
            await assertLiveMatchesShadow(
              "embedded",
              options.shadow,
              options.embedded.tracker.snapshot(),
            );
          }
          if (options.runner === "browser" && options.browser) {
            await assertLiveMatchesShadow(
              "browser",
              options.shadow,
              await options.browser.bridge.snapshot(),
            );
          }
          return window;
        }
        await sleep(20);
      }
      throw new Error(`Timed out waiting for window '${windowId}'.`);
    },
  };

  return {
    game: api,
    players: () => options.shadow.playerOrder(),
    state: () => options.shadow.phase(),
    view: (playerId) => options.shadow.view(playerId),
    prompts: (playerId) => options.shadow.promptsForPlayer(playerId),
    windows: (playerId) => options.shadow.windowsForPlayer(playerId),
    expect,
  };
}

async function tryShadowAction(
  shadow: ShadowReducerRuntime,
  playerId: string,
  actionType: string,
  params: Record<string, unknown>,
): Promise<SubmissionError | null> {
  try {
    await shadow.submitAction(playerId, actionType, params);
    throw new Error("Expected shadow action to reject.");
  } catch (error) {
    if (
      error instanceof Error &&
      (error as SubmissionError).name === "SubmissionError"
    ) {
      return error as SubmissionError;
    }
    throw error;
  }
}

async function tryShadowPrompt(
  shadow: ShadowReducerRuntime,
  playerId: string,
  promptId: string,
  response: unknown,
): Promise<SubmissionError | null> {
  try {
    await shadow.submitPromptResponse(playerId, promptId, response);
    throw new Error("Expected shadow prompt response to reject.");
  } catch (error) {
    if (
      error instanceof Error &&
      (error as SubmissionError).name === "SubmissionError"
    ) {
      return error as SubmissionError;
    }
    throw error;
  }
}

async function tryShadowWindow(
  shadow: ShadowReducerRuntime,
  playerId: string,
  windowId: string,
  actionType: string,
  params: Record<string, unknown>,
): Promise<SubmissionError | null> {
  try {
    await shadow.submitWindowAction(playerId, windowId, actionType, params);
    throw new Error("Expected shadow window action to reject.");
  } catch (error) {
    if (
      error instanceof Error &&
      (error as SubmissionError).name === "SubmissionError"
    ) {
      return error as SubmissionError;
    }
    throw error;
  }
}

function baseStateKey(baseId: string): string {
  return baseId;
}

function validateTypedScenarioBases(
  scenarios: LoadedScenario[],
  basesById: Map<string, LoadedBase>,
): void {
  const available = new Set(basesById.keys());
  const invalid = scenarios
    .filter((scenario) => !available.has(scenario.definition.from))
    .map(
      (scenario) =>
        path.relative(process.cwd(), scenario.filePath) +
        ` -> '${scenario.definition.from}'`,
    );

  if (invalid.length > 0) {
    throw new Error(
      `Unknown scenario base(s): ${invalid.join(", ")}. Available bases: ${Array.from(available).sort().join(", ")}`,
    );
  }
}

export async function writeReducerNativeGeneratedFiles(options: {
  projectRoot: string;
  bases: LoadedBase[];
  scenarios: LoadedScenario[];
  compiledResultId?: string;
  gameId?: string;
  debug?: boolean;
}): Promise<void> {
  await ensureReducerNativeTestingFiles(options.projectRoot);

  const manifest = await loadManifest(options.projectRoot);
  const manifestHash = hashContent(JSON.stringify(manifest));
  const appBundleHash = hashContent(
    await bundleTypeScriptModuleText(
      path.join(options.projectRoot, "app", "game.ts"),
    ),
  );
  const uiContractHash = hashContent(
    await bundleTypeScriptModuleText(
      path.join(options.projectRoot, "shared", "generated", "ui-contract.ts"),
    ),
  );

  const generatedDir = path.join(options.projectRoot, "test", "generated");
  await ensureDir(generatedDir);
  const baseStates: BaseStateFile = {};
  const [gameModule, manifestContractModule] = await Promise.all([
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "app", "game.ts"),
    ),
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "shared", "manifest-contract.ts"),
    ),
  ]);
  const createInitialTable =
    typeof manifestContractModule.createInitialTable === "function"
      ? (manifestContractModule.createInitialTable as GeneratedInitialTableFactory)
      : null;
  for (const base of options.bases) {
    const effectiveSetup = resolveEffectiveBaseSetup({
      manifest,
      base: base.definition,
    });
    const shadow = new ShadowReducerRuntime(
      manifest,
      gameModule.default,
      createInitialTable,
      base.definition.seed,
      base.definition.players,
      effectiveSetup.setupProfileId,
      options.debug ?? false,
    );
    const context = await createScenarioContext({
      runner: "reducer",
      shadow,
    });
    await context.game.start();
    await base.definition.setup({ game: context.game });
    baseStates[baseStateKey(base.definition.id)] = {
      key: baseStateKey(base.definition.id),
      base: base.definition.id,
      snapshot: shadow.rawState(),
      fingerprint: {
        base: base.definition.id,
        seed: base.definition.seed,
        players: base.definition.players,
        baseBundleHash: base.bundleHash,
        manifestHash,
        appBundleHash,
        uiContractHash,
        setupProfileId: effectiveSetup.setupProfileId,
        compiledResultId: options.compiledResultId,
        gameId: options.gameId,
      },
    };
  }

  const header =
    "// Generated by dreamboard test generate. Do not edit by hand.\n";
  await writeTextFile(
    path.join(generatedDir, "base-states.generated.ts"),
    `${header}export const BASE_STATES = ${JSON.stringify(baseStates, null, 2)} as const;\n`,
  );
  await writeTextFile(
    path.join(generatedDir, "base-states.generated.d.ts"),
    `${header}export declare const BASE_STATES: Record<string, unknown>;\n`,
  );
  await writeTextFile(
    path.join(generatedDir, "scenario-manifest.generated.ts"),
    `${header}export const SCENARIO_MANIFEST = ${JSON.stringify(
      options.scenarios.map((scenario) => ({
        id: scenario.definition.id,
        filePath: path.relative(generatedDir, scenario.filePath),
        base: scenario.definition.from,
        runners: normalizeScenarioRunners(scenario.definition.runners),
      })),
      null,
      2,
    )} as const;\n`,
  );
  await writeJsonFile(path.join(generatedDir, ".generation-meta.json"), {
    generatedAt: new Date().toISOString(),
    scenarioCount: options.scenarios.length,
    baseStateCount: options.bases.length,
  });
}

async function loadGeneratedBaseStates(
  projectRoot: string,
): Promise<BaseStateFile | null> {
  const filePath = path.join(
    projectRoot,
    "test",
    "generated",
    "base-states.generated.ts",
  );
  if (!(await exists(filePath))) {
    return null;
  }
  const module =
    await importTypeScriptModule<Record<string, unknown>>(filePath);
  return (module.BASE_STATES as BaseStateFile | undefined) ?? null;
}

function validateGeneratedFingerprint(options: {
  generated: BaseStateArtifact["fingerprint"];
  current: BaseStateArtifact["fingerprint"];
}): void {
  const mismatches: string[] = [];
  if (options.generated.baseBundleHash !== options.current.baseBundleHash) {
    mismatches.push("base module changed");
  }
  if (options.generated.manifestHash !== options.current.manifestHash) {
    mismatches.push("manifest changed");
  }
  if (options.generated.appBundleHash !== options.current.appBundleHash) {
    mismatches.push("game reducer bundle changed");
  }
  if (options.generated.uiContractHash !== options.current.uiContractHash) {
    mismatches.push("ui contract changed");
  }
  if (
    options.generated.compiledResultId &&
    options.current.compiledResultId &&
    options.generated.compiledResultId !== options.current.compiledResultId
  ) {
    mismatches.push("compiled result changed");
  }
  if (
    options.generated.gameId &&
    options.current.gameId &&
    options.generated.gameId !== options.current.gameId
  ) {
    mismatches.push("game id changed");
  }
  if (
    options.generated.seed !== options.current.seed ||
    options.generated.players !== options.current.players
  ) {
    mismatches.push("base seed/player count changed");
  }
  if (
    (options.generated.setupProfileId ?? null) !==
    (options.current.setupProfileId ?? null)
  ) {
    mismatches.push("base setup profile changed");
  }
  if (mismatches.length > 0) {
    throw new Error(
      `${mismatches.join("; ")}. Run 'dreamboard test generate' to refresh reducer-native base artifacts.`,
    );
  }
}

async function currentFingerprint(options: {
  projectRoot: string;
  base: LoadedBase;
  compiledResultId?: string;
  gameId?: string;
}): Promise<BaseStateArtifact["fingerprint"]> {
  const manifest = await loadManifest(options.projectRoot);
  const effectiveSetup = resolveEffectiveBaseSetup({
    manifest,
    base: options.base.definition,
  });
  return {
    base: options.base.definition.id,
    seed: options.base.definition.seed,
    players: options.base.definition.players,
    baseBundleHash: options.base.bundleHash,
    manifestHash: hashContent(JSON.stringify(manifest)),
    appBundleHash: hashContent(
      await bundleTypeScriptModuleText(
        path.join(options.projectRoot, "app", "game.ts"),
      ),
    ),
    uiContractHash: hashContent(
      await bundleTypeScriptModuleText(
        path.join(options.projectRoot, "shared", "generated", "ui-contract.ts"),
      ),
    ),
    setupProfileId: effectiveSetup.setupProfileId,
    compiledResultId: options.compiledResultId,
    gameId: options.gameId,
  };
}

export async function generateReducerNativeArtifacts(options: {
  projectRoot: string;
  compiledResultId?: string;
  gameId?: string;
  scenarioPath?: string;
  debug?: boolean;
}): Promise<{
  bases: LoadedBase[];
  scenarios: LoadedScenario[];
}> {
  await ensureReducerNativeTestingFiles(options.projectRoot);
  const [bases, scenarios] = await Promise.all([
    loadTypedBases(options.projectRoot),
    loadTypedScenarios(options.projectRoot, {
      scenarioPath: options.scenarioPath,
    }),
  ]);
  const basesById = new Map(bases.map((base) => [base.definition.id, base]));
  validateTypedScenarioBases(scenarios, basesById);
  await writeReducerNativeGeneratedFiles({
    projectRoot: options.projectRoot,
    bases,
    scenarios,
    compiledResultId: options.compiledResultId,
    gameId: options.gameId,
    debug: options.debug,
  });
  return { bases, scenarios };
}

export async function runReducerNativeScenarios(options: {
  projectRoot: string;
  projectConfig: ProjectConfig;
  resolvedConfig: ResolvedConfig;
  runner: TestRunnerName;
  scenarioPath?: string;
  compiledResultId?: string;
  gameId?: string;
  webBaseUrl?: string;
  debug?: boolean;
}): Promise<ReducerNativeScenarioSummary> {
  await ensureReducerNativeTestingFiles(options.projectRoot);

  const [
    bases,
    scenarios,
    generatedBaseStates,
    manifest,
    gameModule,
    manifestContractModule,
  ] = await Promise.all([
    loadTypedBases(options.projectRoot),
    loadTypedScenarios(options.projectRoot, {
      scenarioPath: options.scenarioPath,
    }),
    loadGeneratedBaseStates(options.projectRoot),
    loadManifest(options.projectRoot),
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "app", "game.ts"),
    ),
    importTypeScriptModule<Record<string, unknown>>(
      path.join(options.projectRoot, "shared", "manifest-contract.ts"),
    ),
  ]);
  const createInitialTable =
    typeof manifestContractModule.createInitialTable === "function"
      ? (manifestContractModule.createInitialTable as GeneratedInitialTableFactory)
      : null;

  const basesById = new Map(bases.map((base) => [base.definition.id, base]));
  validateTypedScenarioBases(scenarios, basesById);

  const runnerScenarios = scenarios.filter((scenario) =>
    normalizeScenarioRunners(scenario.definition.runners).includes(
      options.runner,
    ),
  );

  let embeddedHarness: EmbeddedHarnessSession | null = null;
  let browser: Browser | null = null;
  let page: Page | null = null;
  let browserBridge: BrowserBridgeClient | null = null;
  let browserDriver: BrowserRunnerDriver | null = null;

  if (options.runner === "embedded") {
    embeddedHarness = await startEmbeddedHarnessSession({
      projectRoot: options.projectRoot,
      projectConfig: options.projectConfig,
      configureClient: true,
    });
  }

  if (options.runner === "browser") {
    const webBaseUrl = options.webBaseUrl ?? options.projectConfig.webBaseUrl;
    if (!webBaseUrl) {
      throw new Error(
        "Browser runner requires a local webBaseUrl. Start the local web stack and configure the project for env local.",
      );
    }
    browserDriver = await loadBrowserDriver(options.projectRoot);
    const opened = await openBrowserPage(
      `${webBaseUrl}/_dev`,
      options.resolvedConfig,
    );
    browser = opened.browser;
    page = opened.page;
  }

  try {
    let passed = 0;
    let failed = 0;
    const results: ReducerNativeScenarioResult[] = [];

    for (const scenario of runnerScenarios) {
      const base = basesById.get(scenario.definition.from);
      if (!base) {
        throw new Error(
          `Missing typed base '${scenario.definition.from}' for scenario '${scenario.definition.id}'.`,
        );
      }

      if (generatedBaseStates?.[baseStateKey(base.definition.id)]) {
        validateGeneratedFingerprint({
          generated:
            generatedBaseStates[baseStateKey(base.definition.id)]!.fingerprint,
          current: await currentFingerprint({
            projectRoot: options.projectRoot,
            base,
            compiledResultId: options.compiledResultId,
            gameId: options.gameId,
          }),
        });
      } else if (options.runner !== "reducer") {
        throw new Error(
          "Missing reducer-native generated base artifacts. Run 'dreamboard test generate' first.",
        );
      }

      try {
        const effectiveSetup = resolveEffectiveBaseSetup({
          manifest,
          base: base.definition,
        });
        const shadow = new ShadowReducerRuntime(
          manifest,
          gameModule.default,
          createInitialTable,
          base.definition.seed,
          base.definition.players,
          effectiveSetup.setupProfileId,
          options.debug ?? false,
        );

        let embedded:
          | {
              sessionId: string;
              tracker: EmbeddedGameplayTracker;
            }
          | undefined;
        try {
          if (options.runner === "embedded" && embeddedHarness) {
            const { data: session, error: sessionError } = await createSession({
              path: { gameId: embeddedHarness.gameId },
              body: {
                compiledResultId: embeddedHarness.compiledResultId,
                seed: base.definition.seed,
                playerCount: base.definition.players,
                autoAssignSeats: true,
                setupProfileId: effectiveSetup.setupProfileId ?? undefined,
              },
            });
            if (!session || sessionError) {
              throw new Error("Failed to create embedded harness session.");
            }
            const tracker = new EmbeddedGameplayTracker(session.sessionId);
            const { error: startError } = await startGame({
              path: { sessionId: session.sessionId },
            });
            if (startError) {
              throw new Error("Failed to start embedded harness session.");
            }
            await tracker.connect();
            await tracker.waitForBootstrap();
            embedded = {
              sessionId: session.sessionId,
              tracker,
            };
          }

          if (options.runner === "browser" && page) {
            const gameId = options.gameId ?? options.projectConfig.gameId;
            const compiledResultId =
              options.compiledResultId ??
              options.projectConfig.compile?.latestSuccessful?.resultId;
            if (!compiledResultId) {
              throw new Error(
                "Browser runner requires a compiled result. Compile the workspace first.",
              );
            }
            const { data: session, error: sessionError } = await createSession({
              path: { gameId },
              body: {
                compiledResultId,
                seed: base.definition.seed,
                playerCount: base.definition.players,
                autoAssignSeats: true,
                setupProfileId: effectiveSetup.setupProfileId ?? undefined,
              },
            });
            if (!session || sessionError) {
              throw new Error("Failed to create browser-runner session.");
            }
            const { error: startError, data: started } = await startGame({
              path: { sessionId: session.sessionId },
            });
            if (startError || !started) {
              throw new Error("Failed to start browser-runner session.");
            }
            await page.goto(
              `${options.webBaseUrl ?? options.projectConfig.webBaseUrl}/_dev/play/${started.shortCode}`,
              { waitUntil: "domcontentloaded" },
            );
            await waitForGameReady(page);
            browserBridge = await createBrowserBridgeClient(page);
            await browserDriver?.onReady?.(browserBridge);
          }

          const context = await createScenarioContext({
            runner: options.runner,
            shadow,
            embedded,
            browser:
              options.runner === "browser" && browserBridge
                ? {
                    bridge: browserBridge,
                    driver: browserDriver,
                  }
                : undefined,
          });

          await context.game.start();
          await base.definition.setup({ game: context.game });
          shadow.clearHistory();
          await scenario.definition.when(context);
          await scenario.definition.then(context);
          passed += 1;
          results.push({
            id: scenario.definition.id,
            success: true,
          });
        } finally {
          embedded?.tracker.close();
        }
      } catch (error) {
        failed += 1;
        results.push({
          id: scenario.definition.id,
          success: false,
          error:
            error instanceof Error
              ? error.message
              : `Scenario '${scenario.definition.id}' failed.`,
        });
      }
    }

    return { passed, failed, results };
  } finally {
    if (embeddedHarness) {
      await embeddedHarness.stop();
    }
    if (browser) {
      await browser.close();
    }
  }
}
