/**
 * Generated by apps/dreamboard-cli/scripts/sync-scaffold-ownership.ts.
 * Source: packages/sdk-types/scaffolding/ownership.json
 * Do not edit manually.
 */

export type OwnershipPattern = {
  prefix: string;
  suffix: string;
};

export type ScaffoldingOwnership = {
  version: number;
  allowedPaths: {
    rootFiles: string[];
    directoryPrefixes: string[];
  };
  dynamic: {
    generatedFiles: string[];
    seedFiles: string[];
    seedFilePatterns: OwnershipPattern[];
  };
  cliStatic: {
    exactFiles: string[];
    directoryPrefixes: string[];
  };
  preservedUserFiles: string[];
};

export const SCAFFOLD_OWNERSHIP: ScaffoldingOwnership = {
  version: 2,
  allowedPaths: {
    rootFiles: ["package.json", "manifest.json", "rule.md"],
    directoryPrefixes: ["app/", "ui/", "shared/", "test/"],
  },
  dynamic: {
    generatedFiles: [
      "shared/manifest.ts",
      "app/generated/guards.ts",
      "app/index.ts",
    ],
    seedFiles: ["shared/ui-args.ts", "ui/App.tsx"],
    seedFilePatterns: [
      {
        prefix: "app/phases/",
        suffix: ".ts",
      },
    ],
  },
  cliStatic: {
    exactFiles: [
      "package.json",
      "shared/game-message.d.ts",
      "shared/index.ts",
      "app/tsconfig.json",
      "ui/index.tsx",
      "ui/tsconfig.json",
      "ui/package.json",
    ],
    directoryPrefixes: ["app/sdk/", "ui/sdk/"],
  },
  preservedUserFiles: ["shared/ui-args.ts"],
};
