import { readdir, unlink } from "node:fs/promises";
import path from "node:path";
import { STATIC_SCAFFOLD_FILES } from "../../scaffold/static/static-files.generated.js";
import { TESTING_TYPES_CONTENT } from "../../templates/testing-types-content.js";
import {
  ensureDir,
  exists,
  readTextFile,
  readTextFileIfExists,
  writeTextFile,
} from "../../utils/fs.js";

type StaticScaffoldMode = "new" | "update";
const SDK_PATH_PREFIX = "ui/sdk/";
const DREAMBOARD_SYNC_COMMAND = "dreamboard sync";
const TESTING_TYPES_STUB =
  "export function defineScenario(scenario) { return scenario; }\n";
const GENERATED_TESTING_TYPES_PREFIX = "// Generated by dreamboard";

export interface StaticScaffoldOptions {
  updateSdk?: boolean;
}

export async function scaffoldStaticWorkspace(
  projectRoot: string,
  mode: StaticScaffoldMode,
  options: StaticScaffoldOptions = {},
): Promise<void> {
  const updateSdk = options.updateSdk ?? mode === "new";

  await writeFrameworkStaticFiles(projectRoot, mode, updateSdk);

  const testDir = path.join(projectRoot, "test");
  const scenariosDir = path.join(testDir, "scenarios");
  const generatedDir = path.join(testDir, "generated");

  await ensureDir(scenariosDir);
  await ensureDir(generatedDir);

  await writeTestReadme(path.join(testDir, "README.md"));
  await writeBaseScenarios(path.join(testDir, "base-scenarios.json"), mode);
  await writeTestingTypes(path.join(testDir, "testing-types.ts"), mode);
  await writeTestTsconfig(path.join(testDir, "tsconfig.json"));

  const staleDtsPath = path.join(testDir, "testing-types.d.ts");
  if (await exists(staleDtsPath)) {
    await unlink(staleDtsPath);
  }

  await migrateLegacyScenarioImports(projectRoot);
}

export async function collectModifiedStaticSdkFiles(
  projectRoot: string,
): Promise<string[]> {
  const modifiedSdkFiles: string[] = [];

  for (const entry of STATIC_SCAFFOLD_FILES) {
    if (!entry.targetPath.startsWith(SDK_PATH_PREFIX)) continue;

    const fullPath = path.join(projectRoot, entry.targetPath);
    const existingContent = await readTextFileIfExists(fullPath);

    if (existingContent === null) continue;
    if (existingContent.trim().length === 0) continue;
    if (existingContent !== entry.content) {
      modifiedSdkFiles.push(entry.targetPath);
    }
  }

  modifiedSdkFiles.sort();
  return modifiedSdkFiles;
}

export async function assertCliStaticScaffoldComplete(
  projectRoot: string,
  deletedPaths: readonly string[] = [],
): Promise<void> {
  const missingOrBlankPaths: string[] = [];

  for (const entry of STATIC_SCAFFOLD_FILES) {
    const fullPath = path.join(projectRoot, entry.targetPath);
    const content = await readTextFileIfExists(fullPath);

    if (content === null || content.trim().length === 0) {
      missingOrBlankPaths.push(entry.targetPath);
    }
  }

  const staticPaths = new Set(
    STATIC_SCAFFOLD_FILES.map((entry) => entry.targetPath),
  );
  const deletedStaticPaths = deletedPaths
    .map(normalizeProjectPath)
    .filter((filePath) => staticPaths.has(filePath))
    .sort();

  if (missingOrBlankPaths.length === 0 && deletedStaticPaths.length === 0) {
    return;
  }

  const problems: string[] = [];
  if (missingOrBlankPaths.length > 0) {
    problems.push(
      `missing or blank: ${summarizePaths(missingOrBlankPaths.sort())}`,
    );
  }
  if (deletedStaticPaths.length > 0) {
    problems.push(`deleted: ${summarizePaths(deletedStaticPaths)}`);
  }

  throw new Error(
    `CLI static scaffold is incomplete (${problems.join("; ")}). Run \`${DREAMBOARD_SYNC_COMMAND}\` to restore the missing static files before compiling.`,
  );
}

async function writeFrameworkStaticFiles(
  projectRoot: string,
  mode: StaticScaffoldMode,
  updateSdk: boolean,
): Promise<void> {
  for (const entry of STATIC_SCAFFOLD_FILES) {
    const fullPath = path.join(projectRoot, entry.targetPath);
    const existingContent = await readTextFileIfExists(fullPath);

    const shouldWrite =
      mode === "new" ||
      !entry.targetPath.startsWith(SDK_PATH_PREFIX) ||
      updateSdk ||
      existingContent === null ||
      existingContent.trim().length === 0;

    if (!shouldWrite) continue;

    await writeTextFile(fullPath, entry.content);
  }
}

async function writeTestReadme(filePath: string): Promise<void> {
  await writeTextFile(
    filePath,
    "# Dreamboard Test Workspace\n\nTypeScript scenarios live in `test/scenarios/*.scenario.ts`.\n\n1. (Optional) Define custom base checkpoints in `test/base-scenarios.json`.\n2. Add at least one `initial-state` scenario with `when.steps: []` so you can assert structural invariants before any actions.\n3. Generate deterministic base snapshots: `dreamboard test generate`.\n4. Run tests: `dreamboard test run`.\n\nImport `defineScenario`, `getNormalizedHands`, and `getNormalizedDecks` from `../testing-types` inside scenario files.\n\nGenerated artifacts are written to `test/generated/*` and should not be edited manually.\n",
  );
}

async function writeBaseScenarios(
  filePath: string,
  mode: StaticScaffoldMode,
): Promise<void> {
  if (mode === "update" && (await exists(filePath))) {
    const existing = await readTextFileIfExists(filePath);
    if (existing !== null && existing.trim().length > 0) {
      return;
    }
  }

  await writeTextFile(
    filePath,
    `${JSON.stringify(
      {
        "initial-turn": {
          seed: 1337,
          players: 4,
          steps: [],
        },
      },
      null,
      2,
    )}\n`,
  );
}

async function writeTestingTypes(
  filePath: string,
  mode: StaticScaffoldMode,
): Promise<void> {
  if (mode === "new") {
    await writeTextFile(filePath, TESTING_TYPES_CONTENT);
    return;
  }

  const existing = await readTextFileIfExists(filePath);
  if (shouldRefreshGeneratedTestingTypes(existing)) {
    await writeTextFile(filePath, TESTING_TYPES_CONTENT);
  }
}

async function writeTestTsconfig(filePath: string): Promise<void> {
  await writeTextFile(
    filePath,
    `${JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          noEmit: true,
        },
        include: [
          "./**/*.ts",
          "./**/*.d.ts",
          "../shared/**/*.ts",
          "../shared/**/*.d.ts",
        ],
      },
      null,
      2,
    )}\n`,
  );
}

export async function migrateLegacyScenarioImports(
  projectRoot: string,
): Promise<void> {
  const scenariosRoot = path.join(projectRoot, "test", "scenarios");
  if (!(await exists(scenariosRoot))) return;

  const scenarioFiles = await collectScenarioFiles(scenariosRoot);
  for (const filePath of scenarioFiles) {
    const content = await readTextFile(filePath);
    if (!content.includes("@dreamboard/cli/testing")) continue;

    const relativeToTestingTypes = normalizeImportPath(
      path.relative(
        path.dirname(filePath),
        path.join(projectRoot, "test", "testing-types"),
      ),
    );

    const migrated = content
      .replaceAll('"@dreamboard/cli/testing"', `"${relativeToTestingTypes}"`)
      .replaceAll("'@dreamboard/cli/testing'", `'${relativeToTestingTypes}'`);

    if (migrated !== content) {
      await writeTextFile(filePath, migrated);
    }
  }
}

function shouldRefreshGeneratedTestingTypes(
  existingContent: string | null,
): boolean {
  if (existingContent === null || existingContent.trim().length === 0) {
    return true;
  }
  if (existingContent === TESTING_TYPES_STUB) {
    return true;
  }
  return existingContent.startsWith(GENERATED_TESTING_TYPES_PREFIX);
}

async function collectScenarioFiles(rootDir: string): Promise<string[]> {
  const files: string[] = [];
  const stack = [rootDir];

  while (stack.length > 0) {
    const dir = stack.pop();
    if (!dir) continue;

    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
      } else if (entry.isFile() && entry.name.endsWith(".ts")) {
        files.push(fullPath);
      }
    }
  }

  return files;
}

function normalizeImportPath(relativePath: string): string {
  const normalized = relativePath.replaceAll("\\", "/");
  if (normalized.startsWith(".")) return normalized;
  return `./${normalized}`;
}

function normalizeProjectPath(filePath: string): string {
  return filePath.replace(/^\.\//, "").replace(/^\/+/, "").replace(/\\/g, "/");
}

function summarizePaths(paths: readonly string[]): string {
  const maxShown = 5;
  const shown = paths.slice(0, maxShown).join(", ");
  if (paths.length <= maxShown) return shown;
  return `${shown}, and ${paths.length - maxShown} more`;
}
