import { existsSync, readFileSync } from "node:fs";
import { readdir, readFile, rm, unlink } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { REDUCER_TESTING_TYPES_WRAPPER_CONTENT } from "../../templates/testing-types-content.js";
import {
  ensureDir,
  exists,
  readTextFile,
  readTextFileIfExists,
  writeTextFile,
} from "../../utils/fs.js";
import { isDynamicSeedPath } from "./scaffold-ownership.js";

type StaticScaffoldMode = "new" | "update";
type StaticAssetEntry = {
  targetPath: string;
  content: string;
};

const DREAMBOARD_SYNC_COMMAND = "dreamboard sync";
const TESTING_TYPES_STUB =
  "export function defineScenario(scenario) { return scenario; }\n";
const GENERATED_TESTING_TYPES_PREFIX = "// Generated by dreamboard";
const STATIC_ASSET_ROOT = resolveStaticAssetRoot();
const require = createRequire(import.meta.url);
const SDK_DEPENDENCY_RANGES = {
  "@dreamboard/app-sdk": buildSdkDependencyRange("@dreamboard/app-sdk"),
  "@dreamboard/sdk-types": buildSdkDependencyRange("@dreamboard/sdk-types"),
  "@dreamboard/ui-sdk": buildSdkDependencyRange("@dreamboard/ui-sdk"),
} as const;

const SHARED_DEPENDENCIES = `
"react": "^19.2.0",
"react-dom": "^19.2.0",
"framer-motion": "^12.23.24",
"motion-dom": "^12.23.23",
"motion-utils": "^12.23.6",
"lucide-react": "^0.562.0",
"clsx": "^2.1.1",
"vaul": "^1.1.2",
"zod": "^4.1.5",
"@use-gesture/react": "^10.3.1",
"@use-gesture/core": "^10.3.1"
`.trim();

const SHARED_DEV_DEPENDENCIES = `
"typescript": "^5.9.2",
"@types/react": "^19.0.0",
"@types/react-dom": "^19.0.0",
"csstype": "^3.1.3"
`.trim();

export async function scaffoldStaticWorkspace(
  projectRoot: string,
  mode: StaticScaffoldMode,
): Promise<void> {
  await writeFrameworkStaticFiles(projectRoot, mode);
  await removeLegacyVendoredSdkPaths(projectRoot);

  const testDir = path.join(projectRoot, "test");
  const basesDir = path.join(testDir, "bases");
  const scenariosDir = path.join(testDir, "scenarios");
  const generatedDir = path.join(testDir, "generated");

  await ensureDir(basesDir);
  await ensureDir(scenariosDir);
  await ensureDir(generatedDir);

  await writeTestReadme(path.join(testDir, "README.md"));
  await writeInitialBase(path.join(basesDir, "initial-turn.base.ts"), mode);
  await writeTestingTypes(path.join(testDir, "testing-types.ts"), mode);
  await writeTestTsconfig(path.join(testDir, "tsconfig.json"));

  const staleDtsPath = path.join(testDir, "testing-types.d.ts");
  if (await exists(staleDtsPath)) {
    await unlink(staleDtsPath);
  }
  const staleBaseScenariosPath = path.join(testDir, "base-scenarios.json");
  if (await exists(staleBaseScenariosPath)) {
    await unlink(staleBaseScenariosPath);
  }

  await migrateLegacyScenarioImports(projectRoot);
}

export async function assertCliStaticScaffoldComplete(
  projectRoot: string,
  deletedPaths: readonly string[] = [],
): Promise<void> {
  const expectedEntries = await getExpectedStaticEntries();
  const missingOrBlankPaths: string[] = [];

  for (const entry of expectedEntries) {
    const fullPath = path.join(projectRoot, entry.targetPath);
    const content = await readTextFileIfExists(fullPath);

    if (content === null || content.trim().length === 0) {
      missingOrBlankPaths.push(entry.targetPath);
    }
  }

  const staticPaths = new Set(expectedEntries.map((entry) => entry.targetPath));
  const deletedStaticPaths = deletedPaths
    .map(normalizeProjectPath)
    .filter((filePath) => staticPaths.has(filePath))
    .sort();

  if (missingOrBlankPaths.length === 0 && deletedStaticPaths.length === 0) {
    return;
  }

  const problems: string[] = [];
  if (missingOrBlankPaths.length > 0) {
    problems.push(
      `missing or blank: ${summarizePaths(missingOrBlankPaths.sort())}`,
    );
  }
  if (deletedStaticPaths.length > 0) {
    problems.push(`deleted: ${summarizePaths(deletedStaticPaths)}`);
  }

  throw new Error(
    `CLI static scaffold is incomplete (${problems.join("; ")}). Run \`${DREAMBOARD_SYNC_COMMAND}\` to restore the missing static files before compiling.`,
  );
}

async function writeFrameworkStaticFiles(
  projectRoot: string,
  mode: StaticScaffoldMode,
): Promise<void> {
  const assetEntries = await getStaticAssetEntries();

  for (const entry of assetEntries) {
    const fullPath = path.join(projectRoot, entry.targetPath);
    // Seed files (e.g. ui/App.tsx) are user-customizable: only write them on
    // first scaffold; preserve existing content on subsequent updates.
    if (mode === "update" && isDynamicSeedPath(entry.targetPath)) {
      const existing = await readTextFileIfExists(fullPath);
      if (existing !== null && existing.trim().length > 0) {
        continue;
      }
    }
    await writeTextFile(fullPath, entry.content);
  }

  for (const entry of await getDynamicStaticEntries()) {
    await writeTextFile(
      path.join(projectRoot, entry.targetPath),
      entry.content,
    );
  }
}

async function removeLegacyVendoredSdkPaths(
  projectRoot: string,
): Promise<void> {
  await rm(path.join(projectRoot, "app", "sdk"), {
    recursive: true,
    force: true,
  });
  await rm(path.join(projectRoot, "ui", "sdk"), {
    recursive: true,
    force: true,
  });
}

async function writeTestReadme(filePath: string): Promise<void> {
  await writeTextFile(
    filePath,
    "# Dreamboard Test Workspace\n\nTypeScript bases live in `test/bases/*.base.ts` and scenarios live in `test/scenarios/*.scenario.ts`.\n\n1. Define reusable seeded bases with `defineBase({ id, seed, players, setup })`.\n2. Define scenarios with `defineScenario({ id, from, when, then })`.\n3. Scenario assertions can read `players()`, `state()`, `view(playerId)`, `prompts(playerId)`, and `windows(playerId)`.\n4. Generate deterministic base snapshots: `dreamboard test generate`.\n5. Run tests: `dreamboard test run`.\n\nImport test helpers from `../testing-types`.\n\nGenerated artifacts are written to `test/generated/*` and should not be edited manually.\n",
  );
}

async function writeInitialBase(
  filePath: string,
  mode: StaticScaffoldMode,
): Promise<void> {
  if (mode === "update") {
    return;
  }

  await writeTextFile(
    filePath,
    `import { defineBase } from "../testing-types";

export default defineBase({
  id: "initial-turn",
  seed: 1337,
  players: 4,
  setup: async () => undefined,
});
`,
  );
}

async function writeTestingTypes(
  filePath: string,
  mode: StaticScaffoldMode,
): Promise<void> {
  if (mode === "new") {
    await writeTextFile(filePath, REDUCER_TESTING_TYPES_WRAPPER_CONTENT);
    return;
  }

  const existing = await readTextFileIfExists(filePath);
  if (shouldRefreshGeneratedTestingTypes(existing)) {
    await writeTextFile(filePath, REDUCER_TESTING_TYPES_WRAPPER_CONTENT);
  }
}

async function writeTestTsconfig(filePath: string): Promise<void> {
  await writeTextFile(
    filePath,
    `${JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          noEmit: true,
        },
        include: [
          "./**/*.ts",
          "./**/*.d.ts",
          "../shared/**/*.ts",
          "../shared/**/*.d.ts",
        ],
      },
      null,
      2,
    )}\n`,
  );
}

export async function migrateLegacyScenarioImports(
  projectRoot: string,
): Promise<void> {
  const scenariosRoot = path.join(projectRoot, "test", "scenarios");
  if (!(await exists(scenariosRoot))) return;

  const scenarioFiles = await collectScenarioFiles(scenariosRoot);
  for (const filePath of scenarioFiles) {
    const content = await readTextFile(filePath);
    if (!content.includes("@dreamboard/cli/testing")) continue;

    const relativeToTestingTypes = normalizeImportPath(
      path.relative(
        path.dirname(filePath),
        path.join(projectRoot, "test", "testing-types"),
      ),
    );

    const migrated = content
      .replaceAll('"@dreamboard/cli/testing"', `"${relativeToTestingTypes}"`)
      .replaceAll("'@dreamboard/cli/testing'", `'${relativeToTestingTypes}'`);

    if (migrated !== content) {
      await writeTextFile(filePath, migrated);
    }
  }
}

function shouldRefreshGeneratedTestingTypes(
  existingContent: string | null,
): boolean {
  if (existingContent === null || existingContent.trim().length === 0) {
    return true;
  }
  if (existingContent === TESTING_TYPES_STUB) {
    return true;
  }
  return existingContent.startsWith(GENERATED_TESTING_TYPES_PREFIX);
}

async function collectScenarioFiles(rootDir: string): Promise<string[]> {
  const files: string[] = [];
  const stack = [rootDir];

  while (stack.length > 0) {
    const dir = stack.pop();
    if (!dir) continue;

    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
      } else if (entry.isFile() && entry.name.endsWith(".ts")) {
        files.push(fullPath);
      }
    }
  }

  return files;
}

export function resolveStaticAssetRoot(
  importUrl: string = import.meta.url,
): string {
  const candidates = [
    fileURLToPath(new URL("../../scaffold/assets/static/", importUrl)),
    fileURLToPath(new URL("./scaffold/assets/static/", importUrl)),
    fileURLToPath(new URL("../scaffold/assets/static/", importUrl)),
  ];

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  throw new Error(
    `Unable to locate CLI static scaffold assets. Checked: ${candidates.join(", ")}`,
  );
}

async function getStaticAssetEntries(): Promise<StaticAssetEntry[]> {
  const files = await walkFiles(STATIC_ASSET_ROOT);
  const entries: StaticAssetEntry[] = [];

  for (const filePath of files) {
    const targetPath = normalizeProjectPath(
      path.relative(STATIC_ASSET_ROOT, filePath),
    );
    entries.push({
      targetPath,
      content: await readFile(filePath, "utf8"),
    });
  }

  entries.sort((left, right) =>
    left.targetPath.localeCompare(right.targetPath),
  );
  return entries;
}

async function getDynamicStaticEntries(): Promise<StaticAssetEntry[]> {
  return [
    {
      targetPath: "package.json",
      content: buildRootPackageJson(),
    },
    {
      targetPath: "ui/package.json",
      content: buildUiPackageJson(),
    },
  ];
}

async function getExpectedStaticEntries(): Promise<StaticAssetEntry[]> {
  const entries = [
    ...(await getStaticAssetEntries()),
    ...(await getDynamicStaticEntries()),
  ];
  entries.sort((left, right) =>
    left.targetPath.localeCompare(right.targetPath),
  );
  return entries;
}

async function walkFiles(rootDir: string): Promise<string[]> {
  const files: string[] = [];
  const stack = [rootDir];

  while (stack.length > 0) {
    const currentDir = stack.pop();
    if (!currentDir) continue;

    const entries = await readdir(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
      } else if (entry.isFile()) {
        files.push(fullPath);
      }
    }
  }

  files.sort((left, right) => left.localeCompare(right));
  return files;
}

function buildRootPackageJson(): string {
  return `{
  "private": true,
  "scripts": {
    "dev": "dreamboard dev",
    "typecheck": "tsc --noEmit -p app/tsconfig.json && tsc --noEmit -p ui/tsconfig.json",
    "typecheck:app": "tsc --noEmit -p app/tsconfig.json",
    "typecheck:ui": "tsc --noEmit -p ui/tsconfig.json"
  },
  "dependencies": {
    "@dreamboard/app-sdk": "${SDK_DEPENDENCY_RANGES["@dreamboard/app-sdk"]}",
    "@dreamboard/ui-sdk": "${SDK_DEPENDENCY_RANGES["@dreamboard/ui-sdk"]}",
${prependIndent(SHARED_DEPENDENCIES, "    ")}
  },
  "devDependencies": {
    "@dreamboard/sdk-types": "${SDK_DEPENDENCY_RANGES["@dreamboard/sdk-types"]}",
${prependIndent(SHARED_DEV_DEPENDENCIES, "    ")}
  }
}
`;
}

function buildUiPackageJson(): string {
  return `{
  "private": true,
  "dependencies": {
${prependIndent(SHARED_DEPENDENCIES, "    ")}
  },
  "devDependencies": {
${prependIndent(SHARED_DEV_DEPENDENCIES, "    ")}
  }
}
`;
}

function prependIndent(text: string, indent: string): string {
  return text
    .split("\n")
    .map((line) => `${indent}${line}`)
    .join("\n");
}

function buildSdkDependencyRange(packageName: string): string {
  const packageJsonPath = require.resolve(`${packageName}/package.json`);
  const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8")) as {
    version?: unknown;
  };

  if (
    typeof packageJson.version !== "string" ||
    packageJson.version.trim().length === 0
  ) {
    throw new Error(`Missing version in ${packageName}/package.json`);
  }

  return `^${packageJson.version.trim()}`;
}

function normalizeImportPath(relativePath: string): string {
  const normalized = relativePath.replaceAll("\\", "/");
  if (normalized.startsWith(".")) return normalized;
  return `./${normalized}`;
}

function normalizeProjectPath(filePath: string): string {
  return filePath.replace(/^\.\//, "").replace(/^\/+/, "").replace(/\\/g, "/");
}

function summarizePaths(paths: readonly string[]): string {
  const maxShown = 5;
  const shown = paths.slice(0, maxShown).join(", ");
  if (paths.length <= maxShown) return shown;
  return `${shown}, and ${paths.length - maxShown} more`;
}
