import { existsSync, readFileSync } from "node:fs";
import { readdir, readFile, rm, unlink } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { GameTopologyManifest } from "@dreamboard/sdk-types";
import { REDUCER_TESTING_TYPES_WRAPPER_CONTENT } from "../../templates/testing-types-content.js";
import {
  MANIFEST_TYPECHECK_CONFIG_FILE,
  PROJECT_CONFIG_FILE,
  PROJECT_DIR_NAME,
} from "../../constants.js";
import type { LocalMaintainerRegistryConfig } from "../../types.js";
import {
  ensureDir,
  exists,
  readJsonFile,
  readTextFile,
  readTextFileIfExists,
  writeTextFile,
} from "../../utils/fs.js";
import { resolveCliRepoRoot } from "../../utils/repo-root.js";
import { materializeManifest } from "./manifest-authoring.js";
import { isDynamicSeedPath } from "./scaffold-ownership.js";

type StaticScaffoldMode = "new" | "update";
type StaticAssetEntry = {
  targetPath: string;
  content: string;
};
type StaticScaffoldOptions = {
  localMaintainerRegistry?: LocalMaintainerRegistryConfig | null;
};
type RootPackageJsonShape = {
  private?: boolean;
  packageManager?: string;
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  overrides?: Record<string, unknown>;
  pnpm?: Record<string, unknown>;
  [key: string]: unknown;
};

const DREAMBOARD_SYNC_COMMAND = "dreamboard sync";
const TESTING_TYPES_STUB =
  "export function defineScenario(scenario) { return scenario; }\n";
const GENERATED_TESTING_TYPES_PREFIX = "// Generated by dreamboard";
const GENERATED_SCENARIO_PREFIX = "// Generated by dreamboard scaffold.";
const INITIAL_SCENARIO_CONTENT = `${GENERATED_SCENARIO_PREFIX}
import { defineScenario } from "../testing-types";

export default defineScenario({
  id: "smoke-initial-turn",
  description:
    "Sanity check that the scaffolded workspace boots into its initial phase.",
  from: "initial-turn",
  when: async () => undefined,
  then: ({ expect, players, prompts, state }) => {
    const playerIds = players();
    expect(playerIds.length).toBeGreaterThanOrEqual(1);
    expect(state()).toBe("setup");
    for (const playerId of playerIds) {
      expect(prompts(playerId)).toEqual([]);
    }
  },
});
`;
const STATIC_ASSET_ROOT = resolveStaticAssetRoot();
const SDK_PACKAGE_PATHS = {
  "@dreamboard/app-sdk": ["packages", "app-sdk", "package.json"],
  "@dreamboard/sdk-types": ["packages", "sdk-types", "package.json"],
  "@dreamboard/ui-sdk": ["packages", "ui-sdk", "package.json"],
} as const;
const DEFAULT_SDK_DEPENDENCY_RANGES = {
  "@dreamboard/app-sdk": "^0.0.40",
  "@dreamboard/sdk-types": "^0.1.0",
  "@dreamboard/ui-sdk": "^0.0.40",
} as const;
const SDK_DEPENDENCY_RANGES = {
  "@dreamboard/app-sdk": resolveSdkDependencyRange("@dreamboard/app-sdk"),
  "@dreamboard/sdk-types": resolveSdkDependencyRange("@dreamboard/sdk-types"),
  "@dreamboard/ui-sdk": resolveSdkDependencyRange("@dreamboard/ui-sdk"),
} as const;

const FRAMEWORK_SCRIPTS = {
  dev: "dreamboard dev",
  typecheck: `tsc --noEmit -p ${MANIFEST_TYPECHECK_CONFIG_FILE} && tsc --noEmit -p app/tsconfig.json && tsc --noEmit -p ui/tsconfig.json`,
  "typecheck:manifest": `tsc --noEmit -p ${MANIFEST_TYPECHECK_CONFIG_FILE}`,
  "typecheck:app": "tsc --noEmit -p app/tsconfig.json",
  "typecheck:ui": "tsc --noEmit -p ui/tsconfig.json",
} as const;
const SHARED_DEPENDENCIES = {
  react: "^19.2.0",
  "react-dom": "^19.2.0",
  "framer-motion": "^12.23.24",
  "motion-dom": "^12.23.23",
  "motion-utils": "^12.23.6",
  "lucide-react": "^0.562.0",
  clsx: "^2.1.1",
  vaul: "^1.1.2",
  zod: "^4.1.5",
  "@use-gesture/react": "^10.3.1",
  "@use-gesture/core": "^10.3.1",
} as const;
const SHARED_DEV_DEPENDENCIES = {
  typescript: "^5.9.2",
  "@types/react": "^19.0.0",
  "@types/react-dom": "^19.0.0",
  csstype: "^3.1.3",
} as const;

export async function scaffoldStaticWorkspace(
  projectRoot: string,
  mode: StaticScaffoldMode,
  options: StaticScaffoldOptions = {},
): Promise<void> {
  await writeFrameworkStaticFiles(projectRoot, mode, options);
  await writeManifestTypecheckTsconfig(
    path.join(projectRoot, MANIFEST_TYPECHECK_CONFIG_FILE),
  );
  await removeLegacyVendoredSdkPaths(projectRoot);

  const testDir = path.join(projectRoot, "test");
  const basesDir = path.join(testDir, "bases");
  const scenariosDir = path.join(testDir, "scenarios");
  const generatedDir = path.join(testDir, "generated");

  await ensureDir(basesDir);
  await ensureDir(scenariosDir);
  await ensureDir(generatedDir);

  await writeTestReadme(path.join(testDir, "README.md"));
  const initialTestPlayerCount = await inferInitialTestPlayerCount(projectRoot);
  await writeInitialBase(
    path.join(basesDir, "initial-turn.base.ts"),
    mode,
    initialTestPlayerCount,
  );
  await writeInitialScenario(
    path.join(scenariosDir, "smoke-initial-turn.scenario.ts"),
    mode,
  );
  await writeTestingTypes(path.join(testDir, "testing-types.ts"), mode);
  await writeTestTsconfig(path.join(testDir, "tsconfig.json"));

  const staleDtsPath = path.join(testDir, "testing-types.d.ts");
  if (await exists(staleDtsPath)) {
    await unlink(staleDtsPath);
  }
  const staleBaseScenariosPath = path.join(testDir, "base-scenarios.json");
  if (await exists(staleBaseScenariosPath)) {
    await unlink(staleBaseScenariosPath);
  }

  await migrateLegacyScenarioImports(projectRoot);
}

export async function assertCliStaticScaffoldComplete(
  projectRoot: string,
  deletedPaths: readonly string[] = [],
): Promise<void> {
  const expectedEntries = await getExpectedStaticEntries(projectRoot);
  const missingOrBlankPaths: string[] = [];

  for (const entry of expectedEntries) {
    const fullPath = path.join(projectRoot, entry.targetPath);
    const content = await readTextFileIfExists(fullPath);

    if (content === null || content.trim().length === 0) {
      missingOrBlankPaths.push(entry.targetPath);
    }
  }

  const staticPaths = new Set(expectedEntries.map((entry) => entry.targetPath));
  const deletedStaticPaths = deletedPaths
    .map(normalizeProjectPath)
    .filter((filePath) => staticPaths.has(filePath))
    .sort();

  if (missingOrBlankPaths.length === 0 && deletedStaticPaths.length === 0) {
    return;
  }

  const problems: string[] = [];
  if (missingOrBlankPaths.length > 0) {
    problems.push(
      `missing or blank: ${summarizePaths(missingOrBlankPaths.sort())}`,
    );
  }
  if (deletedStaticPaths.length > 0) {
    problems.push(`deleted: ${summarizePaths(deletedStaticPaths)}`);
  }

  throw new Error(
    `CLI static scaffold is incomplete (${problems.join("; ")}). Run \`${DREAMBOARD_SYNC_COMMAND}\` to restore the missing static files before compiling.`,
  );
}

async function writeFrameworkStaticFiles(
  projectRoot: string,
  mode: StaticScaffoldMode,
  options: StaticScaffoldOptions,
): Promise<void> {
  const assetEntries = await getStaticAssetEntries();

  for (const entry of assetEntries) {
    const fullPath = path.join(projectRoot, entry.targetPath);
    // Seed files (e.g. ui/App.tsx) are user-customizable: only write them on
    // first scaffold; preserve existing content on subsequent updates.
    if (mode === "update" && isDynamicSeedPath(entry.targetPath)) {
      const existing = await readTextFileIfExists(fullPath);
      if (existing !== null && existing.trim().length > 0) {
        continue;
      }
    }
    await writeTextFile(fullPath, entry.content);
  }

  for (const entry of await getDynamicStaticEntries(
    projectRoot,
    mode,
    options,
  )) {
    await writeTextFile(
      path.join(projectRoot, entry.targetPath),
      entry.content,
    );
  }

  if (!options.localMaintainerRegistry) {
    await rm(path.join(projectRoot, ".npmrc"), { force: true });
  }
}

async function removeLegacyVendoredSdkPaths(
  projectRoot: string,
): Promise<void> {
  await rm(path.join(projectRoot, "app", "sdk"), {
    recursive: true,
    force: true,
  });
  await rm(path.join(projectRoot, "ui", "sdk"), {
    recursive: true,
    force: true,
  });
}

async function writeTestReadme(filePath: string): Promise<void> {
  await writeTextFile(
    filePath,
    "# Dreamboard Test Workspace\n\nTypeScript bases live in `test/bases/*.base.ts` and scenarios live in `test/scenarios/*.scenario.ts`.\n\n1. Define reusable seeded bases with `defineBase({ id, seed, players, setupProfileId?, setup })`.\n2. Define scenarios with `defineScenario({ id, from, when, then })`.\n3. Scenario assertions can read `players()`, `state()`, `view(playerId)`, and `prompts(playerId)`.\n4. Generate deterministic base snapshots: `dreamboard test generate`.\n5. Run tests: `dreamboard test run`.\n\nImport test helpers from `../testing-types`.\n\nGenerated artifacts are written to `test/generated/*` and should not be edited manually.\n",
  );
}

async function writeInitialBase(
  filePath: string,
  mode: StaticScaffoldMode,
  players: number,
): Promise<void> {
  if (mode === "update") {
    return;
  }

  await writeTextFile(
    filePath,
    `import { defineBase } from "../testing-types";

export default defineBase({
  id: "initial-turn",
  seed: 1337,
  players: ${players},
  setup: async () => undefined,
});
`,
  );
}

async function writeInitialScenario(
  filePath: string,
  mode: StaticScaffoldMode,
): Promise<void> {
  if (mode === "new") {
    await writeTextFile(filePath, INITIAL_SCENARIO_CONTENT);
    return;
  }

  const existing = await readTextFileIfExists(filePath);
  if (
    existing === null ||
    existing.trim().length === 0 ||
    existing === INITIAL_SCENARIO_CONTENT
  ) {
    await writeTextFile(filePath, INITIAL_SCENARIO_CONTENT);
  }
}

async function writeTestingTypes(
  filePath: string,
  mode: StaticScaffoldMode,
): Promise<void> {
  if (mode === "new") {
    await writeTextFile(filePath, REDUCER_TESTING_TYPES_WRAPPER_CONTENT);
    return;
  }

  const existing = await readTextFileIfExists(filePath);
  if (shouldRefreshGeneratedTestingTypes(existing)) {
    await writeTextFile(filePath, REDUCER_TESTING_TYPES_WRAPPER_CONTENT);
  }
}

async function writeTestTsconfig(filePath: string): Promise<void> {
  await writeTextFile(
    filePath,
    `${JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          noEmit: true,
        },
        include: [
          "./**/*.ts",
          "./**/*.d.ts",
          "../shared/**/*.ts",
          "../shared/**/*.d.ts",
        ],
      },
      null,
      2,
    )}\n`,
  );
}

async function writeManifestTypecheckTsconfig(filePath: string): Promise<void> {
  await writeTextFile(
    filePath,
    `${JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          noEmit: true,
          allowImportingTsExtensions: true,
        },
        include: ["./manifest.ts"],
      },
      null,
      2,
    )}\n`,
  );
}

export async function migrateLegacyScenarioImports(
  projectRoot: string,
): Promise<void> {
  const scenariosRoot = path.join(projectRoot, "test", "scenarios");
  if (!(await exists(scenariosRoot))) return;

  const scenarioFiles = await collectScenarioFiles(scenariosRoot);
  for (const filePath of scenarioFiles) {
    const content = await readTextFile(filePath);
    if (!content.includes("@dreamboard/cli/testing")) continue;

    const relativeToTestingTypes = normalizeImportPath(
      path.relative(
        path.dirname(filePath),
        path.join(projectRoot, "test", "testing-types"),
      ),
    );

    const migrated = content
      .replaceAll('"@dreamboard/cli/testing"', `"${relativeToTestingTypes}"`)
      .replaceAll("'@dreamboard/cli/testing'", `'${relativeToTestingTypes}'`);

    if (migrated !== content) {
      await writeTextFile(filePath, migrated);
    }
  }
}

function shouldRefreshGeneratedTestingTypes(
  existingContent: string | null,
): boolean {
  if (existingContent === null || existingContent.trim().length === 0) {
    return true;
  }
  if (existingContent === TESTING_TYPES_STUB) {
    return true;
  }
  return existingContent.startsWith(GENERATED_TESTING_TYPES_PREFIX);
}

async function inferInitialTestPlayerCount(
  projectRoot: string,
): Promise<number> {
  const manifestPath = path.join(projectRoot, "manifest.ts");
  if (!(await exists(manifestPath))) {
    return 4;
  }

  try {
    const manifest = await materializeManifest(projectRoot);
    return manifest.players.optimalPlayers ?? manifest.players.minPlayers ?? 4;
  } catch {
    return 4;
  }
}

async function collectScenarioFiles(rootDir: string): Promise<string[]> {
  const files: string[] = [];
  const stack = [rootDir];

  while (stack.length > 0) {
    const dir = stack.pop();
    if (!dir) continue;

    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
      } else if (entry.isFile() && entry.name.endsWith(".ts")) {
        files.push(fullPath);
      }
    }
  }

  return files;
}

export function resolveStaticAssetRoot(
  importUrl: string = import.meta.url,
): string {
  const candidates = [
    fileURLToPath(new URL("../../scaffold/assets/static/", importUrl)),
    fileURLToPath(new URL("./scaffold/assets/static/", importUrl)),
    fileURLToPath(new URL("../scaffold/assets/static/", importUrl)),
  ];

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  throw new Error(
    `Unable to locate CLI static scaffold assets. Checked: ${candidates.join(", ")}`,
  );
}

async function getStaticAssetEntries(): Promise<StaticAssetEntry[]> {
  const files = await walkFiles(STATIC_ASSET_ROOT);
  const entries: StaticAssetEntry[] = [];

  for (const filePath of files) {
    const targetPath = normalizeProjectPath(
      path.relative(STATIC_ASSET_ROOT, filePath),
    );
    entries.push({
      targetPath,
      content: await readFile(filePath, "utf8"),
    });
  }

  entries.sort((left, right) =>
    left.targetPath.localeCompare(right.targetPath),
  );
  return entries;
}

async function getDynamicStaticEntries(
  projectRoot: string,
  mode: StaticScaffoldMode,
  options: StaticScaffoldOptions = {},
): Promise<StaticAssetEntry[]> {
  const entries: StaticAssetEntry[] = [
    {
      targetPath: "package.json",
      content: await buildRootPackageJson(projectRoot, mode, options),
    },
    {
      targetPath: "ui/package.json",
      content: buildUiPackageJson(),
    },
  ];

  if (options.localMaintainerRegistry) {
    entries.push({
      targetPath: ".npmrc",
      content: buildWorkspaceNpmrc(options.localMaintainerRegistry.registryUrl),
    });
  }

  return entries;
}

async function readProjectLocalMaintainerRegistry(
  projectRoot: string,
): Promise<LocalMaintainerRegistryConfig | null> {
  const projectConfigPath = path.join(
    projectRoot,
    PROJECT_DIR_NAME,
    PROJECT_CONFIG_FILE,
  );
  if (!(await exists(projectConfigPath))) {
    return null;
  }

  const projectConfig = await readJsonFile<{
    localMaintainerRegistry?: LocalMaintainerRegistryConfig;
  }>(projectConfigPath);
  return projectConfig.localMaintainerRegistry ?? null;
}

async function getExpectedStaticEntries(
  projectRoot: string,
): Promise<StaticAssetEntry[]> {
  const entries = [
    ...(await getStaticAssetEntries()),
    ...(await getDynamicStaticEntries(projectRoot, "update", {
      localMaintainerRegistry:
        await readProjectLocalMaintainerRegistry(projectRoot),
    })),
  ];
  entries.sort((left, right) =>
    left.targetPath.localeCompare(right.targetPath),
  );
  return entries;
}

async function walkFiles(rootDir: string): Promise<string[]> {
  const files: string[] = [];
  const stack = [rootDir];

  while (stack.length > 0) {
    const currentDir = stack.pop();
    if (!currentDir) continue;

    const entries = await readdir(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
      } else if (entry.isFile()) {
        files.push(fullPath);
      }
    }
  }

  files.sort((left, right) => left.localeCompare(right));
  return files;
}

async function buildRootPackageJson(
  projectRoot: string,
  mode: StaticScaffoldMode,
  options: StaticScaffoldOptions,
): Promise<string> {
  const sdkDependencyRanges =
    options.localMaintainerRegistry?.packages ?? SDK_DEPENDENCY_RANGES;
  const packageJsonPath = path.join(projectRoot, "package.json");
  const existingPackageJson =
    mode === "update" && (await exists(packageJsonPath))
      ? await readJsonFile<RootPackageJsonShape>(packageJsonPath)
      : null;
  const frameworkDependencies = {
    "@dreamboard/app-sdk": sdkDependencyRanges["@dreamboard/app-sdk"],
    "@dreamboard/ui-sdk": sdkDependencyRanges["@dreamboard/ui-sdk"],
    ...SHARED_DEPENDENCIES,
  };
  const frameworkDevDependencies = {
    "@dreamboard/sdk-types": sdkDependencyRanges["@dreamboard/sdk-types"],
    ...SHARED_DEV_DEPENDENCIES,
  };
  const nextPackageJson: RootPackageJsonShape = {
    ...(existingPackageJson ?? {}),
    private: true,
    scripts: {
      ...(existingPackageJson?.scripts ?? {}),
      ...FRAMEWORK_SCRIPTS,
    },
    dependencies: {
      ...(existingPackageJson?.dependencies ?? {}),
      ...frameworkDependencies,
    },
    devDependencies: {
      ...(existingPackageJson?.devDependencies ?? {}),
      ...frameworkDevDependencies,
    },
  };
  return `${JSON.stringify(nextPackageJson, null, 2)}\n`;
}

function buildWorkspaceNpmrc(registryUrl: string): string {
  return `@dreamboard:registry=${registryUrl}\n`;
}

function buildUiPackageJson(): string {
  return `${JSON.stringify(
    {
      private: true,
      dependencies: SHARED_DEPENDENCIES,
      devDependencies: SHARED_DEV_DEPENDENCIES,
    },
    null,
    2,
  )}\n`;
}

function readPackageVersion(
  packageJsonPath: string,
  packageName: string,
): string | null {
  const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8")) as {
    version?: unknown;
  };

  if (
    typeof packageJson.version !== "string" ||
    packageJson.version.trim().length === 0
  ) {
    return null;
  }

  return `^${packageJson.version.trim()}`;
}

function findNearestPackageJsonPath(
  importMetaUrl: string = import.meta.url,
): string | null {
  let current = path.dirname(fileURLToPath(importMetaUrl));

  while (true) {
    const candidate = path.join(current, "package.json");
    if (existsSync(candidate)) {
      return candidate;
    }

    const parent = path.dirname(current);
    if (parent === current) {
      return null;
    }
    current = parent;
  }
}

function readPackagedSdkDependencyRange(
  packageName: keyof typeof SDK_PACKAGE_PATHS,
  importMetaUrl: string = import.meta.url,
): string | null {
  const packageJsonPath = findNearestPackageJsonPath(importMetaUrl);
  if (!packageJsonPath) {
    return null;
  }

  const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8")) as {
    dependencies?: Record<string, unknown>;
    dreamboardSdkDependencyRanges?: Record<string, unknown>;
  };

  const packagedRange =
    packageJson.dreamboardSdkDependencyRanges?.[packageName] ??
    packageJson.dependencies?.[packageName];
  if (
    typeof packagedRange !== "string" ||
    packagedRange.trim().length === 0 ||
    packagedRange.startsWith("workspace:")
  ) {
    return null;
  }

  return packagedRange.trim();
}

export function resolveSdkDependencyRange(
  packageName: keyof typeof SDK_PACKAGE_PATHS,
  importMetaUrl: string = import.meta.url,
): string {
  try {
    const repoRoot = resolveCliRepoRoot(importMetaUrl);
    const packageJsonPath = path.join(
      repoRoot,
      ...SDK_PACKAGE_PATHS[packageName],
    );
    const repoRange = readPackageVersion(packageJsonPath, packageName);
    if (repoRange) {
      return repoRange;
    }
  } catch {
    // Published installs do not include the monorepo layout.
  }

  const packagedRange = readPackagedSdkDependencyRange(
    packageName,
    importMetaUrl,
  );
  if (packagedRange) {
    return packagedRange;
  }

  return DEFAULT_SDK_DEPENDENCY_RANGES[packageName];
}

function normalizeImportPath(relativePath: string): string {
  const normalized = relativePath.replaceAll("\\", "/");
  if (normalized.startsWith(".")) return normalized;
  return `./${normalized}`;
}

function normalizeProjectPath(filePath: string): string {
  return filePath.replace(/^\.\//, "").replace(/^\/+/, "").replace(/\\/g, "/");
}

function summarizePaths(paths: readonly string[]): string {
  const maxShown = 5;
  const shown = paths.slice(0, maxShown).join(", ");
  if (paths.length <= maxShown) return shown;
  return `${shown}, and ${paths.length - maxShown} more`;
}
