import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { expect, test } from "bun:test";
import type { GameTopologyManifest } from "@dreamboard/sdk-types";
import { applyWorkspaceCodegen } from "./workspace-codegen.js";

const TEST_MANIFEST: GameTopologyManifest = {
  cardSets: [],
  zones: [],
  boardTemplates: [],
  boards: [],
  pieceTypes: [],
  pieceSeeds: [],
  dieTypes: [],
  dieSeeds: [],
  players: {
    minPlayers: 2,
    maxPlayers: 4,
    optimalPlayers: 2,
  },
  resources: [],
  setupOptions: [],
  setupProfiles: [],
};

test("applyWorkspaceCodegen preserves a non-empty ui/App.tsx", async () => {
  const projectRoot = await mkdtemp(
    path.join(os.tmpdir(), "db-workspace-codegen-"),
  );
  const existingAppContent =
    "export default function App() { return <div>custom ui</div>; }\n";

  try {
    await Bun.write(
      path.join(projectRoot, "ui", "App.tsx"),
      existingAppContent,
    );

    const result = await applyWorkspaceCodegen({
      projectRoot,
      manifest: TEST_MANIFEST,
    });

    expect(
      await readFile(path.join(projectRoot, "ui", "App.tsx"), "utf8"),
    ).toBe(existingAppContent);
    expect(result.skipped).toContain("ui/App.tsx");
    expect(result.written).not.toContain("ui/App.tsx");
  } finally {
    await rm(projectRoot, { recursive: true, force: true });
  }
});

test("applyWorkspaceCodegen reseeds ui/App.tsx when the local file is blank", async () => {
  const projectRoot = await mkdtemp(
    path.join(os.tmpdir(), "db-workspace-codegen-"),
  );

  try {
    await Bun.write(path.join(projectRoot, "ui", "App.tsx"), "\n");

    const result = await applyWorkspaceCodegen({
      projectRoot,
      manifest: TEST_MANIFEST,
    });
    const appContent = await readFile(
      path.join(projectRoot, "ui", "App.tsx"),
      "utf8",
    );

    expect(appContent.trim().length).toBeGreaterThan(0);
    expect(appContent).toContain("Game UI");
    expect(appContent).not.toBe("\n");
    expect(result.written).toContain("ui/App.tsx");
    expect(result.skipped).not.toContain("ui/App.tsx");
  } finally {
    await rm(projectRoot, { recursive: true, force: true });
  }
});

test("applyWorkspaceCodegen refreshes framework-owned setup-profiles placeholders", async () => {
  const projectRoot = await mkdtemp(
    path.join(os.tmpdir(), "db-workspace-codegen-"),
  );
  const manifestWithProfile: GameTopologyManifest = {
    ...TEST_MANIFEST,
    setupProfiles: [
      {
        id: "draft",
        name: "Draft",
      },
    ],
  };

  try {
    await Bun.write(
      path.join(projectRoot, "app", "setup-profiles.ts"),
      `// Generated by dreamboard setup-profiles scaffold.
import { setupProfiles } from "../shared/manifest-contract";

export default setupProfiles({
  "old-profile": {},
});
`,
    );

    const result = await applyWorkspaceCodegen({
      projectRoot,
      manifest: manifestWithProfile,
    });
    const content = await readFile(
      path.join(projectRoot, "app", "setup-profiles.ts"),
      "utf8",
    );

    expect(content).toContain(
      "Generated by dreamboard setup-profiles scaffold.",
    );
    expect(content).toContain('"draft": {}');
    expect(content).not.toContain('"old-profile": {}');
    expect(result.written).toContain("app/setup-profiles.ts");
    expect(result.skipped).not.toContain("app/setup-profiles.ts");
  } finally {
    await rm(projectRoot, { recursive: true, force: true });
  }
});

test("applyWorkspaceCodegen preserves customized setup-profiles definitions", async () => {
  const projectRoot = await mkdtemp(
    path.join(os.tmpdir(), "db-workspace-codegen-"),
  );
  const customContent = `import {
  setupProfiles,
} from "../shared/manifest-contract";

export default setupProfiles({
  "draft": {
    initialPhase: "setup",
  },
});
`;

  try {
    await Bun.write(
      path.join(projectRoot, "app", "setup-profiles.ts"),
      customContent,
    );

    const result = await applyWorkspaceCodegen({
      projectRoot,
      manifest: {
        ...TEST_MANIFEST,
        setupProfiles: [
          {
            id: "draft",
            name: "Draft",
          },
          {
            id: "final",
            name: "Final",
          },
        ],
      },
    });

    expect(
      await readFile(
        path.join(projectRoot, "app", "setup-profiles.ts"),
        "utf8",
      ),
    ).toBe(customContent);
    expect(result.skipped).toContain("app/setup-profiles.ts");
    expect(result.written).not.toContain("app/setup-profiles.ts");
  } finally {
    await rm(projectRoot, { recursive: true, force: true });
  }
});
