import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
);
const ownershipJsonPath = path.join(
  repoRoot,
  "packages",
  "sdk-types",
  "scaffolding",
  "ownership.json",
);
const outputTsPath = path.join(
  repoRoot,
  "apps",
  "dreamboard-cli",
  "src",
  "services",
  "project",
  "scaffold-ownership.generated.ts",
);

async function main(): Promise<void> {
  const raw = await readFile(ownershipJsonPath, "utf8");
  const parsed = JSON.parse(raw);

  const output = `/**
 * Generated by apps/dreamboard-cli/scripts/sync-scaffold-ownership.ts.
 * Source: packages/sdk-types/scaffolding/ownership.json
 * Do not edit manually.
 */

export type OwnershipPattern = {
  prefix: string;
  suffix: string;
};

export type ScaffoldingOwnership = {
  version: number;
  allowedPaths: {
    rootFiles: string[];
    directoryPrefixes: string[];
  };
  dynamic: {
    generatedFiles: string[];
    seedFiles: string[];
    seedFilePatterns: OwnershipPattern[];
  };
  cliStatic: {
    exactFiles: string[];
    directoryPrefixes: string[];
  };
  preservedUserFiles: string[];
};

export const SCAFFOLD_OWNERSHIP: ScaffoldingOwnership = ${JSON.stringify(parsed, null, 2)};
`;

  const prettierConfig = await resolveConfig(outputTsPath);
  const formattedOutput = await format(output, {
    ...prettierConfig,
    filepath: outputTsPath,
  });

  await mkdir(path.dirname(outputTsPath), { recursive: true });
  await writeFile(outputTsPath, formattedOutput, "utf8");
  console.log("Synced scaffold ownership.");
}

await main();
