import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  assertPublicSkillScriptsArePublishable,
  IGNORED_PUBLIC_SKILL_ENTRY_NAMES,
  resolvePublicSkillRoot,
} from "./public-skill-utils.ts";

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const outputPath = path.join(
  packageRoot,
  "src",
  "generated",
  "skill-content.generated.ts",
);

async function collectSkillAssets(
  rootDir: string,
): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const stack = [rootDir];

  while (stack.length > 0) {
    const currentDir = stack.pop();
    if (!currentDir) continue;

    const entries = await readdir(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      if (IGNORED_PUBLIC_SKILL_ENTRY_NAMES.has(entry.name)) {
        continue;
      }
      const fullPath = path.join(currentDir, entry.name);
      const relativePath = path
        .relative(rootDir, fullPath)
        .replaceAll("\\", "/");

      if (entry.isDirectory()) {
        stack.push(fullPath);
        continue;
      }
      if (!entry.isFile()) continue;

      files[relativePath] = await readFile(fullPath, "utf8");
    }
  }

  return Object.fromEntries(
    Object.entries(files).sort(([left], [right]) => left.localeCompare(right)),
  );
}

const publicSkillRoot = await resolvePublicSkillRoot();
await assertPublicSkillScriptsArePublishable(publicSkillRoot);
const skillAssets = await collectSkillAssets(publicSkillRoot);
const output = `// Generated by apps/dreamboard-cli/scripts/sync-skill-content.ts.
// Do not edit this file directly; update skills/dreamboard/**/* instead.

export const SKILL_ASSET_FILES = ${JSON.stringify(skillAssets, null, 2)} as const;

export const SKILL_MD_CONTENT = SKILL_ASSET_FILES["SKILL.md"];\n`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, output, "utf8");

process.stdout.write("Synced skill content.\n");
