import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { resolvePublicSkillRoot } from "./public-skill-utils.ts";

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const repoRoot = path.resolve(packageRoot, "..", "..");
const docsRoot = path.join(repoRoot, "docs");

const DOCS_TO_COPY = [
  {
    sourcePath: "quickstart.mdx",
    docsHref: "/docs/quickstart",
    outputName: "quickstart.md",
  },
  {
    sourcePath: "tutorials/building-your-first-game.mdx",
    docsHref: "/docs/tutorials/building-your-first-game",
    outputName: "building-your-first-game.md",
  },
  {
    sourcePath: "reference/rule-authoring.mdx",
    docsHref: "/docs/reference/rule-authoring",
    outputName: "rule-authoring.md",
  },
  {
    sourcePath: "reference/manifest-authoring.mdx",
    docsHref: "/docs/reference/manifest-authoring",
    outputName: "manifest-authoring.md",
  },
  {
    sourcePath: "reference/reducer.mdx",
    docsHref: "/docs/reference/reducer",
    outputName: "reducer.md",
  },
  {
    sourcePath: "reference/game-interface.mdx",
    docsHref: "/docs/reference/game-interface",
    outputName: "game-interface.md",
  },
  {
    sourcePath: "reference/testing.mdx",
    docsHref: "/docs/reference/testing",
    outputName: "testing.md",
  },
] as const;

type ManagedDoc = (typeof DOCS_TO_COPY)[number];

function stripQuotes(value: string): string {
  return value.replace(/^['"]|['"]$/g, "").trim();
}

function parseFrontmatter(source: string): {
  title: string | null;
  description: string | null;
  body: string;
} {
  const frontmatterMatch = source.match(/^---\n([\s\S]*?)\n---\n*/u);
  if (!frontmatterMatch) {
    return {
      title: null,
      description: null,
      body: source.trim(),
    };
  }

  const frontmatter = frontmatterMatch[1];
  const titleMatch = frontmatter.match(/^title:\s*(.+)$/mu);
  const descriptionMatch = frontmatter.match(/^description:\s*(.+)$/mu);

  return {
    title: titleMatch ? stripQuotes(titleMatch[1]) : null,
    description: descriptionMatch ? stripQuotes(descriptionMatch[1]) : null,
    body: source.slice(frontmatterMatch[0].length).trim(),
  };
}

function rewriteDocLinks(markdown: string): string {
  let output = markdown;

  for (const doc of DOCS_TO_COPY) {
    const replacement = `./${doc.outputName}`;
    const docsUrls = [
      doc.docsHref,
      `https://dreamboard.games${doc.docsHref}`,
    ];

    for (const docsUrl of docsUrls) {
      output = output.replaceAll(`](${docsUrl})`, `](${replacement})`);
    }
  }

  return output;
}

function renderReference(doc: ManagedDoc, source: string): string {
  const { title, description, body } = parseFrontmatter(source);
  const resolvedTitle =
    title ??
    doc.outputName.replace(/\.md$/u, "").replace(/-/gu, " ");

  const parts = [
    "<!-- Generated by apps/dreamboard-cli/scripts/sync-skill-docs.ts. -->",
    `<!-- Source: docs/${doc.sourcePath} -->`,
    "",
    `# ${resolvedTitle}`,
  ];

  if (description) {
    parts.push("", description);
  }

  parts.push("", rewriteDocLinks(body), "");

  return parts.join("\n");
}

async function main() {
  const publicSkillRoot = await resolvePublicSkillRoot();
  const referencesRoot = path.join(publicSkillRoot, "references");

  try {
    await readFile(path.join(docsRoot, "reference", "reducer.mdx"), "utf8");
  } catch {
    process.stdout.write("Skipped skill docs sync because repo docs were not found.\n");
    return;
  }

  await mkdir(referencesRoot, { recursive: true });

  for (const doc of DOCS_TO_COPY) {
    const sourcePath = path.join(docsRoot, doc.sourcePath);
    const outputPath = path.join(referencesRoot, doc.outputName);
    const source = await readFile(sourcePath, "utf8");
    const rendered = renderReference(doc, source);
    await writeFile(outputPath, rendered, "utf8");
  }

  process.stdout.write("Synced skill docs into references/.\n");
}

await main();
