export const REDUCER_TESTING_TYPES_WRAPPER_CONTENT = `\
// Generated by dreamboard — do not edit by hand.
export * from "./generated/testing-contract";
`;

export const REDUCER_TESTING_CONTRACT_CONTENT = `\
// Generated by dreamboard — do not edit by hand.
import type game from "../../app/game";
import { literals, type SetupProfileId } from "../../shared/manifest-contract";
import {
  phaseCommands,
  type ActionCommandForPhase,
  type ActionName,
  type ActionParams,
  type GameView,
  type PhaseName,
  type PromptId,
  type PromptResponse,
} from "../../shared/generated/ui-contract";
import type { GameplayPromptInstance } from "@dreamboard/ui-sdk";

export type GameDefinition = typeof game;
export type PlayerId = (typeof literals.playerIds)[number];
export type StateName = PhaseName;
export type PromptInstance<Name extends PromptId = PromptId> =
  GameplayPromptInstance<Name>;
export type TestRunner = "reducer" | "embedded" | "browser";

type DefaultRunners = readonly ["reducer"];

export type AnyActionCommand = {
  [Name in PhaseName]: ActionCommandForPhase<Name>;
}[PhaseName];

export type ExpectFn = (actual: unknown) => {
  toBe(expected: unknown): void;
  toEqual(expected: unknown): void;
  toBeDefined(): void;
  toBeUndefined(): void;
  toBeNull(): void;
  toContain(expected: unknown): void;
  toBeGreaterThanOrEqual(expected: number): void;
};

export interface BrowserRunnerSnapshot {
  sessionId: string | null;
  shortCode: string | null;
  version: number;
  currentPhase: string | null;
  controllingPlayerId: string;
  controllablePlayerIds: string[];
  seatViewsByPlayerId: Record<string, unknown>;
  availableActionsByPlayerId?: Record<string, string[]>;
  prompts: readonly PromptInstance[];
}

export interface BrowserRunnerBridge {
  snapshot(): Promise<BrowserRunnerSnapshot>;
  submitAction(playerId: PlayerId, actionType: string, params: Record<string, unknown>): Promise<void>;
  submitPromptResponse(playerId: PlayerId, promptId: string, response: unknown): Promise<void>;
}

export interface BrowserRunnerDriver {
  onReady?(bridge: BrowserRunnerBridge): Promise<void> | void;
  action?(
    bridge: BrowserRunnerBridge,
    input: { playerId: PlayerId; actionType: string; params: Record<string, unknown> },
  ): Promise<boolean | void> | boolean | void;
  promptResponse?(
    bridge: BrowserRunnerBridge,
    input: { playerId: PlayerId; promptId: string; response: unknown },
  ): Promise<boolean | void> | boolean | void;
}

export interface ScenarioGameApi {
  start(): Promise<void>;
  action<Name extends ActionName>(
    playerId: PlayerId,
    actionType: Name,
    params: ActionParams<Name>,
  ): Promise<void>;
  action(playerId: PlayerId, command: AnyActionCommand): Promise<void>;
  respond<Name extends PromptId>(
    playerId: PlayerId,
    prompt: Name | PromptInstance<Name>,
    response: PromptResponse<Name>,
  ): Promise<void>;
  expectPrompt<Name extends PromptId>(
    playerId: PlayerId,
    promptId: Name,
  ): Promise<PromptInstance<Name>>;
}

export interface BaseContext {
  game: ScenarioGameApi;
}

export interface SharedScenarioContext {
  game: ScenarioGameApi;
  players(): readonly PlayerId[];
  state(): StateName;
  view(playerId: PlayerId): GameView;
  prompts(playerId: PlayerId): readonly PromptInstance[];
  expect: ExpectFn;
}

export type ScenarioThenContext<
  _Runners extends readonly TestRunner[] = DefaultRunners,
> = SharedScenarioContext;

export interface BaseDefinition {
  id: string;
  seed: number;
  players: number;
  setupProfileId?: SetupProfileId;
  setup: (ctx: BaseContext) => void | Promise<void>;
}

export interface ScenarioDefinition<
  Runners extends readonly TestRunner[] = DefaultRunners,
> {
  id: string;
  description?: string;
  from: string;
  runners?: Runners;
  when: (ctx: SharedScenarioContext) => void | Promise<void>;
  then: (ctx: ScenarioThenContext<Runners>) => void | Promise<void>;
}

export { phaseCommands };
export type {
  ActionCommandForPhase,
  ActionName,
  ActionParams,
  GameView,
  PhaseName,
  PromptId,
  PromptResponse,
};

export function defineBase<const Definition extends BaseDefinition>(
  definition: Definition,
): Definition {
  return definition;
}

export function defineScenario<
  const Runners extends readonly TestRunner[] = DefaultRunners,
>(definition: ScenarioDefinition<Runners>): ScenarioDefinition<Runners> {
  return definition;
}
`;
